// card_support_gallery_postgres_test.go
// Proves gallery rights, mandatory flags and exact-row denials on PostgreSQL.
// Extends the existing opt-in owner-resolver fixture with a real gallery.
// The owning metadata/parent retry cannot rescue denied gallery content.
package dtt_1_row_read

import (
	backend "easelect/backend/core_components"
	"easelect/backend/core_components/dbutils"
	dtt_models "easelect/backend/core_components/dynamic_table_tools/dtt_models"
	"fmt"
	"testing"
)

func TestCardSupportGalleryAuthorizationPostgres(t *testing.T) {
	owner, reader := ownerResolverPostgres(t)
	exec := func(query string) {
		t.Helper()
		if _, err := owner.Exec(query); err != nil {
			t.Fatal(err)
		}
	}
	exec(`CREATE TABLE system_functions(id integer PRIMARY KEY,url_route_endpoint text,disabled boolean);
 CREATE TABLE system_group_table_func_rights(user_group_id bigint,function_id integer,target_table_uid bigint);
 CREATE TABLE system_foreign_key_relations_1_m(id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,source_table_uid bigint,target_table_uid bigint,source_column_name text,target_insert_specs jsonb);
 CREATE TABLE card_guard_parent(id integer PRIMARY KEY,cached_image text);
 CREATE TABLE card_guard_gallery(id integer PRIMARY KEY,parent_id integer REFERENCES card_guard_parent(id),filename text,asset_kind text,published boolean,is_primary boolean,sort_order integer);
 INSERT INTO system_db_tables(table_uid,table_name) VALUES(100,'card_guard_parent'),(101,'card_guard_gallery');
 INSERT INTO system_column_details VALUES(101,'published',true);
 INSERT INTO system_functions VALUES(1,'/api/get-results',false);
 INSERT INTO system_user_group_memberships VALUES(4,2);
 INSERT INTO system_foreign_key_relations_1_m(source_table_uid,target_table_uid,source_column_name,target_insert_specs) VALUES(101,100,'parent_id','{"file_upload":{"filename_column":"filename","profiles":{"image":{}}}}');
 INSERT INTO card_guard_parent VALUES(1,'hidden.png'),(2,'denied.png');
 INSERT INTO card_guard_gallery VALUES(1,1,E'\thidden.png\n','image',false,true,0),(2,1,'visible.png','image',true,false,1),(3,2,'denied.png','image',true,true,0);
 INSERT INTO system_row_access_rules(table_uid,action_id,row_id,user_id,effect) VALUES(101,1,3,4,'deny');
 GRANT SELECT ON ALL TABLES IN SCHEMA public TO wl58_reader;`)
	old := backend.Db
	backend.Db = owner
	t.Cleanup(func() { backend.Db = old })
	actor := dbutils.NewRequestActorContext(4, "user")
	columns := map[int]dtt_models.ColumnInfo{1: {ColumnName: "cached_image", CardElement: "image"}}
	read := func(cached bool) []map[string]interface{} {
		t.Helper()
		rows := []map[string]interface{}{{"id": int64(1)}, {"id": int64(2)}}
		if cached {
			rows[0]["cached_image"] = "hidden.png"
			rows[1]["cached_image"] = "denied.png"
			rows[1]["cached_image_title"] = "private metadata"
		}
		if err := enrichRowsWithCardSupportColumns(reader, "card_guard_parent", rows, columns, nil, actor, nil); err != nil {
			t.Fatal(err)
		}
		if err := guardGalleryCachedImages(reader, "card_guard_parent", rows, actor, nil); err != nil {
			t.Fatal(err)
		}
		return rows
	}
	for _, cached := range []bool{false, true} {
		for _, row := range read(cached) {
			if _, ok := row["cached_image"]; ok {
				t.Fatal("rightless gallery disclosed image", row)
			}
		}
	}
	exec(`INSERT INTO system_group_table_func_rights VALUES(2,1,101)`)
	for _, cached := range []bool{false, true} {
		rows := read(cached)
		if _, ok := rows[0]["cached_image"]; ok {
			t.Fatal("hidden cache was replaced", rows)
		}
		if _, ok := rows[1]["cached_image"]; ok {
			t.Fatal("exact-row denied cache was returned", rows)
		}
		if _, ok := rows[1]["cached_image_title"]; ok {
			t.Fatal("denied cache metadata was returned", rows)
		}
	}
	exec(`UPDATE card_guard_parent SET cached_image='visible.png' WHERE id=1`)
	if rows := read(false); rows[0]["cached_image"] != "visible.png" {
		t.Fatal("visible gallery cache missing", rows)
	}
	// Response preparation with either parameter form must compare file identity,
	// including alternate gallery spellings, without modifying equal-basename media.
	for _, allowed := range []bool{false, true} {
		if allowed {
			exec(`INSERT INTO system_group_table_func_rights VALUES(2,1,101)`)
		} else {
			exec(`DELETE FROM system_group_table_func_rights`)
		}
		for _, include := range []bool{false, true} {
			for _, test := range []struct {
				name, cached string
				parentID     int64
				kept         bool
			}{
				{"hidden fragment", "hidden.png#preview", 1, false},
				{"denied fragment", "denied.png#preview", 2, false},
				{"hidden storage alias", "/storage/100/1/300/hidden.png?size=300#preview", 1, false},
				{"external same basename", "https://example.org/hidden.png#preview", 1, true},
				{"library same basename", "/storage/media/174668a1-2efa-45a6-aa6c-d8a4ee8ec069/300/hidden.png", 1, true},
				{"other row same basename", "/storage/100/888/300/hidden.png#preview", 1, true},
			} {
				t.Run(fmt.Sprintf("right=%t/include=%t/%s", allowed, include, test.name), func(t *testing.T) {
					rows := []map[string]interface{}{{"id": test.parentID, "cached_image": test.cached, "cached_image_title": "original title"}}
					if err := prepareRowsForCardResponse(reader, "card_guard_parent", rows, columns, nil, actor, include); err != nil {
						t.Fatal(err)
					}
					if test.kept {
						if rows[0]["cached_image"] != test.cached || rows[0]["cached_image_title"] != "original title" {
							t.Fatal("independent picture or metadata changed", rows)
						}
					} else if _, ok := rows[0]["cached_image"]; ok {
						t.Fatal("gallery alias escaped", rows)
					} else if _, ok := rows[0]["cached_image_title"]; ok {
						t.Fatal("gallery companion escaped", rows)
					}
				})
			}
		}
	}
	exec(`REVOKE SELECT ON card_guard_gallery FROM wl58_reader`)
	rows := []map[string]interface{}{{"id": int64(1), "cached_image": "hidden.png"}}
	if err := enrichRowsWithCanonicalAssetImages(reader, "card_guard_parent", rows, []int64{1}, actor, nil); err == nil {
		t.Fatal("fixture content denial did not happen")
	}
	if err := guardGalleryCachedImages(reader, "card_guard_parent", rows, actor, nil); err != nil {
		t.Fatal(err)
	}
	if _, ok := rows[0]["cached_image"]; ok {
		t.Fatal("owner connection rescued gallery content", rows)
	}
}
