// route_function_identity_test.go
// Verifies that safe handler renames preserve route identities and permission grants.
// Connects startup registration decisions with a disposable PostgreSQL fixture.
// Exists because replacing a route row silently strands administrator-granted access.
package router

import (
	"bytes"
	"database/sql"
	"fmt"
	"log"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	_ "github.com/lib/pq"
)

func routeIdentityDisposableDB(t *testing.T) *sql.DB {
	t.Helper()
	if os.Getenv("FILTEREST_TEST_DISPOSABLE_POSTGRES") != "1" {
		t.Skip("set FILTEREST_TEST_DISPOSABLE_POSTGRES=1 to run isolated PostgreSQL verification")
	}

	root := t.TempDir()
	socket := filepath.Join(root, "socket")
	if err := os.Mkdir(socket, 0o700); err != nil {
		t.Fatal(err)
	}
	data := filepath.Join(root, "db")
	bin := "/usr/lib/postgresql/16/bin/"
	run := func(name string, args ...string) {
		t.Helper()
		if output, err := exec.Command(bin+name, args...).CombinedOutput(); err != nil {
			t.Fatalf("%s: %v: %s", name, err, output)
		}
	}

	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("find unused PostgreSQL port: %v", err)
	}
	port := listener.Addr().(*net.TCPAddr).Port
	if err := listener.Close(); err != nil {
		t.Fatalf("release unused PostgreSQL port: %v", err)
	}

	run("initdb", "-D", data, "-A", "trust", "-U", "test_owner", "--no-locale", "--encoding=UTF8")
	t.Cleanup(func() {
		_, _ = exec.Command(bin+"pg_ctl", "-D", data, "-m", "immediate", "-w", "stop").CombinedOutput()
	})
	run(
		"pg_ctl",
		"-D", data,
		"-l", filepath.Join(root, "postgres.log"),
		"-o", fmt.Sprintf("-h '' -k '%s' -p %d", socket, port),
		"-w", "start",
	)

	db, err := sql.Open(
		"postgres",
		fmt.Sprintf("host=%s port=%d user=test_owner dbname=postgres sslmode=disable", socket, port),
	)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = db.Close() })

	if _, err := db.Exec(`
		CREATE TABLE system_functions (
			id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name text UNIQUE,
			"package" text,
			disabled boolean,
			specific_table_related boolean,
			url_route_endpoint text,
			rate_limit_amount integer,
			rate_limit_minutes integer,
			ui_only boolean
		);
		CREATE TABLE system_group_table_func_rights (
			id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			function_id integer NOT NULL
		);
	`); err != nil {
		t.Fatal(err)
	}
	return db
}

func resetRouteIdentityFixture(t *testing.T, db *sql.DB) {
	t.Helper()
	if _, err := db.Exec(`
		TRUNCATE system_group_table_func_rights, system_functions RESTART IDENTITY
	`); err != nil {
		t.Fatal(err)
	}
}

func registerMissingRouteForTest(
	t *testing.T,
	db *sql.DB,
	rd RouteDefinition,
	registeredHandlerNames map[string]bool,
) int {
	t.Helper()
	rateLimitAmount, rateLimitMinutes := defaultRateLimitForHandler(rd.HandlerName)
	id, err := registerMissingRouteFunction(
		db,
		rd,
		registeredHandlerNames,
		getPackageNameFromHandler(rd.HandlerName),
		rateLimitAmount,
		rateLimitMinutes,
	)
	if err != nil {
		t.Fatalf("register missing route: %v", err)
	}
	return id
}

func TestMissingRouteFunctionRegistrationPostgres(t *testing.T) {
	db := routeIdentityDisposableDB(t)

	var logs bytes.Buffer
	previousLogWriter := log.Writer()
	previousLogFlags := log.Flags()
	log.SetOutput(&logs)
	log.SetFlags(0)
	t.Cleanup(func() {
		log.SetOutput(previousLogWriter)
		log.SetFlags(previousLogFlags)
	})

	t.Run("renamed handler keeps its row and grants", func(t *testing.T) {
		resetRouteIdentityFixture(t, db)
		logs.Reset()
		if _, err := db.Exec(`
			INSERT INTO system_functions (
				id, name, "package", disabled, specific_table_related,
				url_route_endpoint, rate_limit_amount, rate_limit_minutes, ui_only
			) VALUES (41, 'oldpkg.AdminHandler', 'oldpkg', false, true, '/admin/', 17, 3, false);
			INSERT INTO system_group_table_func_rights (function_id) VALUES (41), (41);
		`); err != nil {
			t.Fatal(err)
		}

		rd := RouteDefinition{UrlPattern: "/admin/", HandlerName: "newpkg.AdminHandler"}
		id := registerMissingRouteForTest(t, db, rd, map[string]bool{rd.HandlerName: true})
		if id != 41 {
			t.Fatalf("registered row id = %d, want preserved id 41", id)
		}

		var name, packageName string
		var specificTableRelated bool
		var rateLimitAmount, rateLimitMinutes, grants int
		if err := db.QueryRow(`
			SELECT name, "package", specific_table_related, rate_limit_amount, rate_limit_minutes,
			       (SELECT COUNT(*) FROM system_group_table_func_rights WHERE function_id = 41)
			  FROM system_functions
			 WHERE id = 41
		`).Scan(
			&name,
			&packageName,
			&specificTableRelated,
			&rateLimitAmount,
			&rateLimitMinutes,
			&grants,
		); err != nil {
			t.Fatal(err)
		}
		if name != rd.HandlerName || packageName != "newpkg" {
			t.Fatalf("adopted identity = %q/%q, want %q/newpkg", name, packageName, rd.HandlerName)
		}
		if !specificTableRelated || rateLimitAmount != 17 || rateLimitMinutes != 3 {
			t.Fatalf(
				"administrator settings changed: table-related=%v rate=%d/%d",
				specificTableRelated,
				rateLimitAmount,
				rateLimitMinutes,
			)
		}
		if grants != 2 {
			t.Fatalf("grants on preserved row = %d, want 2", grants)
		}
		for _, expected := range []string{"/admin/", "oldpkg.AdminHandler", rd.HandlerName, "2 permission grants"} {
			if !strings.Contains(logs.String(), expected) {
				t.Fatalf("adoption log %q does not contain %q", logs.String(), expected)
			}
		}
	})

	t.Run("ambiguous address inserts and explains why", func(t *testing.T) {
		resetRouteIdentityFixture(t, db)
		logs.Reset()
		if _, err := db.Exec(`
			INSERT INTO system_functions
				(name, "package", disabled, specific_table_related, url_route_endpoint, ui_only)
			VALUES
				('oldpkg.FirstHandler', 'oldpkg', true, false, '/shared', false),
				('oldpkg.SecondHandler', 'oldpkg', false, false, '/shared', false)
		`); err != nil {
			t.Fatal(err)
		}

		rd := RouteDefinition{UrlPattern: "/shared", HandlerName: "newpkg.SharedHandler"}
		newID := registerMissingRouteForTest(t, db, rd, map[string]bool{rd.HandlerName: true})
		var rowCount, unchangedOldRows int
		if err := db.QueryRow(`SELECT COUNT(*) FROM system_functions WHERE url_route_endpoint = '/shared'`).Scan(&rowCount); err != nil {
			t.Fatal(err)
		}
		if err := db.QueryRow(`
			SELECT COUNT(*) FROM system_functions
			 WHERE name IN ('oldpkg.FirstHandler', 'oldpkg.SecondHandler')
		`).Scan(&unchangedOldRows); err != nil {
			t.Fatal(err)
		}
		if rowCount != 3 || unchangedOldRows != 2 || newID <= 0 {
			t.Fatalf("ambiguous registration rows=%d old=%d new id=%d, want 3/2/positive", rowCount, unchangedOldRows, newID)
		}
		for _, expected := range []string{"/shared", "ambiguous non-UI rows", "oldpkg.FirstHandler", "oldpkg.SecondHandler"} {
			if !strings.Contains(logs.String(), expected) {
				t.Fatalf("ambiguity log %q does not contain %q", logs.String(), expected)
			}
		}
	})

	t.Run("handler claimed in this startup is never adopted", func(t *testing.T) {
		resetRouteIdentityFixture(t, db)
		logs.Reset()
		if _, err := db.Exec(`
			INSERT INTO system_functions
				(id, name, "package", disabled, specific_table_related, url_route_endpoint, ui_only)
			VALUES (52, 'oldpkg.LiveHandler', 'oldpkg', false, false, '/claimed', false);
			INSERT INTO system_group_table_func_rights (function_id) VALUES (52);
		`); err != nil {
			t.Fatal(err)
		}

		rd := RouteDefinition{UrlPattern: "/claimed", HandlerName: "newpkg.OtherHandler"}
		newID := registerMissingRouteForTest(t, db, rd, map[string]bool{
			rd.HandlerName:       true,
			"oldpkg.LiveHandler": true,
		})
		if newID == 52 {
			t.Fatal("new handler stole the live handler's row")
		}
		var oldName string
		var oldGrants int
		if err := db.QueryRow(`SELECT name FROM system_functions WHERE id = 52`).Scan(&oldName); err != nil {
			t.Fatal(err)
		}
		if err := db.QueryRow(`SELECT COUNT(*) FROM system_group_table_func_rights WHERE function_id = 52`).Scan(&oldGrants); err != nil {
			t.Fatal(err)
		}
		if oldName != "oldpkg.LiveHandler" || oldGrants != 1 {
			t.Fatalf("claimed row changed to %q with %d grants", oldName, oldGrants)
		}
		if !strings.Contains(logs.String(), "still claimed by a handler registered in this startup") {
			t.Fatalf("claimed-row log did not explain the refusal: %q", logs.String())
		}
	})

	t.Run("disabled row is not treated as a rename source", func(t *testing.T) {
		resetRouteIdentityFixture(t, db)
		logs.Reset()
		if _, err := db.Exec(`
			INSERT INTO system_functions
				(id, name, "package", disabled, specific_table_related, url_route_endpoint, ui_only)
			VALUES (57, 'oldpkg.DisabledHandler', 'oldpkg', true, false, '/disabled', false)
		`); err != nil {
			t.Fatal(err)
		}

		rd := RouteDefinition{UrlPattern: "/disabled", HandlerName: "newpkg.ReplacementHandler"}
		id := registerMissingRouteForTest(t, db, rd, map[string]bool{rd.HandlerName: true})
		if id == 57 {
			t.Fatal("new handler adopted a row that startup was not about to disable")
		}
		var oldName string
		if err := db.QueryRow(`SELECT name FROM system_functions WHERE id = 57`).Scan(&oldName); err != nil {
			t.Fatal(err)
		}
		if oldName != "oldpkg.DisabledHandler" {
			t.Fatalf("disabled row changed to %q", oldName)
		}
		if !strings.Contains(logs.String(), "not active (disabled is true or unset)") {
			t.Fatalf("disabled-row log did not explain the refusal: %q", logs.String())
		}
	})

	t.Run("genuinely new address inserts", func(t *testing.T) {
		resetRouteIdentityFixture(t, db)
		logs.Reset()
		rd := RouteDefinition{UrlPattern: "/brand-new", HandlerName: "newpkg.BrandNewHandler"}
		id := registerMissingRouteForTest(t, db, rd, map[string]bool{rd.HandlerName: true})

		var name, endpoint string
		var disabled, uiOnly bool
		if err := db.QueryRow(`
			SELECT name, url_route_endpoint, disabled, ui_only
			  FROM system_functions
			 WHERE id = $1
		`, id).Scan(&name, &endpoint, &disabled, &uiOnly); err != nil {
			t.Fatal(err)
		}
		if name != rd.HandlerName || endpoint != rd.UrlPattern || disabled || uiOnly {
			t.Fatalf("new route row = %q/%q disabled=%v ui-only=%v", name, endpoint, disabled, uiOnly)
		}
	})

	t.Run("frontend-only row is untouched", func(t *testing.T) {
		resetRouteIdentityFixture(t, db)
		logs.Reset()
		if _, err := db.Exec(`
			INSERT INTO system_functions
				(id, name, "package", disabled, specific_table_related, url_route_endpoint, ui_only)
			VALUES (63, 'ui.admin.example', 'frontend', false, false, '/ui/admin/example', true)
		`); err != nil {
			t.Fatal(err)
		}

		rd := RouteDefinition{UrlPattern: "/ui/admin/example", HandlerName: "newpkg.ExampleHandler"}
		id := registerMissingRouteForTest(t, db, rd, map[string]bool{rd.HandlerName: true})
		if id == 63 {
			t.Fatal("backend handler adopted a frontend-only permission row")
		}
		var uiName string
		var uiOnly bool
		if err := db.QueryRow(`SELECT name, ui_only FROM system_functions WHERE id = 63`).Scan(&uiName, &uiOnly); err != nil {
			t.Fatal(err)
		}
		if uiName != "ui.admin.example" || !uiOnly {
			t.Fatalf("frontend-only row changed to %q ui-only=%v", uiName, uiOnly)
		}
	})
}
