// workline_observatory_copy.js
// Provides translated copy for the workline list, actions and shared detail modal.
// Connects the application language preference with the Observatory surfaces.
// Keeps supported language paths together when interactions move between surfaces.

import { getLanguageWithBrowserFallback } from '../state_stores/lang_preference_reader.js';
const COPY = {
    en: { title: 'Workline observatory', subtitle: 'Select one or more worklines to change their state.', refresh: 'Refresh', now: 'NOW', noGoal: 'No release goal selected', goal: 'Selected release goal', releaseTarget: 'Release target', noReport: 'No canonical report yet.', reportHistory: 'Earlier reports and phases', reportHistoryLoading: 'Loading report history…', reportHistoryUnavailable: 'Report history is unavailable.', context: 'Context', plain: 'Plain language', technical: 'Technical', next: 'Next step', git: 'Scoped Git snapshot', tickets: 'Tickets', contract: 'Release contract', unclassified: 'Unclassified', save: 'Save classification', phase: 'Phase', loading: 'Loading…', unavailable: 'Observatory unavailable.', locked: 'Locked', draft: 'Draft', newGoal: 'Start next release goal', goalKey: 'Release identity', goalRevision: 'Goal revision', goalTitle: 'Release name', goalOutcome: 'Target outcome', createGoal: 'Create and select goal', lockGoal: 'Lock release goal', mustComplete: 'Must complete', mustRemainIncomplete: 'Must remain incomplete', mustBeInPhase: 'Must be in phase', mustNotStart: 'Must not start', outsideRelease: 'Outside release' },
    fi: { title: 'Työlinjojen tilannekuva', subtitle: 'Valitse yksi tai useampi työlinja muuttaaksesi niiden tilaa.', refresh: 'Päivitä', now: 'NYT', noGoal: 'Julkaisutavoitetta ei ole valittu', goal: 'Valittu julkaisutavoite', releaseTarget: 'Julkaisutavoite', noReport: 'Kanonista raporttia ei vielä ole.', reportHistory: 'Aiemmat raportit ja vaiheet', reportHistoryLoading: 'Raporttihistoriaa ladataan…', reportHistoryUnavailable: 'Raporttihistoriaa ei saatu ladattua.', context: 'Konteksti', plain: 'Selkokielellä', technical: 'Teknisesti', next: 'Seuraava askel', git: 'Rajattu Git-tilanne', tickets: 'Tiketit', contract: 'Julkaisusopimus', unclassified: 'Luokittelematon', save: 'Tallenna luokitus', phase: 'Vaihe', loading: 'Ladataan…', unavailable: 'Tilannekuvaa ei saatu ladattua.', locked: 'Lukittu', draft: 'Luonnos', newGoal: 'Aloita seuraava julkaisutavoite', goalKey: 'Julkaisun tunniste', goalRevision: 'Tavoitteen versio', goalTitle: 'Julkaisun nimi', goalOutcome: 'Tavoiteltu lopputulos', createGoal: 'Luo ja valitse tavoite', lockGoal: 'Lukitse julkaisutavoite', mustComplete: 'Valmistuttava', mustRemainIncomplete: 'Jätettävä keskeneräiseksi', mustBeInPhase: 'Oltava vaiheessa', mustNotStart: 'Ei aloiteta', outsideRelease: 'Julkaisun ulkopuolella' },
    ch: { title: '工作线总览', subtitle: '选择一条或多条工作线以更改状态。', refresh: '刷新', now: '现在', noGoal: '未选择发布目标', goal: '所选发布目标', releaseTarget: '发布目标', noReport: '尚无规范报告。', reportHistory: '过往报告和阶段', reportHistoryLoading: '正在加载报告历史…', reportHistoryUnavailable: '无法加载报告历史。', context: '背景', plain: '简明说明', technical: '技术说明', next: '下一步', git: '限定 Git 快照', tickets: '工单', contract: '发布契约', unclassified: '未分类', save: '保存分类', phase: '阶段', loading: '正在加载…', unavailable: '无法加载总览。', locked: '已锁定', draft: '草稿', newGoal: '开始下一个发布目标', goalKey: '发布标识', goalRevision: '目标修订', goalTitle: '发布名称', goalOutcome: '目标结果', createGoal: '创建并选择目标', lockGoal: '锁定发布目标', mustComplete: '必须完成', mustRemainIncomplete: '必须保持未完成', mustBeInPhase: '必须处于阶段', mustNotStart: '不得开始', outsideRelease: '发布范围外' },
    yue: { title: '工作線總覽', subtitle: '揀一條或多條工作線去更改狀態。', refresh: '重新整理', now: '而家', noGoal: '未揀發佈目標', goal: '已選發佈目標', releaseTarget: '發佈目標', noReport: '未有正式報告。', reportHistory: '過往報告同階段', reportHistoryLoading: '載入緊報告記錄…', reportHistoryUnavailable: '未能載入報告記錄。', context: '背景', plain: '簡單說明', technical: '技術說明', next: '下一步', git: '限定 Git 快照', tickets: '工作單', contract: '發佈契約', unclassified: '未分類', save: '儲存分類', phase: '階段', loading: '載入中…', unavailable: '未能載入總覽。', locked: '已鎖定', draft: '草稿', newGoal: '開始下一個發佈目標', goalKey: '發佈識別', goalRevision: '目標修訂', goalTitle: '發佈名稱', goalOutcome: '目標結果', createGoal: '建立並揀選目標', lockGoal: '鎖定發佈目標', mustComplete: '必須完成', mustRemainIncomplete: '必須保持未完成', mustBeInPhase: '必須處於階段', mustNotStart: '唔可以開始', outsideRelease: '發佈範圍外' },
};

const ACTION_COPY = {
    en: { selected: '{count} selected', selectAll: 'Select all', deselectAll: 'Deselect all', selectRows: 'Select one or more worklines to change their state.', activate: 'Activate', pause: 'Pause', markDone: 'Mark done', discard: 'Discard', activeState: 'Active', pausedState: 'Paused', closedState: 'Done', archivedState: 'Discarded', chooseTarget: 'Select one or more worklines to move them to {state}.', alreadyTarget: 'All selected worklines are already {state}.', alreadyTargetOne: '“{title}” is already {state}.', moveOne: 'Move “{title}” to {state}.', moveMany: 'Move all {count} selected worklines to {state}.', moveMixed: 'Move all {count} selected worklines to {state}; {sameCount} already have that state.', confirmOne: 'Change “{title}” to {state}?', confirmMany: 'Change all {count} selected worklines to {state}?', confirmMixed: 'Change all {count} selected worklines to {state}? {sameCount} already have that state.', changed: 'Changed {count} workline(s) to {state}.', status: 'Lifecycle state', lastStatus: 'Latest state decision', reconciliation: 'Waiting for AI synchronization', sourceObservatory: 'Owner in Observatory', sourceAgentTools: 'Agent/API', sourceReport: 'Canonical report synchronization', sourceCreation: 'Workline creation', sourceLegacy: 'Earlier state', unknownActor: 'Unknown user', selectionLabel: 'Select {title}' },
    fi: { selected: '{count} valittu', selectAll: 'Valitse kaikki', deselectAll: 'Poista kaikki valinnat', selectRows: 'Valitse yksi tai useampi työlinja muuttaaksesi niiden tilaa.', activate: 'Aktivoi', pause: 'Tauota', markDone: 'Merkitse valmiiksi', discard: 'Hylkää', activeState: 'Aktiivinen', pausedState: 'Tauolla', closedState: 'Valmis', archivedState: 'Hylätty', chooseTarget: 'Valitse yksi tai useampi työlinja siirtääksesi ne tilaan {state}.', alreadyTarget: 'Kaikki valitut työlinjat ovat jo tilassa {state}.', alreadyTargetOne: '“{title}” on jo tilassa {state}.', moveOne: 'Siirrä “{title}” tilaan {state}.', moveMany: 'Siirrä kaikki {count} valittua työlinjaa tilaan {state}.', moveMixed: 'Siirrä kaikki {count} valittua työlinjaa tilaan {state}; {sameCount} on jo siinä tilassa.', confirmOne: 'Muutetaanko “{title}” tilaan {state}?', confirmMany: 'Muutetaanko kaikki {count} valittua työlinjaa tilaan {state}?', confirmMixed: 'Muutetaanko kaikki {count} valittua työlinjaa tilaan {state}? {sameCount} on jo siinä tilassa.', changed: 'Muutettiin {count} työlinjan tilaksi {state}.', status: 'Työlinjan tila', lastStatus: 'Viimeisin tilapäätös', reconciliation: 'Odottaa AI-synkronointia', sourceObservatory: 'Omistaja Observatoryssa', sourceAgentTools: 'Agentti/API', sourceReport: 'Kanonisen raportin synkronointi', sourceCreation: 'Työlinjan luonti', sourceLegacy: 'Aiempi tila', unknownActor: 'Tuntematon käyttäjä', selectionLabel: 'Valitse {title}' },
    ch: { selected: '已选择 {count} 项', selectAll: '全选', deselectAll: '取消全选', selectRows: '选择一条或多条工作线以更改状态。', activate: '激活', pause: '暂停', markDone: '标记完成', discard: '放弃', activeState: '活动', pausedState: '已暂停', closedState: '已完成', archivedState: '已放弃', chooseTarget: '选择一条或多条工作线以移至“{state}”。', alreadyTarget: '所有所选工作线已处于“{state}”。', alreadyTargetOne: '“{title}”已处于“{state}”。', moveOne: '将“{title}”移至“{state}”。', moveMany: '将 {changeCount} 条工作线移至“{state}”。', moveMixed: '将所选 {count} 条中的 {changeCount} 条移至“{state}”；另有 {sameCount} 条已处于该状态。', confirmOne: '将“{title}”更改为“{state}”吗？', confirmMany: '将 {changeCount} 条工作线更改为“{state}”吗？', confirmMixed: '将所选 {count} 条中的 {changeCount} 条更改为“{state}”吗？', changed: '已将 {count} 条工作线更改为“{state}”。', status: '工作线状态', lastStatus: '最近状态决定', reconciliation: '等待 AI 同步', sourceObservatory: '所有者在总览中操作', sourceAgentTools: '代理/API', sourceReport: '规范报告同步', sourceCreation: '创建工作线', sourceLegacy: '较早状态', unknownActor: '未知用户', selectionLabel: '选择 {title}' },
    yue: { selected: '已揀 {count} 項', selectAll: '全揀', deselectAll: '取消全揀', selectRows: '揀一條或多條工作線去更改狀態。', activate: '啟用', pause: '暫停', markDone: '標記完成', discard: '放棄', activeState: '進行中', pausedState: '已暫停', closedState: '已完成', archivedState: '已放棄', chooseTarget: '揀一條或多條工作線移去「{state}」。', alreadyTarget: '所有已揀工作線已經係「{state}」。', alreadyTargetOne: '「{title}」已經係「{state}」。', moveOne: '將「{title}」移去「{state}」。', moveMany: '將 {changeCount} 條工作線移去「{state}」。', moveMixed: '將已揀 {count} 條入面嘅 {changeCount} 條移去「{state}」；另外 {sameCount} 條已經係呢個狀態。', confirmOne: '將「{title}」改做「{state}」？', confirmMany: '將 {changeCount} 條工作線改做「{state}」？', confirmMixed: '將已揀 {count} 條入面嘅 {changeCount} 條改做「{state}」？', changed: '已將 {count} 條工作線改做「{state}」。', status: '工作線狀態', lastStatus: '最近狀態決定', reconciliation: '等緊 AI 同步', sourceObservatory: '擁有人喺總覽操作', sourceAgentTools: '代理/API', sourceReport: '正式報告同步', sourceCreation: '建立工作線', sourceLegacy: '較早狀態', unknownActor: '未知用戶', selectionLabel: '揀 {title}' },
};


const DETAIL_COPY = {
    en: { priority: 'Priority', low: 'Low', normal: 'Normal', high: 'High', critical: 'Critical', rowActions: 'Actions for {title}', selectAllVisible: 'Select all visible', visible: '{count} visible', conflict: 'This workline changed. Review the refreshed state and try again.', priorityChanged: 'Priority changed to {priority}.', reportedPhase: 'Latest reported phase' },
    fi: { priority: 'Prioriteetti', low: 'Matala', normal: 'Normaali', high: 'Korkea', critical: 'Kriittinen', rowActions: 'Työlinjan {title} toiminnot', selectAllVisible: 'Valitse kaikki näkyvät', visible: '{count} näkyvissä', conflict: 'Työlinja muuttui. Tarkista päivitetty tila ja yritä uudelleen.', priorityChanged: 'Prioriteetiksi muutettiin {priority}.', reportedPhase: 'Viimeisin raportoitu vaihe' },
    ch: { priority: '优先级', low: '低', normal: '普通', high: '高', critical: '紧急', rowActions: '{title} 的操作', selectAllVisible: '选择所有可见项', visible: '{count} 项可见', conflict: '此工作线已更改。请检查刷新后的状态并重试。', priorityChanged: '优先级已更改为{priority}。', reportedPhase: '最近报告的阶段' },
    yue: { priority: '優先次序', low: '低', normal: '一般', high: '高', critical: '緊急', rowActions: '「{title}」嘅操作', selectAllVisible: '揀全部可見項目', visible: '{count} 項可見', conflict: '呢條工作線已經改咗。請檢查更新後嘅狀態再試。', priorityChanged: '優先次序已改做{priority}。', reportedPhase: '最近報告嘅階段' },
};

export const DEFAULT_COPY = { ...COPY.en, ...ACTION_COPY.en, ...DETAIL_COPY.en };

export function resolveCopy() {
    const language = String(getLanguageWithBrowserFallback() || 'en').toLowerCase();
    if (language.startsWith('fi')) return { ...COPY.fi, ...ACTION_COPY.fi, ...DETAIL_COPY.fi };
    if (language === 'yue' || language === 'zh-tw' || language === 'zh-hk') return { ...COPY.yue, ...ACTION_COPY.yue, ...DETAIL_COPY.yue };
    if (language === 'ch' || language.startsWith('zh')) return { ...COPY.ch, ...ACTION_COPY.ch, ...DETAIL_COPY.ch };
    return DEFAULT_COPY;
}
