-- Filterest public bootstrap: the established four-table mock workspace.
-- These names intentionally match the long-lived synthetic demo datasets in
-- the long-lived private source workspace. They remain synthetic public fixtures, separate from private
-- production service and development-task datasets.

CREATE TABLE IF NOT EXISTS public.palvelukatalogi (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer,
    cached_username character varying,
    palvelu text NOT NULL,
    kuvaus text NOT NULL,
    omistava_tiimi text NOT NULL,
    palvelutaso text NOT NULL,
    tila text NOT NULL,
    vastuuhenkilo text NOT NULL,
    cached_image text,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.riskienhallinta (
    vaikutus text NOT NULL,
    riskitaso text NOT NULL,
    kuvaus text NOT NULL,
    tila text NOT NULL,
    riski text NOT NULL,
    omistava_tiimi text NOT NULL,
    todennakoisyys text NOT NULL,
    alentamistoimet text NOT NULL,
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer,
    cached_username character varying,
    palvelu_id integer REFERENCES public.palvelukatalogi(id) ON UPDATE CASCADE ON DELETE SET NULL,
    cached_image text,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.dokumentaatio (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer,
    cached_username character varying,
    palvelu_id integer REFERENCES public.palvelukatalogi(id) ON UPDATE CASCADE ON DELETE SET NULL,
    otsikko text NOT NULL,
    kohdetiimi text NOT NULL,
    ohje text NOT NULL,
    paivitetty date DEFAULT CURRENT_DATE,
    voimassaolo text NOT NULL,
    kuva text,
    cached_image text,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.tiketit (
    otsikko text NOT NULL,
    vastuutiimi text NOT NULL,
    maarapaiva date,
    tila text NOT NULL,
    riski_id integer REFERENCES public.riskienhallinta(id) ON UPDATE CASCADE ON DELETE SET NULL,
    prioriteetti text NOT NULL,
    pyyntotyyppi text NOT NULL,
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer,
    cached_username character varying,
    kuvaus text NOT NULL,
    palvelu_id integer REFERENCES public.palvelukatalogi(id) ON UPDATE CASCADE ON DELETE SET NULL,
    dokumentaatio_id integer REFERENCES public.dokumentaatio(id) ON UPDATE CASCADE ON DELETE SET NULL,
    kuva text,
    cached_image text,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now()
);

-- Each example dataset uses the same shared asset child-table contract as
-- datasets configured through the Asset linking admin tool. Keeping the four
-- tables explicit makes image uploads available immediately after First Run.
CREATE TABLE IF NOT EXISTS public.palvelukatalogi_assets (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    palvelukatalogi_id integer NOT NULL REFERENCES public.palvelukatalogi(id) ON DELETE CASCADE,
    asset_kind text NOT NULL DEFAULT 'image',
    filename text,
    original_name text,
    mime_type text,
    size_bytes bigint,
    title text,
    description text,
    sort_order integer NOT NULL DEFAULT 0,
    is_primary boolean NOT NULL DEFAULT false,
    metadata_json jsonb,
    created timestamp with time zone DEFAULT now(),
    updated timestamp with time zone DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_palvelukatalogi_assets_parent
    ON public.palvelukatalogi_assets (palvelukatalogi_id);
CREATE INDEX IF NOT EXISTS idx_palvelukatalogi_assets_kind
    ON public.palvelukatalogi_assets (asset_kind);
CREATE INDEX IF NOT EXISTS idx_palvelukatalogi_assets_primary
    ON public.palvelukatalogi_assets (palvelukatalogi_id, is_primary, sort_order);

CREATE TABLE IF NOT EXISTS public.riskienhallinta_assets (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    riskienhallinta_id integer NOT NULL REFERENCES public.riskienhallinta(id) ON DELETE CASCADE,
    asset_kind text NOT NULL DEFAULT 'image',
    filename text,
    original_name text,
    mime_type text,
    size_bytes bigint,
    title text,
    description text,
    sort_order integer NOT NULL DEFAULT 0,
    is_primary boolean NOT NULL DEFAULT false,
    metadata_json jsonb,
    created timestamp with time zone DEFAULT now(),
    updated timestamp with time zone DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_riskienhallinta_assets_parent
    ON public.riskienhallinta_assets (riskienhallinta_id);
CREATE INDEX IF NOT EXISTS idx_riskienhallinta_assets_kind
    ON public.riskienhallinta_assets (asset_kind);
CREATE INDEX IF NOT EXISTS idx_riskienhallinta_assets_primary
    ON public.riskienhallinta_assets (riskienhallinta_id, is_primary, sort_order);

CREATE TABLE IF NOT EXISTS public.dokumentaatio_assets (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dokumentaatio_id integer NOT NULL REFERENCES public.dokumentaatio(id) ON DELETE CASCADE,
    asset_kind text NOT NULL DEFAULT 'image',
    filename text,
    original_name text,
    mime_type text,
    size_bytes bigint,
    title text,
    description text,
    sort_order integer NOT NULL DEFAULT 0,
    is_primary boolean NOT NULL DEFAULT false,
    metadata_json jsonb,
    created timestamp with time zone DEFAULT now(),
    updated timestamp with time zone DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_dokumentaatio_assets_parent
    ON public.dokumentaatio_assets (dokumentaatio_id);
CREATE INDEX IF NOT EXISTS idx_dokumentaatio_assets_kind
    ON public.dokumentaatio_assets (asset_kind);
CREATE INDEX IF NOT EXISTS idx_dokumentaatio_assets_primary
    ON public.dokumentaatio_assets (dokumentaatio_id, is_primary, sort_order);

CREATE TABLE IF NOT EXISTS public.tiketit_assets (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tiketit_id integer NOT NULL REFERENCES public.tiketit(id) ON DELETE CASCADE,
    asset_kind text NOT NULL DEFAULT 'image',
    filename text,
    original_name text,
    mime_type text,
    size_bytes bigint,
    title text,
    description text,
    sort_order integer NOT NULL DEFAULT 0,
    is_primary boolean NOT NULL DEFAULT false,
    metadata_json jsonb,
    created timestamp with time zone DEFAULT now(),
    updated timestamp with time zone DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_tiketit_assets_parent
    ON public.tiketit_assets (tiketit_id);
CREATE INDEX IF NOT EXISTS idx_tiketit_assets_kind
    ON public.tiketit_assets (asset_kind);
CREATE INDEX IF NOT EXISTS idx_tiketit_assets_primary
    ON public.tiketit_assets (tiketit_id, is_primary, sort_order);

CREATE OR REPLACE FUNCTION public.set_domain_workspace_updated_timestamp()
RETURNS trigger AS $$
BEGIN
    NEW.updated = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_palvelukatalogi_updated ON public.palvelukatalogi;
CREATE TRIGGER set_palvelukatalogi_updated
BEFORE UPDATE ON public.palvelukatalogi
FOR EACH ROW EXECUTE FUNCTION public.set_domain_workspace_updated_timestamp();

DROP TRIGGER IF EXISTS set_riskienhallinta_updated ON public.riskienhallinta;
CREATE TRIGGER set_riskienhallinta_updated
BEFORE UPDATE ON public.riskienhallinta
FOR EACH ROW EXECUTE FUNCTION public.set_domain_workspace_updated_timestamp();

DROP TRIGGER IF EXISTS set_dokumentaatio_updated ON public.dokumentaatio;
CREATE TRIGGER set_dokumentaatio_updated
BEFORE UPDATE ON public.dokumentaatio
FOR EACH ROW EXECUTE FUNCTION public.set_domain_workspace_updated_timestamp();

DROP TRIGGER IF EXISTS set_tiketit_updated ON public.tiketit;
CREATE TRIGGER set_tiketit_updated
BEFORE UPDATE ON public.tiketit
FOR EACH ROW EXECUTE FUNCTION public.set_domain_workspace_updated_timestamp();

CREATE TABLE IF NOT EXISTS public.palvelukatalogi_riskienhallinta_relation (
    palvelu_id integer NOT NULL REFERENCES public.palvelukatalogi(id) ON DELETE CASCADE,
    riski_id integer NOT NULL REFERENCES public.riskienhallinta(id) ON DELETE CASCADE,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (palvelu_id, riski_id)
);

CREATE TABLE IF NOT EXISTS public.palvelukatalogi_dokumentaatio_relation (
    palvelu_id integer NOT NULL REFERENCES public.palvelukatalogi(id) ON DELETE CASCADE,
    dokumentaatio_id integer NOT NULL REFERENCES public.dokumentaatio(id) ON DELETE CASCADE,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (palvelu_id, dokumentaatio_id)
);

CREATE TABLE IF NOT EXISTS public.palvelukatalogi_tiketit_relation (
    palvelu_id integer NOT NULL REFERENCES public.palvelukatalogi(id) ON DELETE CASCADE,
    tiketti_id integer NOT NULL REFERENCES public.tiketit(id) ON DELETE CASCADE,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (palvelu_id, tiketti_id)
);

CREATE TABLE IF NOT EXISTS public.riskienhallinta_dokumentaatio_relation (
    riski_id integer NOT NULL REFERENCES public.riskienhallinta(id) ON DELETE CASCADE,
    dokumentaatio_id integer NOT NULL REFERENCES public.dokumentaatio(id) ON DELETE CASCADE,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (riski_id, dokumentaatio_id)
);

CREATE TABLE IF NOT EXISTS public.riskienhallinta_tiketit_relation (
    riski_id integer NOT NULL REFERENCES public.riskienhallinta(id) ON DELETE CASCADE,
    tiketti_id integer NOT NULL REFERENCES public.tiketit(id) ON DELETE CASCADE,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (riski_id, tiketti_id)
);

CREATE TABLE IF NOT EXISTS public.dokumentaatio_tiketit_relation (
    dokumentaatio_id integer NOT NULL REFERENCES public.dokumentaatio(id) ON DELETE CASCADE,
    tiketti_id integer NOT NULL REFERENCES public.tiketit(id) ON DELETE CASCADE,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (dokumentaatio_id, tiketti_id)
);

CREATE INDEX IF NOT EXISTS idx_palvelukatalogi_riskienhallinta_relation_riski_id
    ON public.palvelukatalogi_riskienhallinta_relation (riski_id);
CREATE INDEX IF NOT EXISTS idx_palvelukatalogi_dokumentaatio_relation_dokumentaatio_id
    ON public.palvelukatalogi_dokumentaatio_relation (dokumentaatio_id);
CREATE INDEX IF NOT EXISTS idx_palvelukatalogi_tiketit_relation_tiketti_id
    ON public.palvelukatalogi_tiketit_relation (tiketti_id);
CREATE INDEX IF NOT EXISTS idx_riskienhallinta_dokumentaatio_relation_dokumentaatio_id
    ON public.riskienhallinta_dokumentaatio_relation (dokumentaatio_id);
CREATE INDEX IF NOT EXISTS idx_riskienhallinta_tiketit_relation_tiketti_id
    ON public.riskienhallinta_tiketit_relation (tiketti_id);
CREATE INDEX IF NOT EXISTS idx_dokumentaatio_tiketit_relation_tiketti_id
    ON public.dokumentaatio_tiketit_relation (tiketti_id);

DROP TRIGGER IF EXISTS set_palvelukatalogi_riskienhallinta_relation_updated ON public.palvelukatalogi_riskienhallinta_relation;
CREATE TRIGGER set_palvelukatalogi_riskienhallinta_relation_updated
BEFORE UPDATE ON public.palvelukatalogi_riskienhallinta_relation
FOR EACH ROW EXECUTE FUNCTION public.set_domain_workspace_updated_timestamp();

DROP TRIGGER IF EXISTS set_palvelukatalogi_dokumentaatio_relation_updated ON public.palvelukatalogi_dokumentaatio_relation;
CREATE TRIGGER set_palvelukatalogi_dokumentaatio_relation_updated
BEFORE UPDATE ON public.palvelukatalogi_dokumentaatio_relation
FOR EACH ROW EXECUTE FUNCTION public.set_domain_workspace_updated_timestamp();

DROP TRIGGER IF EXISTS set_palvelukatalogi_tiketit_relation_updated ON public.palvelukatalogi_tiketit_relation;
CREATE TRIGGER set_palvelukatalogi_tiketit_relation_updated
BEFORE UPDATE ON public.palvelukatalogi_tiketit_relation
FOR EACH ROW EXECUTE FUNCTION public.set_domain_workspace_updated_timestamp();

DROP TRIGGER IF EXISTS set_riskienhallinta_dokumentaatio_relation_updated ON public.riskienhallinta_dokumentaatio_relation;
CREATE TRIGGER set_riskienhallinta_dokumentaatio_relation_updated
BEFORE UPDATE ON public.riskienhallinta_dokumentaatio_relation
FOR EACH ROW EXECUTE FUNCTION public.set_domain_workspace_updated_timestamp();

DROP TRIGGER IF EXISTS set_riskienhallinta_tiketit_relation_updated ON public.riskienhallinta_tiketit_relation;
CREATE TRIGGER set_riskienhallinta_tiketit_relation_updated
BEFORE UPDATE ON public.riskienhallinta_tiketit_relation
FOR EACH ROW EXECUTE FUNCTION public.set_domain_workspace_updated_timestamp();

DROP TRIGGER IF EXISTS set_dokumentaatio_tiketit_relation_updated ON public.dokumentaatio_tiketit_relation;
CREATE TRIGGER set_dokumentaatio_tiketit_relation_updated
BEFORE UPDATE ON public.dokumentaatio_tiketit_relation
FOR EACH ROW EXECUTE FUNCTION public.set_domain_workspace_updated_timestamp();
