-- Filterest public bootstrap: menus and field labels for the established mock
-- workspace. Cantonese is stored in the first-class yue language column.

INSERT INTO public.system_lang_keys (lang_key, fi, en, ch, yue, creation_spec) VALUES
  ('palvelukatalogi', 'Palvelut', 'Services', '服务', '服務', 'public fixture seed'),
  ('palvelukatalogi_front_page', 'Palvelut', 'Services', '服务', '服務', 'public fixture seed'),
  ('search_slogan_palvelukatalogi', 'Löydä palveluja nimen, omistajan tai palvelutason perusteella.', 'Find services by name, owner, or service level.', '按名称、负责人或服务级别查找服务。', '按名稱、負責人或者服務級別搵服務。', 'public fixture seed'),
  ('search_for_palvelukatalogi', 'Hae palveluja nimellä, omistajalla tai palvelutasolla', 'Search services by name, owner, or service level', '按名称、负责人或服务级别搜索服务', '按名稱、負責人或者服務級別搜尋服務', 'public fixture seed'),
  ('add_row_palvelukatalogi', 'Lisää palvelu', 'Add service', '添加服务', '新增服務', 'public fixture seed'),

  ('tiketit', 'Tiketit', 'Tickets', '工单', '工單', 'public fixture seed'),
  ('tiketit_front_page', 'Tiketit', 'Tickets', '工单', '工單', 'public fixture seed'),
  ('search_slogan_tiketit', 'Löydä tikettejä otsikon, tilan, prioriteetin tai vastuutiimin perusteella.', 'Find tickets by title, status, priority, or responsible team.', '按标题、状态、优先级或负责团队查找工单。', '按標題、狀態、優先次序或者負責團隊搵工單。', 'public fixture seed'),
  ('search_for_tiketit', 'Hae tikettejä otsikolla, tilalla, prioriteetilla tai vastuutiimillä', 'Search tickets by title, status, priority, or responsible team', '按标题、状态、优先级或负责团队搜索工单', '按標題、狀態、優先次序或者負責團隊搜尋工單', 'public fixture seed'),
  ('add_row_tiketit', 'Lisää tiketti', 'Add ticket', '添加工单', '新增工單', 'public fixture seed'),

  ('riskienhallinta', 'Riskit', 'Risks', '风险', '風險', 'public fixture seed'),
  ('riskienhallinta_front_page', 'Riskit', 'Risks', '风险', '風險', 'public fixture seed'),
  ('search_slogan_riskienhallinta', 'Löydä riskejä vaikutuksen, riskitason tai vastuutiimin perusteella.', 'Find risks by impact, risk level, or responsible team.', '按影响、风险等级或负责团队查找风险。', '按影響、風險等級或者負責團隊搵風險。', 'public fixture seed'),
  ('search_for_riskienhallinta', 'Hae riskejä vaikutuksella, riskitasolla tai vastuutiimillä', 'Search risks by impact, risk level, or responsible team', '按影响、风险等级或负责团队搜索风险', '按影響、風險等級或者負責團隊搜尋風險', 'public fixture seed'),
  ('add_row_riskienhallinta', 'Lisää riski', 'Add risk', '添加风险', '新增風險', 'public fixture seed'),

  ('dokumentaatio', 'Dokumentaatio', 'Documentation', '文档', '文件', 'public fixture seed'),
  ('dokumentaatio_front_page', 'Dokumentaatio', 'Documentation', '文档', '文件', 'public fixture seed'),
  ('search_slogan_dokumentaatio', 'Löydä ohjeita otsikon, kohdetiimin tai voimassaolon perusteella.', 'Find guidance by title, audience, or validity.', '按标题、目标团队或有效性查找文档。', '按標題、目標團隊或者有效性搵文件。', 'public fixture seed'),
  ('search_for_dokumentaatio', 'Hae ohjeita otsikolla, kohdetiimillä tai voimassaololla', 'Search guidance by title, audience, or validity', '按标题、目标团队或有效性搜索文档', '按標題、目標團隊或者有效性搜尋文件', 'public fixture seed'),
  ('add_row_dokumentaatio', 'Lisää dokumentti', 'Add document', '添加文档', '新增文件', 'public fixture seed'),

  -- Image-asset datasets use curated public labels instead of exposing their
  -- technical table names or generated "front page" search copy.
  ('palvelukatalogi_assets', 'Palvelukuvat', 'Service images', '服务图片', '服務圖片', 'public fixture seed'),
  ('palvelukatalogi_assets_front_page', 'Palvelukuvat', 'Service images', '服务图片', '服務圖片', 'public fixture seed'),
  ('search_slogan_palvelukatalogi_assets', 'Hallinnoi palveluihin liitettyjä kuvia ja niiden kuvauksia.', 'Manage images linked to services and their descriptions.', '管理与服务关联的图片及其说明。', '管理同服務相關嘅圖片同說明。', 'public fixture seed'),
  ('search_for_palvelukatalogi_assets', 'Hae palvelukuvia tiedostonimellä tai kuvauksella', 'Search service images by filename or description', '按文件名或说明搜索服务图片', '按檔案名稱或者說明搜尋服務圖片', 'public fixture seed'),

  ('riskienhallinta_assets', 'Riskikuvat', 'Risk images', '风险图片', '風險圖片', 'public fixture seed'),
  ('riskienhallinta_assets_front_page', 'Riskikuvat', 'Risk images', '风险图片', '風險圖片', 'public fixture seed'),
  ('search_slogan_riskienhallinta_assets', 'Hallinnoi riskejä, vaikutuksia ja hallintatoimia havainnollistavia kuvia.', 'Manage images that illustrate risks, impacts, and mitigating actions.', '管理用于说明风险、影响和应对措施的图片。', '管理用嚟說明風險、影響同應對措施嘅圖片。', 'public fixture seed'),
  ('search_for_riskienhallinta_assets', 'Hae riskikuvia tiedostonimellä tai kuvauksella', 'Search risk images by filename or description', '按文件名或说明搜索风险图片', '按檔案名稱或者說明搜尋風險圖片', 'public fixture seed'),

  ('dokumentaatio_assets', 'Dokumentaation kuvat', 'Documentation images', '文档图片', '文件圖片', 'public fixture seed'),
  ('dokumentaatio_assets_front_page', 'Dokumentaation kuvat', 'Documentation images', '文档图片', '文件圖片', 'public fixture seed'),
  ('search_slogan_dokumentaatio_assets', 'Hallinnoi ohjeissa ja dokumentaatiossa käytettäviä kuvia sekä niiden kuvauksia.', 'Manage images used in guidance and documentation, together with their descriptions.', '管理指南和文档中使用的图片及其说明。', '管理指南同文件使用嘅圖片同說明。', 'public fixture seed'),
  ('search_for_dokumentaatio_assets', 'Hae dokumentaation kuvia tiedostonimellä tai kuvauksella', 'Search documentation images by filename or description', '按文件名或说明搜索文档图片', '按檔案名稱或者說明搜尋文件圖片', 'public fixture seed'),

  ('tiketit_assets', 'Tikettien kuvat', 'Ticket images', '工单图片', '工單圖片', 'public fixture seed'),
  ('tiketit_assets_front_page', 'Tikettien kuvat', 'Ticket images', '工单图片', '工單圖片', 'public fixture seed'),
  ('search_slogan_tiketit_assets', 'Hallinnoi tiketteihin liitettyjä kuvakaappauksia, kuvia ja kuvauksia.', 'Manage screenshots, images, and descriptions linked to tickets.', '管理与工单关联的截图、图片和说明。', '管理同工單相關嘅螢幕截圖、圖片同說明。', 'public fixture seed'),
  ('search_for_tiketit_assets', 'Hae tikettien kuvia tiedostonimellä tai kuvauksella', 'Search ticket images by filename or description', '按文件名或说明搜索工单图片', '按檔案名稱或者說明搜尋工單圖片', 'public fixture seed'),

  ('palvelu', 'Palvelu', 'Service', '服务', '服務', 'public fixture seed'),
  ('kuvaus', 'Kuvaus', 'Description', '描述', '描述', 'public fixture seed'),
  ('omistava_tiimi', 'Omistava tiimi', 'Owning team', '负责团队', '負責團隊', 'public fixture seed'),
  ('palvelutaso', 'Palvelutaso', 'Service level', '服务级别', '服務級別', 'public fixture seed'),
  ('tila', 'Tila', 'Status', '状态', '狀態', 'public fixture seed'),
  ('vastuuhenkilo', 'Vastuuhenkilö', 'Owner', '负责人', '負責人', 'public fixture seed'),
  ('riski', 'Riski', 'Risk', '风险', '風險', 'public fixture seed'),
  ('vaikutus', 'Vaikutus', 'Impact', '影响', '影響', 'public fixture seed'),
  ('riskitaso', 'Riskitaso', 'Risk level', '风险级别', '風險級別', 'public fixture seed'),
  ('todennakoisyys', 'Todennäköisyys', 'Likelihood', '可能性', '可能性', 'public fixture seed'),
  ('alentamistoimet', 'Hallintatoimet', 'Mitigation', '缓解措施', '緩解措施', 'public fixture seed'),
  ('otsikko', 'Otsikko', 'Title', '标题', '標題', 'public fixture seed'),
  ('kohdetiimi', 'Kohdetiimi', 'Target team', '目标团队', '目標團隊', 'public fixture seed'),
  ('ohje', 'Ohje', 'Guidance', '指南', '指引', 'public fixture seed'),
  ('paivitetty', 'Katselmoitu', 'Reviewed', '审核日期', '審查日期', 'public fixture seed'),
  ('voimassaolo', 'Voimassaolo', 'Validity', '有效性', '有效性', 'public fixture seed'),
  ('vastuutiimi', 'Vastuutiimi', 'Responsible team', '负责团队', '負責團隊', 'public fixture seed'),
  ('maarapaiva', 'Määräpäivä', 'Due date', '截止日期', '截止日期', 'public fixture seed'),
  ('prioriteetti', 'Prioriteetti', 'Priority', '优先级', '優先次序', 'public fixture seed'),
  ('pyyntotyyppi', 'Pyyntötyyppi', 'Request type', '请求类型', '請求類型', 'public fixture seed'),
  ('cached_image', 'Kuva', 'Image', '图片', '圖片', 'public fixture seed'),
  ('cached_username', 'Käyttäjänimi', 'Username', '用户名', '用戶名稱', 'public fixture seed'),
  ('search_for_cached_username', 'Hae käyttäjänimellä', 'Search by username', '按用户名搜索', '按用戶名稱搜尋', 'public fixture seed'),
  ('sort_images_first', 'Kuvalliset ensin', 'Rows with images first', '有图片的行优先', '有圖片嘅資料列優先', 'public fixture seed'),

  -- Travel datasets keep exact bilingual navigation names before and after
  -- the planned app_ technical-prefix normalization. Other locales fall back
  -- to English until project-owned translations are authored and reviewed.
  ('travel_info', 'Matkainfo', 'Travel info', '', '', 'curated bilingual travel dataset label'),
  ('travel_info_front_page', 'Matkainfo', 'Travel information', '', '', 'curated bilingual travel dataset hero label'),
  ('app_travel_info', 'Matkainfo', 'Travel info', '', '', 'curated bilingual travel dataset label'),
  ('travel_deals', 'Matkatarjoukset', 'Travel deals', '', '', 'curated bilingual travel dataset label'),
  ('app_travel_deals', 'Matkatarjoukset', 'Travel deals', '', '', 'curated bilingual travel dataset label'),

  -- Calendar presentation controls are product-owned copy. They must be
  -- available before the view renders; the public runtime never calls AI to
  -- repair missing translations.
  ('calendar_month', 'Kuukausi', 'Month', '月', '月', 'public fixture seed'),
  ('calendar_week', 'Viikko', 'Week', '周', '週', 'public fixture seed'),
  ('calendar_day', 'Päivä', 'Day', '日', '日', 'public fixture seed'),
  ('calendar_agenda', 'Agenda', 'Agenda', '日程', '議程', 'public fixture seed'),
  ('calendar_today', 'Tänään', 'Today', '今天', '今日', 'public fixture seed'),
  ('calendar_no_events', 'Ei tapahtumia', 'No events', '没有事件', '冇活動', 'public fixture seed'),
  ('calendar_no_date_column', 'Kalenterille sopivaa päivämääräkenttää ei löytynyt', 'No calendar date column found', '未找到日历日期字段', '搵唔到日曆日期欄位', 'public fixture seed'),

  -- Shared navigation and tool labels rendered by the public application shell.
  ('account', 'Tili', 'Account', '账户', '帳戶', 'public fixture seed'),
  ('logout', 'Kirjaudu ulos', 'Logout', '退出登录', '登出', 'public fixture seed'),
  ('privacy_notice_login_acceptance', 'Kirjautuaksesi sinun on hyväksyttävä tietosuojaseloste.', 'To sign in, you must accept the privacy notice.', '登录前，您必须接受隐私声明。', '登入前，你必須接受私隱聲明。', 'Single linked sentence beside the sign-in privacy acceptance checkbox.'),
  ('privacy_notice_login_acceptance_prefix', 'Kirjautuaksesi sinun on hyväksyttävä ', 'To sign in, you must accept the ', '登录前，您必须接受', '登入前，你必須接受', 'Plain-text prefix before the linked privacy notice name; spacing is intentional for languages that use it.'),
  ('privacy_notice_login_acceptance_link', 'tietosuojaseloste', 'privacy notice', '隐私声明', '私隱聲明', 'Only the privacy notice name linked to the notice modal in the login acceptance sentence.'),
  ('privacy_notice_login_acceptance_suffix', '.', '.', '。', '。', 'Plain-text locale-specific sentence terminator after the linked privacy notice name.'),
  ('filter_mode_exact_value', 'Tarkka arvo', 'Exact value', '精确值', '精確值', 'Tooltip and accessible name for the filter mode that matches one exact value.'),
  ('filter_mode_range', 'Arvoväli', 'Range', '范围', '範圍', 'Tooltip and accessible name for the filter mode that matches a lower-to-upper range.'),
  ('filter_mode_condition_expression', 'Ehto tai lauseke', 'Condition or expression', '条件或表达式', '條件或運算式', 'Tooltip and accessible name for the filter mode that accepts a condition or expression.'),
  ('system_config', 'Järjestelmäasetukset', 'System configuration', '系统配置', '系統設定', 'public fixture seed'),
  ('users', 'Käyttäjät', 'Users', '用户', '用戶', 'public fixture seed'),
  ('system_users_front_page', 'Käyttäjät', 'Users', '用户', '用戶', 'public fixture seed'),
  ('search_slogan_system_users', 'Löydä käyttäjiä nimen, käyttäjätunnuksen tai käyttöoikeusryhmän perusteella.', 'Find users by name, username, or permission group.', '按姓名、用户名或权限组查找用户。', '按姓名、用戶名稱或者權限群組搵用戶。', 'public fixture seed'),
  ('search_for_system_users', 'Hae käyttäjiä nimellä, käyttäjätunnuksella tai käyttöoikeusryhmällä', 'Search users by name, username, or permission group', '按姓名、用户名或权限组搜索用户', '按姓名、用戶名稱或者權限群組搜尋用戶', 'public fixture seed'),
  ('admin_and_development_tools', 'Ylläpidon ja kehityksen työkalut', 'Admin and development tools', '管理和开发工具', '管理及開發工具', 'public fixture seed'),
  ('admin_tools', 'Ylläpidon työkalut', 'Admin tools', '管理工具', '管理工具', 'public fixture seed'),
  ('permissions', 'Käyttöoikeudet', 'Permissions', '权限', '權限', 'public fixture seed'),
  ('queen_chat', 'Queen-keskustelu', 'Queen chat', 'Queen 聊天', 'Queen 傾偈', 'public fixture seed'),
  ('table_tools', 'Taulutyökalut', 'Table tools', '表格工具', '資料表工具', 'public fixture seed'),
  ('create_table', 'Luo taulu', 'Create table', '创建表格', '建立資料表', 'public fixture seed'),
  ('foreign_keys', 'Vierasavaimet', 'Foreign keys', '外键', '外鍵', 'public fixture seed'),
  ('asset_linking', 'Assettien linkitys', 'Asset linking', '资源关联', '資產連結', 'public fixture seed'),
  ('card_visibility', 'Korttien näkyvyys', 'Card visibility', '卡片可见性', '卡片顯示設定', 'public fixture seed'),
  ('service_catalog_moderation', 'Palvelukatalogin moderointi', 'Service catalog moderation', '服务目录审核', '服務目錄審核', 'public fixture seed'),
  ('child_tab_config', 'Alivälilehtien asetukset', 'Child tab configuration', '子标签页配置', '子分頁設定', 'public fixture seed'),
  ('dataset_alias_management', 'Tietojoukkoaliasten hallinta', 'Dataset alias management', '数据集别名管理', '資料集別名管理', 'public fixture seed'),
  ('dataset_header_config', 'Tietojoukko-otsikoiden asetukset', 'Dataset header configuration', '数据集标题配置', '資料集標題設定', 'public fixture seed'),
  ('maintenance', 'Ylläpito', 'Maintenance', '维护', '維護', 'public fixture seed'),
  ('add_notification_trigger', 'Lisää ilmoituslaukaisin', 'Add notification trigger', '添加通知触发器', '新增通知觸發器', 'public fixture seed'),
  ('refresh_embeddings', 'Päivitä upotukset', 'Refresh embeddings', '刷新嵌入', '更新嵌入資料', 'public fixture seed'),
  ('check_json_columns', 'Tarkista JSON-sarakkeet', 'Check JSON columns', '检查 JSON 列', '檢查 JSON 欄位', 'public fixture seed'),
  ('database_consistency', 'Tietokannan eheys', 'Database consistency', '数据库一致性', '資料庫一致性', 'public fixture seed'),
  ('empty_rows', 'Tyhjät rivit', 'Empty rows', '空行', '空白資料列', 'public fixture seed'),
  ('fix_media_subfolders', 'Korjaa median alikansiot', 'Fix media subfolders', '修复媒体子文件夹', '修正媒體子資料夾', 'public fixture seed'),
  ('check_and_fix_all_datasets', 'Tarkista ja korjaa kaikki aineistot', 'Check & fix all datasets', '检查并修复所有数据集', '檢查並修正所有資料集', 'public fixture seed'),
  ('check_all_media_subfolders', 'Tarkista kaikki aineistot', 'Check all datasets', '检查所有数据集', '檢查所有資料集', 'public fixture seed'),
  ('fk_cache_triggers', 'Vierasavainvälimuistin laukaisimet', 'Foreign-key cache triggers', '外键缓存触发器', '外鍵快取觸發器', 'public fixture seed'),
  ('translation_helper', 'Käännösavustaja', 'Translation helper', '翻译助手', '翻譯助手', 'public fixture seed'),
  ('text_index_maintenance', 'Teksti-indeksien ylläpito', 'Text index maintenance', '文本索引维护', '文字索引維護', 'public fixture seed'),
  ('user_tools', 'Käyttäjän työkalut', 'User tools', '用户工具', '用戶工具', 'public fixture seed'),
  ('create', 'Luo', 'Create', '创建', '建立', 'public fixture seed'),
  ('user', 'Käyttäjä', 'User', '用户', '用戶', 'public fixture seed'),
  ('register', 'Rekisteröidy', 'Register', '注册', '註冊', 'public fixture seed'),
  ('database', 'Tietokanta', 'Database', '数据库', '資料庫', 'public fixture seed'),
  ('system', 'Järjestelmä', 'System', '系统', '系統', 'public fixture seed'),
  ('development', 'Kehitys', 'Development', '开发', '開發', 'public fixture seed'),
  ('apps', 'Sovellukset', 'Apps', '应用', '應用程式', 'public fixture seed'),
  ('filterest', 'Filterest', 'Filterest', 'Filterest', 'Filterest', 'public fixture seed'),
  ('users_and_groups', 'Käyttäjät ja ryhmät', 'Users and groups', '用户与用户组', '用戶同群組', 'public fixture seed'),
  ('logs', 'Lokit', 'Logs', '日志', '日誌', 'public fixture seed'),
  ('mgmt_helpers', 'Hallinnan apurakenteet', 'Management helpers', '管理辅助项', '管理輔助項目', 'public fixture seed'),
  ('functions_and_rights', 'Toiminnot ja oikeudet', 'Functions and rights', '功能与权限', '功能同權限', 'public fixture seed'),
  ('about', 'Tietoja', 'About', '关于', '關於', 'public fixture seed'),
  ('lang', 'Kielet', 'Language', '语言', '語言', 'public fixture seed'),
  ('tables', 'Taulut', 'Tables', '表格', '資料表', 'public fixture seed'),
  ('columns', 'Sarakkeet', 'Columns', '列', '欄位', 'public fixture seed'),
  ('other_tables', 'Muut taulut', 'Other tables', '其他表格', '其他資料表', 'public fixture seed'),

  -- Public runtime tables and fixture relations shown in the database tree.
  ('ai_chat_conversations', 'AI-keskustelut', 'AI chat conversations', 'AI 聊天记录', 'AI 對話', 'public fixture seed'),
  ('dokumentaatio_tiketit_relation', 'Dokumenttien ja tikettien relaatiot', 'Document and ticket relations', '文档与工单关系', '文件與工單關係', 'public fixture seed'),
  ('palvelukatalogi_dokumentaatio_relation', 'Palvelujen ja dokumenttien relaatiot', 'Service and document relations', '服务与文档关系', '服務與文件關係', 'public fixture seed'),
  ('palvelukatalogi_riskienhallinta_relation', 'Palvelujen ja riskien relaatiot', 'Service and risk relations', '服务与风险关系', '服務與風險關係', 'public fixture seed'),
  ('palvelukatalogi_tiketit_relation', 'Palvelujen ja tikettien relaatiot', 'Service and ticket relations', '服务与工单关系', '服務與工單關係', 'public fixture seed'),
  ('payments', 'Maksut', 'Payments', '付款', '付款', 'public fixture seed'),
  ('riskienhallinta_dokumentaatio_relation', 'Riskien ja dokumenttien relaatiot', 'Risk and document relations', '风险与文档关系', '風險與文件關係', 'public fixture seed'),
  ('riskienhallinta_tiketit_relation', 'Riskien ja tikettien relaatiot', 'Risk and ticket relations', '风险与工单关系', '風險與工單關係', 'public fixture seed'),
  ('spatial_ref_sys', 'Koordinaattijärjestelmät', 'Spatial reference systems', '空间参考系统', '空間參考系統', 'public fixture seed'),
  ('system_about', 'Järjestelmätiedot', 'System information', '系统信息', '系統資訊', 'public fixture seed'),
  ('system_audit_log', 'Auditointiloki', 'Audit log', '审计日志', '稽核記錄', 'public fixture seed'),
  ('system_child_tab_config', 'Alivälilehtien asetukset', 'Child tab configuration', '子标签页配置', '子分頁設定', 'public fixture seed'),
  ('system_column_control', 'Sarakkeiden hallinta', 'Column control', '列控制', '欄位控制', 'public fixture seed'),
  ('system_column_details', 'Sarakkeiden tiedot', 'Column details', '列详情', '欄位詳細資料', 'public fixture seed'),
  ('system_db_tables', 'Tietokannan taulut', 'Database tables', '数据库表', '資料庫資料表', 'public fixture seed'),
  ('system_db_version', 'Tietokantaversio', 'Database version', '数据库版本', '資料庫版本', 'public fixture seed'),
  ('system_embedding_refresh_jobs', 'Embedding-päivitysjono', 'Embedding refresh jobs', '嵌入刷新任务', '嵌入重新整理工作', 'public fixture seed'),
  ('system_dataset_sort_defaults', 'Taulujen lajitteluoletukset', 'Dataset Sort Defaults', '数据表排序默认值', '資料表排序預設值', 'public fixture seed'),
  ('system_dataset_media', 'Tietojoukkojen kuvat', 'Dataset Media', '数据集媒体', '資料集媒體', 'public fixture seed'),
  ('system_foreign_key_relations_1_m', 'Vierasavainrelaatiot 1:M', 'Foreign-key relations 1:M', '外键关系 1:M', '外鍵關係 1:M', 'public fixture seed'),
  ('system_foreign_key_relations_m_m', 'Vierasavainrelaatiot M:M', 'Foreign-key relations M:M', '外键关系 M:M', '外鍵關係 M:M', 'public fixture seed'),
  ('system_functions', 'Järjestelmätoiminnot', 'System functions', '系统功能', '系統功能', 'public fixture seed'),
  ('system_group_table_func_rights', 'Ryhmien taulutoimintojen oikeudet', 'Group table-function rights', '组表功能权限', '群組資料表功能權限', 'public fixture seed'),
  ('system_languages', 'Kielet', 'Languages', '语言', '語言', 'Static database-tree label for the canonical UI-language registry; authored for every supported locale so normal navigation never requests an AI translation.'),
  ('system_lang_key_translations', 'Kieliavainten käännökset', 'Language key translations', '语言键翻译', '語言鍵翻譯', 'Static database-tree label for normalized UI language-key translations; authored for every supported locale so normal navigation never requests an AI translation.'),
  ('system_lang_keys', 'Kieliavaimet', 'Language keys', '语言键', '語言鍵', 'public fixture seed'),
  ('system_lang_keys_archive', 'Kieliavainarkisto', 'Language-key archive', '语言键归档', '語言鍵封存', 'public fixture seed'),
  ('system_lang_key_sources', 'Kieliavainlähteet', 'Language-key sources', '语言键来源', '語言鍵來源', 'public fixture seed'),
  ('system_schema_migrations', 'Skeemamigraatiot', 'Schema migrations', '架构迁移', '結構描述遷移', 'public fixture seed'),
  ('system_table_folders', 'Taulukansiot', 'Table folders', '表格文件夹', '資料表資料夾', 'public fixture seed'),
  ('system_table_row_view_counts', 'Rivien näyttökerrat', 'Table row view counts', '表行查看次数', '資料列檢視次數', 'public fixture seed'),
  ('system_table_views', 'Taulunäkymät', 'Table views', '表格视图', '資料表檢視', 'public fixture seed'),
  ('system_transaction_log', 'Tapahtumaloki', 'Transaction log', '事务日志', '交易記錄', 'public fixture seed'),
  ('system_column_field_sets', 'Kenttäkokoelmat', 'Field collections', '字段集合', '欄位集合', 'public fixture seed'),
  ('system_column_field_set_members', 'Kenttäkokoelmien kentät', 'Field collection members', '字段集合成员', '欄位集合成員', 'public fixture seed'),
  ('system_view_field_set_assignments', 'Näkymien kenttäkokoelmat', 'View field assignments', '视图字段分配', '檢視欄位指派', 'public fixture seed'),
  ('edit_site_field_default', 'Muokkaa sivuston oletusta', 'Edit site default', '编辑站点默认字段', '編輯網站預設欄位', 'public fixture seed'),
  ('edit_personal_field_selection', 'Palaa omaan valintaan', 'Return to personal selection', '返回个人字段选择', '返回個人欄位選擇', 'public fixture seed'),
  ('return_to_site_default', 'Palaa sivuston oletukseen', 'Return to site default', '继承站点默认值', '使用網站預設值', 'public fixture seed'),
  ('site_default_restored', 'Sivuston oletus palautettu', 'Site default restored', '已恢复站点默认值', '已恢復網站預設值', 'public fixture seed'),
  ('shared', 'Jaettu', 'Shared', '共享', '共用', 'public fixture seed'),
  ('field_set_fields_placeholder', 'Kentät kenttäjoukossa', 'Fields in collection', '字段集中的字段', '欄位集中的欄位', 'public fixture seed'),
  ('fields_selected', 'kenttää valittu', 'fields selected', '个字段已选择', '個欄位已選取', 'public fixture seed'),
  ('system_user_group_memberships', 'Käyttäjäryhmien jäsenyydet', 'User group memberships', '用户组成员关系', '用戶群組成員關係', 'public fixture seed'),
  ('system_user_groups', 'Käyttäjäryhmät', 'User groups', '用户组', '用戶群組', 'public fixture seed'),
  ('system_users', 'Järjestelmän käyttäjät', 'System users', '系统用户', '系統用戶', 'public fixture seed'),
  ('views', 'Näkymät', 'Views', '视图', '檢視', 'public fixture seed'),
  ('geography_columns', 'Maantieteelliset sarakkeet', 'Geography columns', '地理列', '地理欄位', 'public fixture seed'),
  ('geometry_columns', 'Geometriasarakkeet', 'Geometry columns', '几何列', '幾何欄位', 'public fixture seed'),

  -- Article fields, generated relation labels, search labels, and child-tab actions.
  ('palvelu_id', 'Palvelun id', 'Service id', '服务 ID', '服務 ID', 'public fixture seed'),
  ('open_in_new_tab', 'Avaa uudessa välilehdessä', 'Open in new tab', '在新标签页中打开', '喺新分頁開啟', 'public fixture seed'),
  ('palvelu_name', 'Palvelun nimi', 'Service name', '服务名称', '服務名稱', 'public fixture seed'),
  ('dokumentaatio_id', 'Dokumentin id', 'Document id', '文档 ID', '文件 ID', 'public fixture seed'),
  ('dokumentaatio_name', 'Dokumentin nimi', 'Document name', '文档名称', '文件名稱', 'public fixture seed'),
  ('kuva', 'Kuva', 'Image', '图片', '圖片', 'public fixture seed'),
  ('riski_id', 'Riskin id', 'Risk id', '风险 ID', '風險 ID', 'public fixture seed'),
  ('riski_name', 'Riskin nimi', 'Risk name', '风险名称', '風險名稱', 'public fixture seed'),
  ('edit', 'Muokkaa', 'Edit', '编辑', '編輯', 'public fixture seed'),
  ('cancel', 'Peruuta', 'Cancel', '取消', '取消', 'public fixture seed'),
  ('delete', 'Poista', 'Delete', '删除', '刪除', 'public fixture seed'),
  ('riski_name (ln)', 'Riskin nimi', 'Risk name', '风险名称', '風險名稱', 'public fixture seed'),
  ('search_for_riski_name (ln)', 'Hae riskin nimestä', 'Search risk name', '搜索风险名称', '搜尋風險名稱', 'public fixture seed'),
  ('palvelu_name (ln)', 'Palvelun nimi', 'Service name', '服务名称', '服務名稱', 'public fixture seed'),
  ('search_for_palvelu_name (ln)', 'Hae palvelun nimestä', 'Search service name', '搜索服务名称', '搜尋服務名稱', 'public fixture seed'),
  ('dokumentaatio_name (ln)', 'Dokumentin nimi', 'Document name', '文档名称', '文件名稱', 'public fixture seed'),
  ('search_for_dokumentaatio_name (ln)', 'Hae dokumentin nimestä', 'Search document name', '搜索文档名称', '搜尋文件名稱', 'public fixture seed'),
  ('search_for_riski_id', 'Hae riskin id:stä', 'Search risk id', '搜索风险 ID', '搜尋風險 ID', 'public fixture seed'),
  ('search_for_maarapaiva', 'Hae määräpäivästä', 'Search due date', '搜索截止日期', '搜尋截止日期', 'public fixture seed'),
  ('search_for_id', 'Hae id:stä', 'Search id', '搜索 ID', '搜尋 ID', 'public fixture seed'),
  ('search_for_palvelu_id', 'Hae palvelun id:stä', 'Search service id', '搜索服务 ID', '搜尋服務 ID', 'public fixture seed'),
  ('search_for_dokumentaatio_id', 'Hae dokumentin id:stä', 'Search document id', '搜索文档 ID', '搜尋文件 ID', 'public fixture seed'),
  ('search_for_kuva', 'Hae kuvasta', 'Search image', '搜索图片', '搜尋圖片', 'public fixture seed'),
  ('search_for_created', 'Hae luontiajasta', 'Search creation time', '搜索创建时间', '搜尋建立時間', 'public fixture seed'),
  ('search_for_updated', 'Hae päivitysajasta', 'Search update time', '搜索更新时间', '搜尋更新時間', 'public fixture seed'),
  ('chat_for_table', 'Keskustelu – $table_name', 'Chat – $table_name', '$table_name 表聊天', '$table_name 資料表傾偈', 'public fixture seed'),
  ('chat_welcome_message', 'Miten voin auttaa tämän taulun kanssa?', 'How can I help with this table?', '我能如何协助处理此表？', '我可以點樣幫你處理呢個資料表？', 'public fixture seed'),
  ('delete_history', 'Poista keskusteluhistoria', 'Delete chat history', '删除聊天记录', '刪除對話記錄', 'public fixture seed'),
  ('open', 'Avaa', 'Open', '打开', '開啟', 'public fixture seed'),
  ('showing_first_50', 'Näytetään ensimmäiset 50 riviä', 'Showing the first 50 rows', '显示前 50 行', '顯示首 50 個資料列', 'public fixture seed'),
  ('name', 'Nimi', 'Name', '名称', '名稱', 'public fixture seed'),
  ('comments', 'Kommentit', 'Comments', '评论', '留言', 'public fixture seed'),
  ('write_comment', 'Kirjoita kommentti', 'Write a comment', '撰写评论', '撰寫留言', 'public fixture seed'),
  ('send', 'Lähetä', 'Send', '发送', '傳送', 'public fixture seed'),

  ('row_article_section_details', 'Tiedot', 'Details', '详细信息', '詳細資料', 'public fixture seed'),
  ('row_article_section_task_progress', 'Edistyminen', 'Progress', '进度', '進度', 'public fixture seed'),
  ('row_article_section_images', 'Kuvat', 'Images', '图片', '圖片', 'public fixture seed'),
  ('row_article_section_attachments', 'Liitteet', 'Attachments', '附件', '附件', 'public fixture seed'),
  ('row_article_section_related_rows', 'Liittyvät rivit', 'Related rows', '关联行', '關聯資料列', 'public fixture seed'),
  ('search_for_palvelu', 'Hae palvelusta', 'Search service', '搜索服务', '搜尋服務', 'public fixture seed'),
  ('search_for_kuvaus', 'Hae kuvauksesta', 'Search description', '搜索描述', '搜尋描述', 'public fixture seed'),
  ('search_for_omistava_tiimi', 'Hae omistavasta tiimistä', 'Search owning team', '搜索负责团队', '搜尋負責團隊', 'public fixture seed'),
  ('search_for_palvelutaso', 'Hae palvelutasosta', 'Search service level', '搜索服务级别', '搜尋服務級別', 'public fixture seed'),
  ('search_for_tila', 'Hae tilasta', 'Search status', '搜索状态', '搜尋狀態', 'public fixture seed'),
  ('search_for_vastuuhenkilo', 'Hae vastuuhenkilöstä', 'Search owner', '搜索负责人', '搜尋負責人', 'public fixture seed'),
  ('search_for_riski', 'Hae riskistä', 'Search risk', '搜索风险', '搜尋風險', 'public fixture seed'),
  ('search_for_vaikutus', 'Hae vaikutuksesta', 'Search impact', '搜索影响', '搜尋影響', 'public fixture seed'),
  ('search_for_riskitaso', 'Hae riskitasosta', 'Search risk level', '搜索风险级别', '搜尋風險級別', 'public fixture seed'),
  ('search_for_todennakoisyys', 'Hae todennäköisyydestä', 'Search likelihood', '搜索可能性', '搜尋可能性', 'public fixture seed'),
  ('search_for_alentamistoimet', 'Hae hallintatoimista', 'Search mitigation', '搜索缓解措施', '搜尋緩解措施', 'public fixture seed'),
  ('search_for_otsikko', 'Hae otsikosta', 'Search title', '搜索标题', '搜尋標題', 'public fixture seed'),
  ('search_for_kohdetiimi', 'Hae kohdetiimistä', 'Search target team', '搜索目标团队', '搜尋目標團隊', 'public fixture seed'),
  ('search_for_ohje', 'Hae ohjeesta', 'Search guidance', '搜索指南', '搜尋指引', 'public fixture seed'),
  ('search_for_voimassaolo', 'Hae voimassaolosta', 'Search validity', '搜索有效性', '搜尋有效性', 'public fixture seed'),
  ('search_for_vastuutiimi', 'Hae vastuutiimistä', 'Search responsible team', '搜索负责团队', '搜尋負責團隊', 'public fixture seed'),
  ('search_for_prioriteetti', 'Hae prioriteetista', 'Search priority', '搜索优先级', '搜尋優先次序', 'public fixture seed'),
  ('search_for_pyyntotyyppi', 'Hae pyyntötyypistä', 'Search request type', '搜索请求类型', '搜尋請求類型', 'public fixture seed')
ON CONFLICT (lang_key) DO UPDATE
SET fi = EXCLUDED.fi,
    en = EXCLUDED.en,
    ch = EXCLUDED.ch,
    yue = EXCLUDED.yue,
    updated = now(),
    creation_spec = EXCLUDED.creation_spec;

-- Public runtime metadata columns. Finnish and English values are aligned with
-- the current Filterest VPS where available; Chinese values are curated here so
-- generated instances never need AI translation for ordinary dataset metadata.
INSERT INTO public.system_lang_keys (lang_key, fi, en, ch, yue, creation_spec) VALUES
  ('id', 'Tunniste', 'ID', 'ID', 'ID', 'public fixture metadata seed'),
  ('created', 'Luotu', 'Created', '创建时间', '建立時間', 'public fixture metadata seed'),
  ('updated', 'Päivitetty', 'Updated', '更新时间', '更新時間', 'public fixture metadata seed'),
  ('description', 'Kuvaus', 'Description', '描述', '描述', 'curated shared row-description label'),
  ('link', 'Linkki', 'Link', '链接', '連結', 'curated shared row-link label'),
  ('keywords', 'Avainsanat', 'Keywords', '关键词', '關鍵字', 'curated shared row-keywords label'),
  ('admin_access_allowed', 'Kelpaa ylläpitäjäksi', 'Admin eligible', '可担任管理员', '可擔任管理員', 'public fixture metadata seed'),
  ('admin_approved', 'Hyväksytty', 'Approved', '已批准', '已批准', 'public fixture metadata seed'),
  ('admin_user_id', 'Järjestelmänvalvojan käyttäjätunnus', 'Admin user ID', '管理员用户 ID', '管理員用戶 ID', 'public fixture metadata seed'),
  ('amount_cents', 'Summa (sentteinä)', 'Amount (cents)', '金额（分）', '金額（仙）', 'public fixture metadata seed'),
  ('applied_at', 'Käytetty', 'Applied at', '应用时间', '套用時間', 'public fixture metadata seed'),
  ('app_name', 'Sovelluksen nimi', 'App name', '应用名称', '應用程式名稱', 'public fixture metadata seed'),
  ('archived_at', 'Arkistoitu', 'Archived at', '归档时间', '封存時間', 'public fixture metadata seed'),
  ('auth_name', 'Auktoriteetin nimi', 'Authority name', '授权机构名称', '授權機構名稱', 'public fixture metadata seed'),
  ('auth_srid', 'Auktoriteetin SRID', 'Authority SRID', '授权机构 SRID', '授權機構 SRID', 'public fixture metadata seed'),
  ('bio_social_medias', 'Bio', 'Bio', '个人简介', '個人簡介', 'public fixture metadata seed'),
  ('boolean_value', 'Totuusarvo', 'Boolean value', '布尔值', '布林值', 'public fixture metadata seed'),
  ('bridging_col_a', 'Yhdistävä sarake A', 'Bridging column A', '桥接列 A', '橋接欄位 A', 'public fixture metadata seed'),
  ('bridging_col_b', 'Yhdistävä sarake B', 'Bridging column B', '桥接列 B', '橋接欄位 B', 'public fixture metadata seed'),
  ('bridging_table_name', 'Yhdistävän taulun nimi', 'Bridging table name', '桥接表名称', '橋接資料表名稱', 'public fixture metadata seed'),
  ('bridging_table_uid', 'Välitaulun UID', 'Bridging table UID', '桥接表 UID', '橋接資料表 UID', 'public fixture metadata seed'),
  ('cached_name_col_in_src', '@nimen sarake lähteessä', '@name column in source', '源表中的缓存名称列', '來源資料表嘅快取名稱欄位', 'public fixture metadata seed'),
  ('cached_oid', '@OID', 'Cached OID', '缓存 OID', '快取 OID', 'public fixture metadata seed'),
  ('card_detail_capitalization', 'Kortin yksityiskohdan kapitalisointi', 'Card detail capitalization', '卡片详情首字母大写', '卡片詳細資料首字母大寫', 'public fixture metadata seed'),
  ('card_detail_icon_key', 'Kortin yksityiskohdan kuvakeavain', 'Card detail icon key', '卡片详情图标键', '卡片詳細資料圖示鍵', 'public fixture metadata seed'),
  ('card_detail_icon_svg', 'Kortin yksityiskohdan kuvake SVG', 'Card detail icon SVG', '卡片详情图标 SVG', '卡片詳細資料圖示 SVG', 'public fixture metadata seed'),
  ('card_detail_label_mode', 'Kortin yksityiskohdan otsikon tila', 'Card detail label mode', '卡片详情标签模式', '卡片詳細資料標籤模式', 'public fixture metadata seed'),
  ('card_details_layout', 'Kortin tietojen asettelu', 'Card details layout', '卡片详情布局', '卡片詳細資料版面', 'public fixture metadata seed'),
  ('card_element', 'Kortin elementti', 'Card element', '卡片元素', '卡片元素', 'public fixture metadata seed'),
  ('card_style_variant', 'Kortin tyylivariantti', 'Card style variant', '卡片样式变体', '卡片樣式變體', 'public fixture metadata seed'),
  ('ch', 'Kiina', 'Chinese', '简体中文', '簡體中文', 'public fixture metadata seed'),
  ('column_label', 'Sarakkeen otsikko', 'Column label', '列标签', '欄位標籤', 'public fixture metadata seed'),
  ('column_name', 'Sarakkeen nimi', 'Column name', '列名', '欄位名稱', 'public fixture metadata seed'),
  ('column_uid', 'Sarakkeen UID', 'Column UID', '列 UID', '欄位 UID', 'public fixture metadata seed'),
  ('column_width_px', 'Sarakkeen leveys (px)', 'Column width (px)', '列宽（像素）', '欄位寬度（像素）', 'public fixture metadata seed'),
  ('co_number', 'CO-numero', 'CO number', 'CO 编号', 'CO 編號', 'public fixture metadata seed'),
  ('created_at', 'Luotu', 'Created at', '创建时间', '建立時間', 'public fixture metadata seed'),
  ('creation_spec', 'Tiedot luomisesta', 'Creation specification', '创建说明', '建立規格', 'public fixture metadata seed'),
  ('currency', 'Valuutta', 'Currency', '货币', '貨幣', 'public fixture metadata seed'),
  ('customer_email', 'Asiakkaan sähköposti', 'Customer email', '客户电子邮件', '客戶電郵', 'public fixture metadata seed'),
  ('dataset', 'Aineisto', 'Dataset', '数据集', '資料集', 'public fixture metadata seed'),
  ('data_type', 'Datatyyppi', 'Data type', '数据类型', '資料類型', 'public fixture metadata seed'),
  ('default_view_id', 'Näkymän oletustunnus', 'Default view ID', '默认视图 ID', '預設檢視 ID', 'public fixture metadata seed'),
  ('details', 'Tiedot', 'Details', '详细信息', '詳細資料', 'public fixture metadata seed'),
  ('disabled', 'Pois käytöstä', 'Disabled', '已禁用', '已停用', 'public fixture metadata seed'),
  ('display_name', 'Näyttönimi', 'Display name', '显示名称', '顯示名稱', 'public fixture metadata seed'),
  ('duration_ms', 'Kesto (ms)', 'Duration (ms)', '持续时间（毫秒）', '持續時間（毫秒）', 'public fixture metadata seed'),
  ('editable_in_ui', 'Muokattavissa käyttöliittymässä', 'Editable in UI', '可在界面中编辑', '可喺介面編輯', 'public fixture metadata seed'),
  ('en', 'Englanti', 'English', '英语', '英文', 'public fixture metadata seed'),
  ('enabled', 'Käytössä', 'Enabled', '已启用', '已啟用', 'public fixture metadata seed'),
  ('error_message', 'Virheilmoitus', 'Error message', '错误消息', '錯誤訊息', 'public fixture metadata seed'),
  ('external_order_id', 'Ulkoinen tilaus-ID', 'External order ID', '外部订单 ID', '外部訂單 ID', 'public fixture metadata seed'),
  ('fco_number', 'FCO-numero', 'FCO number', 'FCO 编号', 'FCO 編號', 'public fixture metadata seed'),
  ('fi', 'Suomi', 'Finnish', '芬兰语', '芬蘭文', 'public fixture metadata seed'),
  ('filename', 'Tiedostonimi', 'Filename', '文件名', '檔案名稱', 'public fixture metadata seed'),
  ('filterbar_visible_by_default', 'Suodatinpalkki oletuksena näkyvissä', 'Filter bar visible by default', '默认显示筛选栏', '預設顯示篩選列', 'public fixture metadata seed'),
  ('fk_display_column', 'Viiteavaimen näyttösarake', 'FK display column', '外键显示列', '外鍵顯示欄位', 'public fixture metadata seed'),
  ('folder_description', 'Kansion kuvaus', 'Folder description', '文件夹描述', '資料夾描述', 'public fixture metadata seed'),
  ('folder_id', 'Kansion tunnus', 'Folder ID', '文件夹 ID', '資料夾 ID', 'public fixture metadata seed'),
  ('folder_name', 'Kansion nimi', 'Folder name', '文件夹名称', '資料夾名稱', 'public fixture metadata seed'),
  ('full_name', 'Koko nimi', 'Full name', '全名', '全名', 'public fixture metadata seed'),
  ('function_id', 'Toiminnon tunniste', 'Function ID', '功能 ID', '功能 ID', 'public fixture metadata seed'),
  ('group_id', 'Ryhmä ID', 'Group ID', '用户组 ID', '群組 ID', 'public fixture metadata seed'),
  ('handler_name', 'Käsittelijän nimi', 'Handler name', '处理程序名称', '處理程式名稱', 'public fixture metadata seed'),
  ('hidden', 'Piilotettu', 'Hidden', '已隐藏', '已隱藏', 'public fixture metadata seed'),
  ('hide_everywhere', 'Piilota kaikkialla', 'Hide everywhere', '在所有位置隐藏', '喺所有位置隱藏', 'public fixture metadata seed'),
  ('hide_false_null_on_big_crd', 'Piilota epätosi/tyhjä isossa kortissa', 'Hide false/null on big card', '在文章视图中隐藏假值或空值', '喺文章檢視隱藏假值或空值', 'public fixture metadata seed'),
  ('hide_false_null_on_sml_crd', 'Piilota epätosi/tyhjä pienessä kortissa', 'Hide false/null on small card', '在小卡片中隐藏假值或空值', '喺細卡片隱藏假值或空值', 'public fixture metadata seed'),
  ('hide_in_filter_panel', 'Piilota suodatinpaneelissa', 'Hide in filter panel', '在筛选面板中隐藏', '喺篩選面板隱藏', 'public fixture metadata seed'),
  ('hide_on_bg_crd_if_not_own', 'Piilota isossa kortissa, jos ei oma', 'Hide on big card if not own', '非本人记录时在文章视图中隐藏', '唔係自己記錄時喺文章檢視隱藏', 'public fixture metadata seed'),
  ('hide_on_small_card', 'Piilota pienessä kortissa', 'Hide on small card', '在小卡片中隐藏', '喺細卡片隱藏', 'public fixture metadata seed'),
  ('http_method', 'HTTP-menetelmä', 'HTTP method', 'HTTP 方法', 'HTTP 方法', 'public fixture metadata seed'),
  ('icon_key', 'Kuvakkeen avain', 'Icon key', '图标键', '圖示鍵', 'public fixture metadata seed'),
  ('insertable', 'Lisättävä', 'Insertable', '可插入', '可新增', 'public fixture metadata seed'),
  ('insert_expln_langkey', 'Lisää selitys', 'Insert explanation', '插入说明', '新增說明', 'public fixture metadata seed'),
  ('insert_new_source_with_target', 'Lisää uusi lähde kohteella', 'Insert new source with target', '使用目标插入新来源', '使用目標新增來源', 'public fixture metadata seed'),
  ('insert_new_target_with_source', 'Lisää uusi kohde lähteellä', 'Insert new target with source', '使用来源插入新目标', '使用來源新增目標', 'public fixture metadata seed'),
  ('instance_id', 'Instanssin tunniste', 'Instance ID', '实例 ID', '執行個體 ID', 'public fixture metadata seed'),
  ('int_value', 'Kokonaisluku', 'Integer value', '整数值', '整數值', 'public fixture metadata seed'),
  ('ip_address', 'IP-osoite', 'IP address', 'IP 地址', 'IP 位址', 'public fixture metadata seed'),
  ('is_about_table', 'Onko tietoja-taulu', 'Is about table', '是信息表', '係資訊資料表', 'public fixture metadata seed'),
  ('is_current_project', 'On nykyinen projekti', 'Is current project', '是当前项目', '係目前專案', 'public fixture metadata seed'),
  ('is_default', 'On oletus', 'Is default', '是默认值', '係預設值', 'public fixture metadata seed'),
  ('is_hidden', 'On piilotettu', 'Is hidden', '已隐藏', '已隱藏', 'public fixture metadata seed'),
  ('is_main_table', 'Onko päätaulu', 'Is main table', '是主表', '係主要資料表', 'public fixture metadata seed'),
  ('is_multilingual', 'On monikielinen', 'Is multilingual', '支持多语言', '支援多語言', 'public fixture metadata seed'),
  ('is_removable', 'On poistettavissa', 'Is removable', '可删除', '可刪除', 'public fixture metadata seed'),
  ('json_value', 'JSON-arvo', 'JSON value', 'JSON 值', 'JSON 值', 'public fixture metadata seed'),
  ('key', 'Avain', 'Key', '键', '鍵', 'public fixture metadata seed'),
  ('lang_key', 'Avain', 'Key', '语言键', '語言鍵', 'public fixture metadata seed'),
  ('lang_key_id', 'Kieliavaimen tunniste', 'Language key ID', '语言键 ID', '語言鍵 ID', 'public fixture metadata seed'),
  ('lang_key_type', 'Kieliavaintyyppi', 'Language key type', '语言键类型', '語言鍵類型', 'public fixture metadata seed'),
  ('last_seen', 'Viimeksi nähty', 'Last seen', '最后出现时间', '最後出現時間', 'public fixture metadata seed'),
  ('main_group_id', 'Pääryhmän tunniste', 'Main group ID', '主用户组 ID', '主要群組 ID', 'public fixture metadata seed'),
  ('mandatory', 'Pakollinen', 'Mandatory', '必填', '必填', 'public fixture metadata seed'),
  ('messages', 'Viestit', 'Messages', '消息', '訊息', 'public fixture metadata seed'),
  ('metadata', 'Metatiedot', 'Metadata', '元数据', '中繼資料', 'public fixture metadata seed'),
  ('method', 'Menetelmä', 'Method', '方法', '方法', 'public fixture metadata seed'),
  ('multi_lang_embeddings', 'Monikieliset upotteet', 'Multilingual embeddings', '多语言嵌入', '多語言嵌入', 'public fixture metadata seed'),
  ('must_be_true_unless_own', 'Täytyy olla tosi, ellei oma', 'Must be true unless own', '除本人记录外必须为真', '除自己記錄外必須為真', 'public fixture metadata seed'),
  ('name_col_in_tgt', 'Nimisarake kohteessa', 'Name column in target', '目标中的名称列', '目標入面嘅名稱欄位', 'public fixture metadata seed')
ON CONFLICT (lang_key) DO UPDATE
SET fi = EXCLUDED.fi,
    en = EXCLUDED.en,
    ch = EXCLUDED.ch,
    yue = EXCLUDED.yue,
    updated = now(),
    creation_spec = EXCLUDED.creation_spec;

INSERT INTO public.system_lang_keys (lang_key, fi, en, ch, yue, creation_spec) VALUES
  ('operation_type', 'Toiminnon tyyppi', 'Operation type', '操作类型', '操作類型', 'public fixture metadata seed'),
  ('original_created', 'Alkuperäinen luontiaika', 'Original created', '原始创建时间', '原始建立時間', 'public fixture metadata seed'),
  ('original_id', 'Alkuperäinen ID', 'Original ID', '原始 ID', '原始 ID', 'public fixture metadata seed'),
  ('original_updated', 'Alkuperäinen päivitysaika', 'Original updated', '原始更新时间', '原始更新時間', 'public fixture metadata seed'),
  ('orphan_since', 'Orpo siitä lähtien', 'Orphan since', '成为孤立项的时间', '成為孤立項目嘅時間', 'public fixture metadata seed'),
  ('package', 'Paketti', 'Package', '包', '套件', 'public fixture metadata seed'),
  ('paid_at', 'Maksettu', 'Paid at', '付款时间', '付款時間', 'public fixture metadata seed'),
  ('parent_id', 'Vanhempi-ID', 'Parent ID', '父级 ID', '上層 ID', 'public fixture metadata seed'),
  ('parent_table', 'Päätaulu', 'Parent table', '父表', '上層資料表', 'public fixture metadata seed'),
  ('payment_token', 'Maksutunniste', 'Payment token', '支付令牌', '付款權杖', 'public fixture metadata seed'),
  ('predecessor_id', 'Edeltäjän ID', 'Predecessor ID', '前置项 ID', '前置項目 ID', 'public fixture metadata seed'),
  ('preview', 'Esikatselu', 'Preview', '预览', '預覽', 'public fixture metadata seed'),
  ('privileged', 'Etuoikeutettu', 'Privileged', '特权用户', '特權用戶', 'public fixture metadata seed'),
  ('proj4text', 'PROJ.4-teksti', 'PROJ.4 text', 'PROJ.4 文本', 'PROJ.4 文字', 'public fixture metadata seed'),
  ('rate_limit_amount', 'Rajoituksen määrä', 'Rate limit amount', '速率限制数量', '速率限制數量', 'public fixture metadata seed'),
  ('rate_limit_minutes', 'Rajoituksen minuutit', 'Rate limit minutes', '速率限制分钟数', '速率限制分鐘數', 'public fixture metadata seed'),
  ('reference_direction', 'Viittauksen suunta', 'Reference direction', '引用方向', '參照方向', 'public fixture metadata seed'),
  ('revolut_checkout_url', 'Revolut-kassan URL', 'Revolut checkout URL', 'Revolut 结账 URL', 'Revolut 結帳 URL', 'public fixture metadata seed'),
  ('revolut_order_id', 'Revolut-tilaus-ID', 'Revolut order ID', 'Revolut 订单 ID', 'Revolut 訂單 ID', 'public fixture metadata seed'),
  ('row_id', 'Rivitunnus', 'Row ID', '行 ID', '資料列 ID', 'public fixture metadata seed'),
  ('row_policy_owner_column', 'Rivipolitiikan omistajasarake', 'Row-policy owner column', '行策略所有者列', '資料列政策擁有者欄位', 'public fixture metadata seed'),
  ('schema_name', 'Skeeman nimi', 'Schema name', '模式名称', '結構描述名稱', 'public fixture metadata seed'),
  ('sco_number', 'SCO-numero', 'SCO number', 'SCO 编号', 'SCO 編號', 'public fixture metadata seed'),
  ('search_placeholder', 'Hakupaikkamerkki', 'Search placeholder', '搜索占位文本', '搜尋預留位置文字', 'public fixture metadata seed'),
  ('search_slogan', 'Hakuiskulause', 'Search slogan', '搜索提示语', '搜尋提示語', 'public fixture metadata seed'),
  ('search_vector_simple', 'Yksinkertainen hakuvektori', 'Simple search vector', '简单搜索向量', '簡單搜尋向量', 'public fixture metadata seed'),
  ('show_key_on_card', 'Näytä avain kortilla', 'Show key on card', '在卡片上显示键', '喺卡片顯示鍵', 'public fixture metadata seed'),
  ('show_value_on_card', 'Näytä arvo kortissa', 'Show value on card', '在卡片上显示值', '喺卡片顯示值', 'public fixture metadata seed'),
  ('sort_order', 'Lajittelujärjestys', 'Sort order', '排序顺序', '排序次序', 'public fixture metadata seed'),
  ('source_column_name', 'Lähdesarakkeen nimi', 'Source column name', '源列名称', '來源欄位名稱', 'public fixture metadata seed'),
  ('source_high', 'Lähde korkea', 'Source high', '高优先级来源', '高優先級來源', 'public fixture metadata seed'),
  ('source_insert_specs', 'Lähteen lisäyksen määrittelyt', 'Source insert specifications', '来源插入规范', '來源新增規格', 'public fixture metadata seed'),
  ('source_low', 'Lähde matala', 'Source low', '低优先级来源', '低優先級來源', 'public fixture metadata seed'),
  ('source_table_uid', 'Lähdetaulun UID', 'Source table UID', '源表 UID', '來源資料表 UID', 'public fixture metadata seed'),
  ('source_type', 'Lähteen tyyppi', 'Source type', '来源类型', '來源類型', 'public fixture metadata seed'),
  ('specific_table_related', 'Tiettyyn tauluun liittyvä', 'Specific table related', '与特定表相关', '同特定資料表相關', 'public fixture metadata seed'),
  ('sql_dump_policy', 'SQL dump -käytäntö', 'SQL dump policy', 'SQL 转储策略', 'SQL 傾印政策', 'public fixture metadata seed'),
  ('srid', 'SRID', 'SRID', 'SRID', 'SRID', 'public fixture metadata seed'),
  ('srtext', 'Paikkaviitteen määritelmä', 'Spatial reference text', '空间参考文本', '空間參照文字', 'public fixture metadata seed'),
  ('status', 'Tila', 'Status', '状态', '狀態', 'public fixture metadata seed'),
  ('success', 'Onnistui', 'Success', '成功', '成功', 'public fixture metadata seed'),
  ('tab_key', 'Välilehden avain', 'Tab key', '标签页键', '分頁鍵', 'public fixture metadata seed'),
  ('table_a_column', 'Taulun A sarake', 'Table A column', '表 A 的列', '資料表 A 嘅欄位', 'public fixture metadata seed'),
  ('table_a_uid', 'Taulun A UID', 'Table A UID', '表 A UID', '資料表 A UID', 'public fixture metadata seed'),
  ('table_b_column', 'Taulun B sarake', 'Table B column', '表 B 的列', '資料表 B 嘅欄位', 'public fixture metadata seed'),
  ('table_b_uid', 'Taulun B UID', 'Table B UID', '表 B UID', '資料表 B UID', 'public fixture metadata seed'),
  ('table_name', 'Taulun nimi', 'Table name', '表名', '資料表名稱', 'public fixture metadata seed'),
  ('table_uid', 'Taulun UID', 'Table UID', '表 UID', '資料表 UID', 'public fixture metadata seed'),
  ('tab_order', 'Välilehtien järjestys', 'Tab order', '标签页顺序', '分頁次序', 'public fixture metadata seed'),
  ('tab_order_json', 'Välilehtien järjestys JSON', 'Tab order JSON', '标签页顺序 JSON', '分頁次序 JSON', 'public fixture metadata seed'),
  ('target_column_name', 'Kohdesarakkeen nimi', 'Target column name', '目标列名称', '目標欄位名稱', 'public fixture metadata seed'),
  ('target_insert_specs', 'Kohteen lisäyksen määrittelyt', 'Target insert specifications', '目标插入规范', '目標新增規格', 'public fixture metadata seed'),
  ('target_schema_name', 'Kohdeskeeman nimi', 'Target schema name', '目标模式名称', '目標結構描述名稱', 'public fixture metadata seed'),
  ('target_table_uid', 'Kohdetaulun UID', 'Target table UID', '目标表 UID', '目標資料表 UID', 'public fixture metadata seed'),
  ('text_value', 'Tekstiarvo', 'Text value', '文本值', '文字值', 'public fixture metadata seed'),
  ('tiketti_id', 'Tiketin ID', 'Ticket ID', '工单 ID', '工單 ID', 'public fixture metadata seed'),
  ('title', 'Otsikko', 'Title', '标题', '標題', 'public fixture metadata seed'),
  ('ui_only', 'Vain käyttöliittymä', 'UI only', '仅限界面', '只限介面', 'public fixture metadata seed'),
  ('updated_at', 'Päivitetty', 'Updated at', '更新时间', '更新時間', 'public fixture metadata seed'),
  ('url_path', 'URL-polku', 'URL path', 'URL 路径', 'URL 路徑', 'public fixture metadata seed'),
  ('url_route_endpoint', 'URL-reitin päätepiste', 'URL route endpoint', 'URL 路由端点', 'URL 路由端點', 'public fixture metadata seed'),
  ('usage_explanation', 'Käyttöselite', 'Usage explanation', '使用说明', '使用說明', 'public fixture metadata seed'),
  ('user_group_id', 'Käyttäjäryhmän tunnus', 'User group ID', '用户组 ID', '用戶群組 ID', 'public fixture metadata seed'),
  ('email', 'Sähköposti', 'Email', '电子邮件', '電郵', 'public fixture metadata seed'),
  ('password', 'Salasana', 'Password', '密码', '密碼', 'public fixture metadata seed'),
  ('username', 'Käyttäjätunnus', 'Username', '用户名', '用戶名稱', 'public fixture metadata seed'),
  ('value_type', 'Arvon tyyppi', 'Value type', '值类型', '值類型', 'public fixture metadata seed'),
  ('version', 'Versio', 'Version', '版本', '版本', 'public fixture metadata seed'),
  ('viewed_by_user_id', 'Katsottu käyttäjätunnuksella', 'Viewed by user ID', '查看者用户 ID', '檢視者用戶 ID', 'public fixture metadata seed'),
  ('visible', 'Näkyvä', 'Visible', '可见', '可見', 'public fixture metadata seed'),
  ('webhook_received_at', 'Webhook vastaanotettu', 'Webhook received at', '收到 Webhook 的时间', '收到 Webhook 嘅時間', 'public fixture metadata seed'),
  ('previous_image', 'Edellinen kuva', 'Previous image', '上一张图片', '上一張圖片', 'Accessible label for moving to the previous image in an image-first article.'),
  ('next_image', 'Seuraava kuva', 'Next image', '下一张图片', '下一張圖片', 'Accessible label for moving to the next image in an image-first article.'),
  ('previous_row', 'Edellinen tietue', 'Previous record', '上一条记录', '上一筆資料', 'Accessible label for experimental navigation to the previous permitted result row.'),
  ('next_row', 'Seuraava tietue', 'Next record', '下一条记录', '下一筆資料', 'Accessible label for experimental navigation to the next permitted result row.'),
  ('open_article', 'Avaa artikkeli', 'Open article', '打开文章', '開啟文章', 'Accessible label for opening an image-first article from its card image.'),
  ('article_records', 'Artikkelin tietueet', 'Article records', '文章记录', '文章資料', 'Accessible navigation-region label for moving between permitted result rows.'),
  ('yue', 'Kantoninkiina', 'Cantonese', '粤语', '粵語', 'public fixture metadata seed')
ON CONFLICT (lang_key) DO UPDATE
SET fi = EXCLUDED.fi,
    en = EXCLUDED.en,
    ch = EXCLUDED.ch,
    yue = EXCLUDED.yue,
    updated = now(),
    creation_spec = EXCLUDED.creation_spec;

-- A fresh public installation asks its owner to choose the first login-ready
-- administrator. These labels mirror the upgrade migration so the reduced
-- deterministic bootstrap works without opening the general migration gate.
INSERT INTO public.system_lang_keys (lang_key, fi, en, ch, yue, creation_spec) VALUES
  ('first_run_admin_title', 'Luo ensimmäinen pääkäyttäjä', 'Create the first administrator', '创建首位管理员', '建立第一位管理員', 'Public first-run administrator setup label.'),
  ('first_run_admin_description', 'Valitse tämän asennuksen sivuston nimi ja pääkäyttäjän tunnukset. Sähköpostia käytetään myös tilin palautukseen ja viesteihin.', 'Choose the site name and administrator credentials for this installation. Email is also used for account recovery and messages.', '为此安装设置站点名称和管理员凭据。电子邮件也用于账户恢复和消息。', '為此安裝設定網站名稱及管理員登入資料。電郵亦用於帳戶復原及訊息。', 'Public first-run administrator setup label.'),
  ('first_run_admin_submit', 'Luo pääkäyttäjä', 'Create administrator', '创建管理员', '建立管理員', 'Public first-run administrator setup label.'),
  ('confirm_password', 'Vahvista salasana', 'Confirm password', '确认密码', '確認密碼', 'Public first-run administrator setup label.'),
  ('first_run_username_invalid', 'Käytä 3–64 merkkiä: kirjaimia, numeroita, pisteitä, alaviivoja tai yhdysmerkkejä.', 'Use 3–64 characters: letters, numbers, dots, underscores, or hyphens.', '请输入 3–64 个字符，可使用字母、数字、句点、下划线或连字符。', '請輸入 3–64 個字元，可使用字母、數字、句號、底線或連字號。', 'Public first-run administrator validation label.'),
  ('first_run_email_invalid', 'Anna kelvollinen sähköpostiosoite.', 'Enter a valid email address.', '请输入有效的电子邮件地址。', '請輸入有效的電郵地址。', 'Public first-run administrator validation label.'),
  ('first_run_password_invalid', 'Käytä 12–128 merkin pituista salasanaa.', 'Use a password containing 12–128 characters.', '密码长度须为 12–128 个字符。', '密碼長度須為 12–128 個字元。', 'Public first-run administrator validation label.'),
  ('first_run_password_mismatch', 'Salasanat eivät täsmää.', 'The passwords do not match.', '两次输入的密码不一致。', '兩次輸入的密碼不一致。', 'Public first-run administrator validation label.'),
  ('first_run_admin_creation_failed', 'Pääkäyttäjää ei voitu luoda. Mitään asetusmuutoksia ei tallennettu.', 'The administrator could not be created. No setup changes were saved.', '无法创建管理员，未保存任何设置更改。', '無法建立管理員，未儲存任何設定變更。', 'Public first-run administrator failure label.'),
  ('form_sections', 'Lomakkeen osiot', 'Form sections', '表单部分', '表格部分', 'Public reusable form navigation label.'),
  ('previous', 'Edellinen', 'Previous', '上一步', '上一步', 'Public reusable form navigation label.'),
  ('next', 'Seuraava', 'Next', '下一步', '下一步', 'Public reusable form navigation label.'),
  ('back', 'Takaisin', 'Back', '返回', '返回', 'Public reusable form navigation label.'),
  ('proceed', 'Jatka', 'Proceed', '继续', '繼續', 'Public reusable form navigation label.'),
  ('first_run_welcome', 'Tervetuloa Filterestiin!', 'Welcome to Filterest!', '欢迎使用 Filterest！', '歡迎使用 Filterest！', 'Public First Run label.'),
  ('first_run_site_name', 'Sivuston nimi', 'Site name', '站点名称', '網站名稱', 'Public First Run label.'),
  ('first_run_site_name_invalid', 'Anna sivustolle 1–100 merkkiä pitkä nimi.', 'Enter a site name containing 1–100 characters.', '请输入 1–100 个字符的站点名称。', '請輸入 1–100 個字元的網站名稱。', 'Public First Run validation label.'),
  ('first_run_section_settings', 'Ympäristö', 'Environment', '环境', '環境', 'Public First Run label.'),
  ('first_run_section_credentials', 'Tunnukset', 'Credentials', '登录凭据', '登入資料', 'Public First Run label.'),
  ('first_run_settings_title', 'Määritä työympäristö', 'Set up your workspace', '设置工作区', '設定工作區', 'Public First Run label.'),
  ('first_run_settings_description', 'Valitse asennuksen käyttötarkoitus ja tapa, jolla ensimmäinen pääkäyttäjä varmentaa kirjautumiset.', 'Choose how this installation is used and how the first administrator verifies sign-ins.', '选择此安装的用途以及首位管理员验证登录的方式。', '選擇此安裝的用途，以及首位管理員驗證登入的方式。', 'Public First Run label.'),
  ('first_run_environment_legend', 'Ympäristö', 'Environment', '环境', '環境', 'Public First Run label.'),
  ('environment_development', 'Devaus', 'Development', '开发', '開發', 'Public First Run label.'),
  ('environment_development_description', 'Sovelluksen kehittämiseen ja muuttamiseen.', 'For building and changing the application.', '用于构建和修改应用程序。', '用於建構及修改應用程式。', 'Public First Run label.'),
  ('environment_testing', 'Testaus', 'Testing', '测试', '測試', 'Public First Run label.'),
  ('environment_testing_description', 'Devausta vastaavaan testaukseen.', 'For testing in a development-like environment.', '用于类似开发环境的测试。', '用於類似開發環境的測試。', 'Public First Run label.'),
  ('environment_qa', 'QA', 'QA', 'QA', 'QA', 'Public First Run label.'),
  ('environment_qa_description', 'Laadunvarmistukseen ja julkaisujen tarkistukseen.', 'For quality assurance and release verification.', '用于质量保证和发布验证。', '用於品質保證及發佈驗證。', 'Public First Run label.'),
  ('environment_production', 'Tuotanto', 'Production', '生产', '正式環境', 'Public First Run label.'),
  ('environment_production_description', 'Oikeille käyttäjille ja tuotantodatalle.', 'For real users and live data.', '用于真实用户和正式数据。', '用於真實使用者及正式資料。', 'Public First Run label.'),
  ('first_run_verification_legend', 'Kirjautumisen varmennus', 'Sign-in verification', '登录验证', '登入驗證', 'Public First Run label.'),
  ('verification_none', 'Ei lisävarmennusta', 'No additional verification', '无额外验证', '不作額外驗證', 'Public First Run label.'),
  ('verification_none_description', 'Kirjaudu vain käyttäjätunnuksella ja salasanalla.', 'Sign in with username and password only.', '仅使用用户名和密码登录。', '只使用使用者名稱及密碼登入。', 'Public First Run label.'),
  ('verification_fixed_pin', 'Kiinteä PIN', 'Fixed PIN', '固定 PIN', '固定 PIN', 'Public First Run label.'),
  ('verification_fixed_pin_description', 'Käytä samaa yksityistä 4–8 numeron PIN-koodia jokaisella kirjautumisella.', 'Use the same private 4–8 digit PIN at every sign-in.', '每次登录都使用同一个私密的 4–8 位数字 PIN。', '每次登入都使用同一個私密的 4–8 位數字 PIN。', 'Public First Run label.'),
  ('verification_authenticator', 'Autentikaattorisovellus', 'Authenticator app', '身份验证器应用', '驗證器應用程式', 'Public First Run label.'),
  ('verification_authenticator_description', 'Toimii standardia TOTP:tä tukevilla sovelluksilla, myös Google Authenticatorilla.', 'Works with standard TOTP apps, including Google Authenticator.', '适用于标准 TOTP 应用，包括 Google Authenticator。', '適用於標準 TOTP 應用程式，包括 Google Authenticator。', 'Public First Run label.'),
  ('verification_email', 'Sähköposti', 'Email', '电子邮件', '電郵', 'Public First Run label.'),
  ('verification_email_description', 'Lähettää kertakäyttökoodin Postmarkin kautta. Vaatii ilmaisen ulkoisen Postmark-tilin.', 'Sends a one-time code through Postmark. Requires a free external Postmark account.', '通过 Postmark 发送一次性代码。需要免费的外部 Postmark 账户。', '透過 Postmark 傳送一次性驗證碼。需要免費的外部 Postmark 帳戶。', 'Public First Run label.'),
  ('fixed_pin', 'Kiinteä PIN', 'Fixed PIN', '固定 PIN', '固定 PIN', 'Public First Run label.'),
  ('confirm_fixed_pin', 'Vahvista kiinteä PIN', 'Confirm fixed PIN', '确认固定 PIN', '確認固定 PIN', 'Public First Run label.'),
  ('authenticator_setup_key', 'Lisää tämä käyttöönottoavain autentikaattorisovellukseesi:', 'Add this setup key to your authenticator app:', '将此设置密钥添加到身份验证器应用中：', '將此設定密鑰加入驗證器應用程式：', 'Public First Run label.'),
  ('authenticator_confirmation_code', 'Vahvista käyttöönotto syöttämällä nykyinen 6-numeroinen koodi', 'Enter the current 6-digit code to confirm setup', '输入当前的 6 位代码以确认设置', '輸入目前的 6 位驗證碼以確認設定', 'Public First Run label.'),
  ('verification_fixed_pin_prompt', 'Syötä kiinteä PIN-koodisi.', 'Enter your fixed PIN.', '输入固定 PIN。', '輸入固定 PIN。', 'Public login verification prompt.'),
  ('verification_authenticator_prompt', 'Syötä autentikaattorisovelluksen nykyinen koodi.', 'Enter the current code from your authenticator app.', '输入身份验证器应用中的当前代码。', '輸入驗證器應用程式中的目前驗證碼。', 'Public login verification prompt.'),
  ('verification_email_prompt', 'Vahvistuskoodi lähetetty: $site_name', 'Verification code sent: $site_name', '验证代码已发送：$site_name', '驗證碼已傳送：$site_name', 'Public login verification prompt.'),
  ('first_run_environment_invalid', 'Valitse ympäristö.', 'Choose an environment.', '请选择环境。', '請選擇環境。', 'Public First Run validation label.'),
  ('first_run_verification_invalid', 'Valitse kirjautumisen varmennustapa.', 'Choose a sign-in verification method.', '请选择登录验证方式。', '請選擇登入驗證方式。', 'Public First Run validation label.'),
  ('first_run_fixed_pin_invalid', 'Käytä kiinteässä PIN-koodissa 4–8 numeroa.', 'Use 4–8 digits for the fixed PIN.', '固定 PIN 需使用 4–8 位数字。', '固定 PIN 需使用 4–8 位數字。', 'Public First Run validation label.'),
  ('first_run_fixed_pin_mismatch', 'Kiinteät PIN-koodit eivät täsmää.', 'The fixed PIN values do not match.', '两次输入的固定 PIN 不一致。', '兩次輸入的固定 PIN 不一致。', 'Public First Run validation label.'),
  ('first_run_totp_invalid', 'Vahvista autentikaattorin käyttöönotto kelvollisella nykyisellä koodilla.', 'Confirm the authenticator setup with a valid current code.', '请使用有效的当前代码确认身份验证器设置。', '請使用有效的目前驗證碼確認驗證器設定。', 'Public First Run validation label.'),
  ('first_run_postmark_required', 'Sähköpostivarmennus vaatii suojattuun ympäristötiedostoon POSTMARK_API_KEY- ja EMAIL_FROM_ADDRESS-arvot.', 'Email verification requires POSTMARK_API_KEY and EMAIL_FROM_ADDRESS in the protected environment file.', '电子邮件验证需要在受保护的环境文件中设置 POSTMARK_API_KEY 和 EMAIL_FROM_ADDRESS。', '電郵驗證需要在受保護的環境檔案中設定 POSTMARK_API_KEY 及 EMAIL_FROM_ADDRESS。', 'Public First Run validation label.')
ON CONFLICT (lang_key) DO UPDATE
SET fi = EXCLUDED.fi,
    en = EXCLUDED.en,
    ch = EXCLUDED.ch,
    yue = EXCLUDED.yue,
    updated = now(),
    creation_spec = EXCLUDED.creation_spec;

-- Field labels for the canonical language registry and its normalized values.
-- Seed these before derived search labels so the fresh installation never
-- needs a page-load AI request for the new administration fields.
INSERT INTO public.system_lang_keys (lang_key, fi, en, ch, yue, creation_spec) VALUES
  ('site_settings', 'Sivustoasetukset', 'Site settings', '站点设置', '網站設定', 'Admin navigation group for site-wide settings.'),
  ('site_languages', 'Sivuston kielet', 'Site languages', '站点语言', '網站語言', 'Admin view for the canonical site-language registry.'),
  ('site_languages_description', 'Valitse sivuston kielet, yksi oletuskieli, selkeät varakielet ja julkisessa kielivalitsimessa näkyvät tarkistetut kielet.', 'Choose the site languages, one default, explicit fallbacks, and which reviewed languages may appear publicly.', '选择站点语言、一个默认语言、明确的后备语言，以及可在公共语言选择器中显示的已审核语言。', '選擇網站語言、一個預設語言、明確嘅後備語言，同埋可以喺公開語言選擇器顯示嘅已審核語言。', 'Explanation above the administrator-owned site-language registry.'),
  ('language', 'Kieli', 'Language', '语言', '語言', 'Column heading in the site-language registry.'),
  ('default_language', 'Oletuskieli', 'Default language', '默认语言', '預設語言', 'The one root language used by the site.'),
  ('fallback_language', 'Varakieli', 'Fallback language', '后备语言', '後備語言', 'Explicit fallback used when a translation is unavailable.'),
  ('translation_coverage', 'Käännösten kattavuus', 'Translation coverage', '翻译覆盖率', '翻譯覆蓋程度', 'Coverage status shown in the site-language registry.'),
  ('public_selector', 'Julkinen kielivalitsin', 'Public language selector', '公共语言选择器', '公開語言選擇器', 'Whether an approved language may appear in the public selector.'),
  ('save', 'Tallenna', 'Save', '保存', '儲存', 'Shared save action.'),
  ('saving', 'Tallennetaan…', 'Saving…', '正在保存…', '儲存緊…', 'Progress copy while site-language settings are saved.'),
  ('settings_saved', 'Asetukset tallennettu.', 'Settings saved.', '设置已保存。', '設定已儲存。', 'Confirmation after settings are saved.'),
  ('save_failed', 'Tallennus epäonnistui.', 'Save failed.', '保存失败。', '儲存失敗。', 'Safe generic failure copy for a settings update.'),
  ('load_failed', 'Lataus epäonnistui.', 'Loading failed.', '加载失败。', '載入失敗。', 'Safe generic failure copy for a settings view load.'),
  ('language_code', 'Kielikoodi', 'Language code', '语言代码', '語言代碼', 'Canonical language registry field.'),
  ('english_name', 'Englanninkielinen nimi', 'English name', '英文名称', '英文名稱', 'Canonical language registry field.'),
  ('native_name', 'Omankielinen nimi', 'Native name', '本地名称', '本地名稱', 'Canonical language registry field.'),
  ('script_code', 'Kirjoitusjärjestelmän koodi', 'Script code', '文字代码', '文字代碼', 'Canonical language registry field.'),
  ('region_code', 'Aluekoodi', 'Region code', '地区代码', '地區代碼', 'Canonical language registry field.'),
  ('is_enabled', 'Käytössä sivustolla', 'Enabled on site', '在网站上启用', '在網站上啟用', 'Canonical language registry field.'),
  ('fallback_language_code', 'Varakieli', 'Fallback language', '后备语言', '後備語言', 'Canonical language registry field.'),
  ('coverage_status', 'Käännöskattavuus', 'Translation coverage', '翻译覆盖率', '翻譯覆蓋率', 'Canonical language registry field.'),
  ('review_status', 'Tarkistustila', 'Review status', '审核状态', '審核狀態', 'Canonical language registry field.'),
  ('public_selector_ready', 'Valmis kielivalitsimeen', 'Ready for language selector', '可用于语言选择器', '可用於語言選擇器', 'Canonical language registry field.'),
  ('translation', 'Käännös', 'Translation', '翻译', '翻譯', 'Normalized translation field.'),
  ('source_kind', 'Käännöksen alkuperä', 'Translation source', '翻译来源', '翻譯來源', 'Normalized translation field.')
ON CONFLICT (lang_key) DO NOTHING;

INSERT INTO public.system_lang_keys (lang_key, fi, en, ch, yue, creation_spec) VALUES
  ('external_embedding_allowed', 'Sallittu ulkoiseen embeddingiin', 'Allowed for external embeddings', '允许用于外部嵌入', '允許用於外部嵌入', 'Per-field administrator choice for the configured external embedding provider.'),
  ('external_embedding_enabled', 'Ulkoiset embeddingit käytössä', 'External embeddings enabled', '已启用外部嵌入', '已啟用外部嵌入', 'Per-table administrator switch for the configured external embedding provider.'),
  ('external_embedding_policy_configured', 'Embedding-kenttävalinta määritetty', 'Embedding field policy configured', '已配置嵌入字段策略', '已設定嵌入欄位政策', 'Technical marker showing that the administrator has saved an explicit field selection.'),
  ('generation', 'Sukupolvi', 'Generation', '生成版本', '產生版本', 'Content-free embedding refresh queue field.'),
  ('attempt_count', 'Yritysten määrä', 'Attempt count', '尝试次数', '嘗試次數', 'Content-free embedding refresh queue field.'),
  ('available_at', 'Käsiteltävissä', 'Available at', '可处理时间', '可處理時間', 'Content-free embedding refresh queue field.'),
  ('lease_token', 'Työvarauksen tunniste', 'Lease token', '租约令牌', '租約權杖', 'Content-free embedding refresh queue field.'),
  ('lease_expires_at', 'Työvaraus päättyy', 'Lease expires at', '租约到期时间', '租約到期時間', 'Content-free embedding refresh queue field.'),
  ('last_error_code', 'Viimeisin virhekoodi', 'Last error code', '最后错误代码', '最後錯誤代碼', 'Content-free embedding refresh queue field.'),
  ('embedding_external_fields', 'Ulkoiseen embedding-palveluun lähetettävät kentät', 'Fields sent to the external embedding provider', '发送到外部嵌入服务的字段', '傳送到外部嵌入服務嘅欄位', 'Admin label for selecting technically eligible dataset fields for the configured external embedding provider.'),
  ('embedding_enable_dataset', 'Salli ulkoiset embeddingit tälle taululle', 'Enable external embeddings for this table', '为此表启用外部嵌入', '為此資料表啟用外部嵌入', 'Admin switch that enables external embedding processing for one public-schema dataset.'),
  ('embedding_external_warning', 'Kun taulu otetaan käyttöön, sen teknisesti sopivat tekstikentät ovat aluksi valittuina. Poista valinta kentistä, joita et halua lähettää määritetylle ulkoiselle embedding-palvelulle. Restricted-skeeman kenttiä ei voi valita tässä.', 'When a table is enabled, its technically eligible text fields are initially selected. Clear any fields you do not want sent to the configured external embedding provider. Restricted-schema fields cannot be selected here.', '启用表后，技术上适用的文本字段将默认被选中。请取消选择不希望发送到已配置外部嵌入服务的字段。此处无法选择受限架构中的字段。', '啟用資料表後，技術上適用嘅文字欄位會預設揀選。請取消揀選唔想傳送到已設定外部嵌入服務嘅欄位。受限制綱要嘅欄位無法喺呢度揀選。', 'Explanation beside the administrator-owned table and field policy for external embedding generation.'),
  ('embedding_save_field_policy', 'Tallenna embedding-asetukset', 'Save embedding settings', '保存嵌入设置', '儲存嵌入設定', 'Admin action that saves the table switch and explicit field selection.'),
  ('embedding_field_policy_saved', 'Embedding-asetukset tallennettu ja päivitys jonotettu', 'Embedding settings saved and refresh queued', '嵌入设置已保存，刷新已排队', '嵌入設定已儲存，重新整理已排程', 'Confirmation after enabled embedding settings are saved and refresh work is queued.')
ON CONFLICT (lang_key) DO UPDATE
SET fi = EXCLUDED.fi,
    en = EXCLUDED.en,
    ch = EXCLUDED.ch,
    yue = EXCLUDED.yue,
    updated = now(),
    creation_spec = EXCLUDED.creation_spec;

-- Filter inputs derive predictable labels from their already translated field
-- name. Existing hand-written labels (including the four example apps) win.
INSERT INTO public.system_lang_keys (lang_key, fi, en, ch, yue, creation_spec)
SELECT 'search_for_' || base.lang_key,
       'Hae: ' || base.fi,
       'Search: ' || base.en,
       '搜索：' || base.ch,
       '搜尋：' || base.yue,
       'public fixture metadata seed'
FROM (
    SELECT DISTINCT COALESCE(NULLIF(details.lang_key, ''), details.column_name) AS lang_key
    FROM public.system_column_details details
) required
JOIN public.system_lang_keys base ON base.lang_key = required.lang_key
WHERE NOT EXISTS (
    SELECT 1
    FROM public.system_lang_keys existing
    WHERE existing.lang_key = 'search_for_' || base.lang_key
);

-- Every registered public dataset receives stable page-title and global-search
-- labels from its translated table name, again preserving curated overrides.
INSERT INTO public.system_lang_keys (lang_key, fi, en, ch, yue, creation_spec)
SELECT derived.lang_key,
       derived.fi,
       derived.en,
       derived.ch,
       derived.yue,
       'public fixture metadata seed'
FROM (
    SELECT 'search_for_' || tables.table_name AS lang_key,
           'Hae: ' || base.fi AS fi,
           'Search: ' || base.en AS en,
           '搜索：' || COALESCE(NULLIF(base.ch, ''), base.en) AS ch,
           '搜尋：' || COALESCE(NULLIF(base.yue, ''), NULLIF(base.ch, ''), base.en) AS yue
    FROM public.system_db_tables tables
    JOIN public.system_lang_keys base ON base.lang_key = tables.table_name
    UNION ALL
    SELECT tables.table_name || '_front_page' AS lang_key,
           base.fi AS fi,
           base.en AS en,
           COALESCE(NULLIF(base.ch, ''), base.en) AS ch,
           COALESCE(NULLIF(base.yue, ''), NULLIF(base.ch, ''), base.en) AS yue
    FROM public.system_db_tables tables
    JOIN public.system_lang_keys base ON base.lang_key = tables.table_name
) derived
WHERE NOT EXISTS (
    SELECT 1
    FROM public.system_lang_keys existing
    WHERE existing.lang_key = derived.lang_key
);

-- Fresh installs receive exactly the same five-locale registry as an upgraded
-- database. Only semantically proven legacy values are copied. In particular,
-- Cantonese yue text is not relabelled as reviewed Hong Kong Chinese (zh-HK).
INSERT INTO public.system_languages (
    language_code,
    english_name,
    native_name,
    script_code,
    region_code,
    is_enabled,
    is_default,
    fallback_language_code,
    coverage_status,
    review_status,
    public_selector_ready,
    sort_order
) VALUES
  ('en',    'English',                              'English',              'Latn', NULL, TRUE,  TRUE,  NULL, 'complete',    'approved',     TRUE,   10),
  ('fi',    'Finnish',                              'Suomi',                'Latn', NULL, TRUE,  FALSE, 'en', 'complete',    'approved',     TRUE,   20),
  ('zh-CN', 'Chinese (Simplified, Mainland China)', '简体中文（中国大陆）',   'Hans', 'CN', FALSE, FALSE, 'en', 'partial',     'needs_review', FALSE,  30),
  ('zh-TW', 'Chinese (Traditional, Taiwan)',        '繁體中文（台灣）',     'Hant', 'TW', FALSE, FALSE, 'en', 'not_started', 'unreviewed',   FALSE,  40),
  ('zh-HK', 'Chinese (Traditional, Hong Kong)',     '繁體中文（香港）',     'Hant', 'HK', FALSE, FALSE, 'en', 'not_started', 'unreviewed',   FALSE,  50)
ON CONFLICT (language_code) DO NOTHING;

WITH legacy_translations AS (
    SELECT source.id AS lang_key_id,
           'en'::TEXT AS language_code,
           source.en AS translation,
           'legacy_en'::TEXT AS source_kind,
           'approved'::TEXT AS review_status
    FROM public.system_lang_keys AS source
    UNION ALL
    SELECT source.id, 'fi'::TEXT, source.fi, 'legacy_fi'::TEXT, 'approved'::TEXT
    FROM public.system_lang_keys AS source
    UNION ALL
    SELECT source.id, 'zh-CN'::TEXT, source.ch, 'legacy_ch'::TEXT, 'needs_review'::TEXT
    FROM public.system_lang_keys AS source
)
INSERT INTO public.system_lang_key_translations (
    lang_key_id,
    language_code,
    translation,
    source_kind,
    review_status
)
SELECT source.lang_key_id,
       source.language_code,
       source.translation,
       source.source_kind,
       source.review_status
FROM legacy_translations AS source
WHERE NULLIF(btrim(source.translation), '') IS NOT NULL
ON CONFLICT (lang_key_id, language_code) DO NOTHING;

-- The two language-model table labels are authored static navigation copy,
-- not candidates for runtime AI fallback. Seed every canonical locale row;
-- the legacy columns above remain available during the compatibility period.
WITH authored_translations(lang_key, language_code, translation, review_status) AS (
    VALUES
        ('system_languages', 'en', 'Languages', 'approved'),
        ('system_languages', 'fi', 'Kielet', 'approved'),
        ('system_languages', 'zh-CN', '语言', 'needs_review'),
        ('system_languages', 'zh-TW', '語言', 'needs_review'),
        ('system_languages', 'zh-HK', '語言', 'needs_review'),
        ('system_lang_key_translations', 'en', 'Language key translations', 'approved'),
        ('system_lang_key_translations', 'fi', 'Kieliavainten käännökset', 'approved'),
        ('system_lang_key_translations', 'zh-CN', '语言键翻译', 'needs_review'),
        ('system_lang_key_translations', 'zh-TW', '語言鍵翻譯', 'needs_review'),
        ('system_lang_key_translations', 'zh-HK', '語言鍵翻譯', 'needs_review'),
        ('system_column_field_sets', 'en', 'Field collections', 'approved'),
        ('system_column_field_sets', 'fi', 'Kenttäkokoelmat', 'approved'),
        ('system_column_field_sets', 'zh-CN', '字段集合', 'needs_review'),
        ('system_column_field_sets', 'zh-TW', '欄位集合', 'needs_review'),
        ('system_column_field_sets', 'zh-HK', '欄位集合', 'needs_review'),
        ('system_column_field_set_members', 'en', 'Field collection members', 'approved'),
        ('system_column_field_set_members', 'fi', 'Kenttäkokoelmien kentät', 'approved'),
        ('system_column_field_set_members', 'zh-CN', '字段集合成员', 'needs_review'),
        ('system_column_field_set_members', 'zh-TW', '欄位集合成員', 'needs_review'),
        ('system_column_field_set_members', 'zh-HK', '欄位集合成員', 'needs_review'),
        ('system_view_field_set_assignments', 'en', 'View field assignments', 'approved'),
        ('system_view_field_set_assignments', 'fi', 'Näkymien kenttäkokoelmat', 'approved'),
        ('system_view_field_set_assignments', 'zh-CN', '视图字段分配', 'needs_review'),
        ('system_view_field_set_assignments', 'zh-TW', '檢視欄位指派', 'needs_review'),
        ('system_view_field_set_assignments', 'zh-HK', '檢視欄位指派', 'needs_review'),
        ('edit_site_field_default', 'en', 'Edit site default', 'approved'),
        ('edit_site_field_default', 'fi', 'Muokkaa sivuston oletusta', 'approved'),
        ('edit_site_field_default', 'zh-CN', '编辑站点默认字段', 'needs_review'),
        ('edit_site_field_default', 'zh-TW', '編輯網站預設欄位', 'needs_review'),
        ('edit_site_field_default', 'zh-HK', '編輯網站預設欄位', 'needs_review'),
        ('edit_personal_field_selection', 'en', 'Return to personal selection', 'approved'),
        ('edit_personal_field_selection', 'fi', 'Palaa omaan valintaan', 'approved'),
        ('edit_personal_field_selection', 'zh-CN', '返回个人字段选择', 'needs_review'),
        ('edit_personal_field_selection', 'zh-TW', '返回個人欄位選擇', 'needs_review'),
        ('edit_personal_field_selection', 'zh-HK', '返回個人欄位選擇', 'needs_review'),
        ('return_to_site_default', 'en', 'Return to site default', 'approved'),
        ('return_to_site_default', 'fi', 'Palaa sivuston oletukseen', 'approved'),
        ('return_to_site_default', 'zh-CN', '继承站点默认值', 'needs_review'),
        ('return_to_site_default', 'zh-TW', '使用網站預設值', 'needs_review'),
        ('return_to_site_default', 'zh-HK', '使用網站預設值', 'needs_review'),
        ('site_default_restored', 'en', 'Site default restored', 'approved'),
        ('site_default_restored', 'fi', 'Sivuston oletus palautettu', 'approved'),
        ('site_default_restored', 'zh-CN', '已恢复站点默认值', 'needs_review'),
        ('site_default_restored', 'zh-TW', '已恢復網站預設值', 'needs_review'),
        ('site_default_restored', 'zh-HK', '已恢復網站預設值', 'needs_review'),
        ('shared', 'en', 'Shared', 'approved'),
        ('shared', 'fi', 'Jaettu', 'approved'),
        ('shared', 'zh-CN', '共享', 'needs_review'),
        ('shared', 'zh-TW', '共用', 'needs_review'),
        ('shared', 'zh-HK', '共用', 'needs_review'),
        ('field_set_fields_placeholder', 'en', 'Fields in collection', 'approved'),
        ('field_set_fields_placeholder', 'fi', 'Kentät kenttäjoukossa', 'approved'),
        ('field_set_fields_placeholder', 'zh-CN', '字段集中的字段', 'needs_review'),
        ('field_set_fields_placeholder', 'zh-TW', '欄位集中的欄位', 'needs_review'),
        ('field_set_fields_placeholder', 'zh-HK', '欄位集中的欄位', 'needs_review'),
        ('fields_selected', 'en', 'fields selected', 'approved'),
        ('fields_selected', 'fi', 'kenttää valittu', 'approved'),
        ('fields_selected', 'zh-CN', '个字段已选择', 'needs_review'),
        ('fields_selected', 'zh-TW', '個欄位已選取', 'needs_review'),
        ('fields_selected', 'zh-HK', '個欄位已選取', 'needs_review'),
        ('filter_mode_exact_value', 'en', 'Exact value', 'approved'),
        ('filter_mode_exact_value', 'fi', 'Tarkka arvo', 'approved'),
        ('filter_mode_exact_value', 'zh-CN', '精确值', 'needs_review'),
        ('filter_mode_exact_value', 'zh-TW', '精確值', 'needs_review'),
        ('filter_mode_exact_value', 'zh-HK', '精確值', 'needs_review'),
        ('filter_mode_range', 'en', 'Range', 'approved'),
        ('filter_mode_range', 'fi', 'Arvoväli', 'approved'),
        ('filter_mode_range', 'zh-CN', '范围', 'needs_review'),
        ('filter_mode_range', 'zh-TW', '範圍', 'needs_review'),
        ('filter_mode_range', 'zh-HK', '範圍', 'needs_review'),
        ('filter_mode_condition_expression', 'en', 'Condition or expression', 'approved'),
        ('filter_mode_condition_expression', 'fi', 'Ehto tai lauseke', 'approved'),
        ('filter_mode_condition_expression', 'zh-CN', '条件或表达式', 'needs_review'),
        ('filter_mode_condition_expression', 'zh-TW', '條件或運算式', 'needs_review'),
        ('filter_mode_condition_expression', 'zh-HK', '條件或運算式', 'needs_review'),
        ('previous_image', 'en', 'Previous image', 'approved'),
        ('previous_image', 'fi', 'Edellinen kuva', 'approved'),
        ('previous_image', 'zh-CN', '上一张图片', 'needs_review'),
        ('previous_image', 'zh-TW', '上一張圖片', 'needs_review'),
        ('previous_image', 'zh-HK', '上一張圖片', 'needs_review'),
        ('next_image', 'en', 'Next image', 'approved'),
        ('next_image', 'fi', 'Seuraava kuva', 'approved'),
        ('next_image', 'zh-CN', '下一张图片', 'needs_review'),
        ('next_image', 'zh-TW', '下一張圖片', 'needs_review'),
        ('next_image', 'zh-HK', '下一張圖片', 'needs_review'),
        ('previous_row', 'en', 'Previous record', 'approved'),
        ('previous_row', 'fi', 'Edellinen tietue', 'approved'),
        ('previous_row', 'zh-CN', '上一条记录', 'needs_review'),
        ('previous_row', 'zh-TW', '上一筆資料', 'needs_review'),
        ('previous_row', 'zh-HK', '上一筆資料', 'needs_review'),
        ('next_row', 'en', 'Next record', 'approved'),
        ('next_row', 'fi', 'Seuraava tietue', 'approved'),
        ('next_row', 'zh-CN', '下一条记录', 'needs_review'),
        ('next_row', 'zh-TW', '下一筆資料', 'needs_review'),
        ('next_row', 'zh-HK', '下一筆資料', 'needs_review'),
        ('open_article', 'en', 'Open article', 'approved'),
        ('open_article', 'fi', 'Avaa artikkeli', 'approved'),
        ('open_article', 'zh-CN', '打开文章', 'needs_review'),
        ('open_article', 'zh-TW', '開啟文章', 'needs_review'),
        ('open_article', 'zh-HK', '開啟文章', 'needs_review'),
        ('article_records', 'en', 'Article records', 'approved'),
        ('article_records', 'fi', 'Artikkelin tietueet', 'approved'),
        ('article_records', 'zh-CN', '文章记录', 'needs_review'),
        ('article_records', 'zh-TW', '文章資料', 'needs_review'),
        ('article_records', 'zh-HK', '文章資料', 'needs_review')
), resolved AS (
    SELECT
        keys.id AS lang_key_id,
        authored.language_code,
        authored.translation,
        authored.review_status
    FROM authored_translations AS authored
    JOIN public.system_lang_keys AS keys
      ON keys.lang_key = authored.lang_key
)
INSERT INTO public.system_lang_key_translations (
    lang_key_id,
    language_code,
    translation,
    source_kind,
    review_status
)
SELECT
    resolved.lang_key_id,
    resolved.language_code,
    resolved.translation,
    'manual',
    resolved.review_status
FROM resolved
ON CONFLICT (lang_key_id, language_code) DO UPDATE
SET translation = EXCLUDED.translation,
    source_kind = EXCLUDED.source_kind,
    review_status = EXCLUDED.review_status,
    updated = now();

INSERT INTO public.system_lang_key_sources (
    lang_key_id, source_type, source_high, source_low, usage_explanation, last_seen
)
SELECT keys.id,
       'code',
       'frontend/core_components/filterbar/filter_list/column_view_preset_builder.js',
       '',
       'Per-view personal and site-default field collection controls.',
       CURRENT_DATE
FROM public.system_lang_keys AS keys
WHERE keys.lang_key IN (
    'edit_site_field_default',
    'edit_personal_field_selection',
    'return_to_site_default',
    'site_default_restored',
    'shared',
    'field_set_fields_placeholder',
    'fields_selected'
)
ON CONFLICT (lang_key_id, source_type, source_high) DO UPDATE
SET source_low = EXCLUDED.source_low,
    usage_explanation = EXCLUDED.usage_explanation,
    last_seen = CURRENT_DATE;
