-- runtime.schema.sql
-- Defines the public-safe tables required before Filterest serves its first authenticated page.
-- Bridges the reduced essential fixture schema and backend startup/browser runtime dependencies.
-- Exists so generated siblings fail during bootstrap instead of returning recurring HTTP 500 errors.

ALTER TABLE restricted.users_restricted
    ADD COLUMN IF NOT EXISTS authentication_generation bigint NOT NULL DEFAULT 1;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'users_restricted_authentication_generation_positive'
          AND conrelid = 'restricted.users_restricted'::regclass
    ) THEN
        ALTER TABLE restricted.users_restricted
            ADD CONSTRAINT users_restricted_authentication_generation_positive
            CHECK (authentication_generation >= 1);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.system_table_views (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now(),
    kuvaus character varying(255),
    name character varying(128),
    status character varying(255),
    view_key text NOT NULL UNIQUE
        CHECK (view_key ~ '^[a-z][a-z0-9_]{0,63}$')
);

CREATE TABLE IF NOT EXISTS public.system_child_tab_config (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_table text NOT NULL,
    tab_key text NOT NULL,
    tab_order integer NOT NULL DEFAULT 0,
    hidden boolean NOT NULL DEFAULT false,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (parent_table, tab_key)
);

CREATE OR REPLACE FUNCTION public.set_system_child_tab_config_updated_timestamp()
RETURNS trigger AS $$
BEGIN
    NEW.updated = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_system_child_tab_config_timestamp
    ON public.system_child_tab_config;
CREATE TRIGGER update_system_child_tab_config_timestamp
BEFORE UPDATE ON public.system_child_tab_config
FOR EACH ROW EXECUTE FUNCTION public.set_system_child_tab_config_updated_timestamp();

CREATE TABLE IF NOT EXISTS public.system_comments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name text NOT NULL,
    row_id integer NOT NULL,
    comment_text text NOT NULL
        CHECK (char_length(comment_text) BETWEEN 1 AND 5000),
    created_by integer REFERENCES public.system_users(id) ON DELETE SET NULL,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_system_comments_lookup
    ON public.system_comments (table_name, row_id, created DESC);

CREATE OR REPLACE FUNCTION public.set_system_comments_updated_timestamp()
RETURNS trigger AS $$
BEGIN
    NEW.updated = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_system_comments_timestamp
    ON public.system_comments;
CREATE TRIGGER update_system_comments_timestamp
BEFORE UPDATE ON public.system_comments
FOR EACH ROW EXECUTE FUNCTION public.set_system_comments_updated_timestamp();

CREATE TABLE IF NOT EXISTS public.system_row_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9][a-z0-9_-]{0,63}$'),
    title jsonb NOT NULL CHECK (jsonb_typeof(title) = 'object' AND title <> '{}'::jsonb),
    description jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(description) = 'object'),
    sort_order integer NOT NULL DEFAULT 0 CHECK (sort_order BETWEEN -100000 AND 100000),
    enabled boolean NOT NULL DEFAULT true,
    created_by bigint REFERENCES public.system_users(id) ON DELETE SET NULL,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.system_row_group_memberships (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id bigint NOT NULL REFERENCES public.system_row_groups(id) ON DELETE CASCADE,
    table_uid integer NOT NULL REFERENCES public.system_db_tables(table_uid) ON DELETE CASCADE,
    row_id bigint NOT NULL CHECK (row_id > 0),
    target_stable_key text,
    created_by bigint REFERENCES public.system_users(id) ON DELETE SET NULL,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_system_row_group_membership UNIQUE (group_id, table_uid, row_id),
    CONSTRAINT ck_system_row_group_memberships_stable_key
        CHECK (target_stable_key IS NULL OR char_length(btrim(target_stable_key)) BETWEEN 1 AND 500)
);

CREATE INDEX IF NOT EXISTS idx_system_row_group_memberships_row
    ON public.system_row_group_memberships (table_uid, row_id, group_id);
CREATE INDEX IF NOT EXISTS idx_system_row_group_memberships_stable_key
    ON public.system_row_group_memberships (table_uid, target_stable_key)
    WHERE target_stable_key IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_system_row_group_memberships_stable_key
    ON public.system_row_group_memberships (group_id, table_uid, target_stable_key)
    WHERE target_stable_key IS NOT NULL;

CREATE OR REPLACE FUNCTION public.set_system_row_groups_updated_timestamp()
RETURNS trigger AS $$
BEGIN
    NEW.updated = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.set_system_row_group_memberships_updated_timestamp()
RETURNS trigger AS $$
BEGIN
    NEW.updated = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_system_row_groups_timestamp
    ON public.system_row_groups;
CREATE TRIGGER update_system_row_groups_timestamp
BEFORE UPDATE ON public.system_row_groups
FOR EACH ROW EXECUTE FUNCTION public.set_system_row_groups_updated_timestamp();

DROP TRIGGER IF EXISTS update_system_row_group_memberships_timestamp
    ON public.system_row_group_memberships;
CREATE TRIGGER update_system_row_group_memberships_timestamp
BEFORE UPDATE ON public.system_row_group_memberships
FOR EACH ROW EXECUTE FUNCTION public.set_system_row_group_memberships_updated_timestamp();

CREATE TABLE IF NOT EXISTS public.system_column_field_sets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_uid integer NOT NULL REFERENCES public.system_db_tables(table_uid) ON DELETE CASCADE,
    owner_user_id bigint REFERENCES public.system_users(id) ON DELETE CASCADE,
    name text NOT NULL CHECK (char_length(btrim(name)) BETWEEN 1 AND 128),
    created_by bigint REFERENCES public.system_users(id) ON DELETE SET NULL,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT chk_system_column_field_sets_no_guest_owner
        CHECK (owner_user_id IS NULL OR owner_user_id <> 1),
    CONSTRAINT uq_system_column_field_sets_owner_name
        UNIQUE NULLS NOT DISTINCT (table_uid, owner_user_id, name),
    CONSTRAINT uq_system_column_field_sets_id_table UNIQUE (id, table_uid)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_system_column_details_table_column
    ON public.system_column_details (table_uid, column_uid);

CREATE TABLE IF NOT EXISTS public.system_column_field_set_members (
    field_set_id bigint NOT NULL,
    table_uid integer NOT NULL,
    column_uid integer NOT NULL,
    sort_order integer NOT NULL CHECK (sort_order > 0),
    column_width_px integer CHECK (column_width_px IS NULL OR column_width_px >= 0),
    PRIMARY KEY (field_set_id, column_uid),
    CONSTRAINT uq_system_column_field_set_member_order UNIQUE (field_set_id, sort_order),
    CONSTRAINT fk_system_column_field_set_members_set
        FOREIGN KEY (field_set_id, table_uid)
        REFERENCES public.system_column_field_sets(id, table_uid) ON DELETE CASCADE,
    CONSTRAINT fk_system_column_field_set_members_column
        FOREIGN KEY (table_uid, column_uid)
        REFERENCES public.system_column_details(table_uid, column_uid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.system_view_field_set_assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint REFERENCES public.system_users(id) ON DELETE CASCADE,
    table_uid integer NOT NULL REFERENCES public.system_db_tables(table_uid) ON DELETE CASCADE,
    view_id integer NOT NULL REFERENCES public.system_table_views(id) ON DELETE CASCADE,
    field_set_id bigint NOT NULL,
    created_by bigint REFERENCES public.system_users(id) ON DELETE SET NULL,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT chk_system_view_field_set_assignments_no_guest_user
        CHECK (user_id IS NULL OR user_id <> 1),
    CONSTRAINT uq_system_view_field_set_assignment
        UNIQUE NULLS NOT DISTINCT (user_id, table_uid, view_id),
    CONSTRAINT fk_system_view_field_set_assignment_set
        FOREIGN KEY (field_set_id, table_uid)
        REFERENCES public.system_column_field_sets(id, table_uid) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_system_column_field_sets_table_owner
    ON public.system_column_field_sets (table_uid, owner_user_id);
CREATE INDEX IF NOT EXISTS idx_system_view_field_set_assignments_lookup
    ON public.system_view_field_set_assignments (table_uid, view_id, user_id);

CREATE TABLE IF NOT EXISTS public.system_dataset_sort_defaults (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_uid integer NOT NULL REFERENCES public.system_db_tables(table_uid) ON DELETE CASCADE,
    user_id integer REFERENCES public.system_users(id) ON DELETE CASCADE,
    sort_column text NOT NULL CHECK (btrim(sort_column) <> ''),
    sort_direction text NOT NULL CHECK (sort_direction IN ('ASC', 'DESC')),
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE NULLS NOT DISTINCT (table_uid, user_id)
);

CREATE INDEX IF NOT EXISTS idx_system_dataset_sort_defaults_user
    ON public.system_dataset_sort_defaults (user_id, table_uid)
    WHERE user_id IS NOT NULL;

CREATE OR REPLACE FUNCTION public.set_system_dataset_sort_defaults_updated_timestamp()
RETURNS trigger AS $$
BEGIN
    NEW.updated = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_system_dataset_sort_defaults_timestamp
    ON public.system_dataset_sort_defaults;
CREATE TRIGGER update_system_dataset_sort_defaults_timestamp
BEFORE UPDATE ON public.system_dataset_sort_defaults
FOR EACH ROW EXECUTE FUNCTION public.set_system_dataset_sort_defaults_updated_timestamp();

CREATE TABLE IF NOT EXISTS public.system_dataset_media (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_uid integer NOT NULL REFERENCES public.system_db_tables(table_uid) ON DELETE CASCADE,
    media_role text NOT NULL CHECK (media_role IN ('cover', 'background')),
    storage_key text NOT NULL CHECK (btrim(storage_key) <> '' AND storage_key !~ '(^|/)\.\.(/|$)'),
    original_name text NOT NULL,
    mime_type text NOT NULL,
    alt_text jsonb NOT NULL DEFAULT '{}'::jsonb,
    focal_x numeric(5, 4) NOT NULL DEFAULT 0.5000 CHECK (focal_x BETWEEN 0 AND 1),
    focal_y numeric(5, 4) NOT NULL DEFAULT 0.5000 CHECK (focal_y BETWEEN 0 AND 1),
    variants jsonb NOT NULL DEFAULT '{}'::jsonb,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (table_uid, media_role)
);

CREATE INDEX IF NOT EXISTS idx_system_dataset_media_table_uid
    ON public.system_dataset_media (table_uid);

CREATE OR REPLACE FUNCTION public.set_system_dataset_media_updated_timestamp()
RETURNS trigger AS $$
BEGIN
    NEW.updated = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_system_dataset_media_timestamp
    ON public.system_dataset_media;
CREATE TRIGGER update_system_dataset_media_timestamp
BEFORE UPDATE ON public.system_dataset_media
FOR EACH ROW EXECUTE FUNCTION public.set_system_dataset_media_updated_timestamp();

CREATE TABLE IF NOT EXISTS public.system_db_table_aliases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_uid integer NOT NULL REFERENCES public.system_db_tables(table_uid) ON DELETE CASCADE,
    alias_slug text NOT NULL UNIQUE,
    is_primary boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_system_db_table_aliases_table_uid
    ON public.system_db_table_aliases (table_uid);

CREATE UNIQUE INDEX IF NOT EXISTS idx_system_db_table_aliases_one_primary_alias_per_table
    ON public.system_db_table_aliases (table_uid)
    WHERE is_primary IS TRUE AND is_active IS TRUE;

CREATE OR REPLACE FUNCTION public.set_system_db_table_aliases_updated_timestamp()
RETURNS trigger AS $$
BEGIN
    NEW.updated = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'set_system_db_table_aliases_updated'
    ) THEN
        CREATE TRIGGER set_system_db_table_aliases_updated
            BEFORE UPDATE ON public.system_db_table_aliases
            FOR EACH ROW EXECUTE FUNCTION public.set_system_db_table_aliases_updated_timestamp();
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'readeronly') THEN
        GRANT SELECT ON TABLE public.system_db_table_aliases TO readeronly;
    END IF;
END $$;

-- External embedding work is opt-in per dataset. The queue contains only row
-- identifiers and scheduling state; the worker reads field content later
-- through the administrator-owned allowlist.
ALTER TABLE public.system_column_details
    ADD COLUMN IF NOT EXISTS external_embedding_allowed BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.system_db_tables
    ADD COLUMN IF NOT EXISTS external_embedding_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS external_embedding_policy_configured BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS public.system_embedding_refresh_jobs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_uid        INTEGER NOT NULL REFERENCES public.system_db_tables(table_uid) ON DELETE CASCADE,
    row_id           BIGINT NOT NULL,
    generation       BIGINT NOT NULL DEFAULT 1,
    attempt_count    INTEGER NOT NULL DEFAULT 0,
    available_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    lease_token      TEXT NOT NULL DEFAULT '',
    lease_expires_at TIMESTAMPTZ,
    last_error_code  TEXT NOT NULL DEFAULT '',
    created          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_system_embedding_refresh_jobs_row UNIQUE (table_uid, row_id),
    CONSTRAINT ck_system_embedding_refresh_jobs_generation CHECK (generation >= 1),
    CONSTRAINT ck_system_embedding_refresh_jobs_attempt_count CHECK (attempt_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_system_embedding_refresh_jobs_claim
    ON public.system_embedding_refresh_jobs (available_at, lease_expires_at, id);

-- Keep fresh public installations on the same canonical UI-language model as
-- an existing database upgraded through 20260817000002. Runtime readers still
-- use the legacy wide columns during the compatibility phase; these tables are
-- the durable per-locale contract for the later runtime cutover.
CREATE TABLE IF NOT EXISTS public.system_languages (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code            TEXT        NOT NULL UNIQUE,
    english_name             TEXT        NOT NULL,
    native_name              TEXT        NOT NULL,
    script_code              TEXT        NOT NULL,
    region_code              TEXT,
    is_enabled               BOOLEAN     NOT NULL DEFAULT FALSE,
    is_default               BOOLEAN     NOT NULL DEFAULT FALSE,
    fallback_language_code   TEXT        REFERENCES public.system_languages(language_code) ON DELETE RESTRICT,
    coverage_status          TEXT        NOT NULL DEFAULT 'not_started',
    review_status            TEXT        NOT NULL DEFAULT 'unreviewed',
    public_selector_ready    BOOLEAN     NOT NULL DEFAULT FALSE,
    sort_order               INTEGER     NOT NULL DEFAULT 100,
    created                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_system_languages_code
        CHECK (language_code ~ '^[a-z]{2,3}(-[A-Z]{2})?$'),
    CONSTRAINT ck_system_languages_script
        CHECK (script_code ~ '^[A-Z][a-z]{3}$'),
    CONSTRAINT ck_system_languages_region
        CHECK (region_code IS NULL OR region_code ~ '^[A-Z]{2}$'),
    CONSTRAINT ck_system_languages_code_region_match
        CHECK (
            (region_code IS NULL AND language_code !~ '-')
            OR language_code = split_part(language_code, '-', 1) || '-' || region_code
        ),
    CONSTRAINT ck_system_languages_coverage
        CHECK (coverage_status IN ('not_started', 'partial', 'complete')),
    CONSTRAINT ck_system_languages_review
        CHECK (review_status IN ('unreviewed', 'needs_review', 'approved')),
    CONSTRAINT ck_system_languages_default_enabled
        CHECK (is_default IS FALSE OR is_enabled IS TRUE),
    CONSTRAINT ck_system_languages_fallback
        CHECK (
            (is_default IS TRUE AND fallback_language_code IS NULL)
            OR
            (
                is_default IS FALSE
                AND fallback_language_code IS NOT NULL
                AND fallback_language_code <> language_code
            )
        ),
    CONSTRAINT ck_system_languages_public_selector_gate
        CHECK (
            public_selector_ready IS FALSE
            OR (
                is_enabled IS TRUE
                AND coverage_status = 'complete'
                AND review_status = 'approved'
            )
        )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_system_languages_one_default
    ON public.system_languages (is_default)
    WHERE is_default IS TRUE;

CREATE TABLE IF NOT EXISTS public.system_lang_key_translations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lang_key_id       BIGINT      NOT NULL REFERENCES public.system_lang_keys(id) ON DELETE CASCADE,
    language_code     TEXT        NOT NULL REFERENCES public.system_languages(language_code) ON DELETE RESTRICT,
    translation       TEXT        NOT NULL CHECK (btrim(translation) <> ''),
    source_kind       TEXT        NOT NULL,
    review_status     TEXT        NOT NULL DEFAULT 'unreviewed',
    created           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated           TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_system_lang_key_translations_key_language
        UNIQUE (lang_key_id, language_code),
    CONSTRAINT ck_system_lang_key_translations_source
        CHECK (source_kind IN ('legacy_en', 'legacy_fi', 'legacy_ch', 'manual', 'import')),
    CONSTRAINT ck_system_lang_key_translations_review
        CHECK (review_status IN ('unreviewed', 'needs_review', 'approved'))
);

CREATE INDEX IF NOT EXISTS idx_system_lang_key_translations_language
    ON public.system_lang_key_translations (language_code, lang_key_id);

CREATE OR REPLACE FUNCTION public.set_system_languages_updated_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.set_system_lang_key_translations_updated_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'update_system_languages_timestamp'
          AND tgrelid = 'public.system_languages'::regclass
    ) THEN
        CREATE TRIGGER update_system_languages_timestamp
            BEFORE UPDATE ON public.system_languages
            FOR EACH ROW EXECUTE FUNCTION public.set_system_languages_updated_timestamp();
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'update_system_lang_key_translations_timestamp'
          AND tgrelid = 'public.system_lang_key_translations'::regclass
    ) THEN
        CREATE TRIGGER update_system_lang_key_translations_timestamp
            BEFORE UPDATE ON public.system_lang_key_translations
            FOR EACH ROW EXECUTE FUNCTION public.set_system_lang_key_translations_updated_timestamp();
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.system_about (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp with time zone NOT NULL DEFAULT now(),
    updated timestamp with time zone NOT NULL DEFAULT now(),
    title character varying,
    description text,
    predecessor_id integer,
    cached_image text,
    search_vector_simple tsvector,
    admin_approved boolean
);

CREATE TABLE IF NOT EXISTS public.ai_chat_conversations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.system_users(id) ON DELETE CASCADE,
    dataset character varying(255) NOT NULL,
    preview text NOT NULL DEFAULT '',
    messages jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_ai_chat_conversations_user_dataset
    ON public.ai_chat_conversations (user_id, dataset);
CREATE INDEX IF NOT EXISTS idx_ai_chat_conversations_user_id
    ON public.ai_chat_conversations (user_id);

CREATE TABLE IF NOT EXISTS public.system_db_version (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version character varying(20) NOT NULL,
    applied_at timestamp with time zone DEFAULT now(),
    description text,
    instance_id character varying(12) NOT NULL DEFAULT SUBSTRING(md5(random()::text) FROM 1 FOR 12)
);
