-- 20261005000001_add_row_actor_support.sql
-- Creates the support every content dataset's creator and owner columns rest on: the
-- actor marks that name those columns for good, the repair record every data step of
-- this release writes, the functions that add, constrain, register, read and check the
-- columns, and the triggers that keep the two internal tables writable only by their
-- owner role. Nothing in the application uses them yet.
-- Bridges the release's data file (000004), dataset creation and the public bootstrap
-- with one definition of an actor column, so the three cannot drift apart.
-- Exists because a column called owner_id says nothing by itself: the marks are the
-- lasting answer to which column holds a row's creator and owner, every protection
-- reads them, and the registry's owner setting is bound to them.
-- The file is schema only. Its one row is its own completion marker, which the public
-- bootstrap's acceptance block requires. Running it again changes nothing. WL58 stage 2
-- plan v14 (v13 sections 1.3-1.7 and 3.7) describes every part.
-- VERSION_DB: 9.10.0
-- VERSION_DB_OWNER: 20261005000099_record_database_release_9_10_0.sql
-- COMPLETION_MARKER: wl58_row_actor_support

-- 1. The repair record: what each data step changed, by identifier only, never a name.
-- No foreign keys, so the history survives a user's deletion.
CREATE TABLE IF NOT EXISTS public.system_data_repair_records (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migration   text        NOT NULL,
    table_name  text,
    row_id      text,
    column_name text,
    old_value   text,
    new_value   text,
    action      text        NOT NULL,
    detail      jsonb       NOT NULL DEFAULT '{}'::jsonb,
    recorded_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_system_data_repair_records_migration_action
    ON public.system_data_repair_records (migration, action, table_name);
COMMENT ON TABLE public.system_data_repair_records IS
    'Immutable record of what data migrations changed, by identifier only; visible to the table owner role alone.';

-- 2. The actor marks: which column holds each marked dataset's creator and owner.
-- Keyed by the registry id, which survives a dataset's rename; deleting the registry
-- row takes its marks with it, so a new dataset of the same name never inherits them.
CREATE TABLE IF NOT EXISTS public.system_row_actor_columns (
    table_id    bigint      NOT NULL REFERENCES public.system_db_tables(id) ON DELETE CASCADE,
    actor_role  text        NOT NULL CHECK (actor_role IN ('creator', 'owner')),
    column_name text        NOT NULL,
    marked_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (table_id, actor_role)
);
COMMENT ON TABLE public.system_row_actor_columns IS
    'Permanent marks naming each marked dataset''s creator and owner columns; written only by the table owner role.';

-- 3. Writes only by the owner role. The installation's roles may hold write rights on
-- every public table and their names vary, so the guard is a trigger, not a privilege:
-- only the table's owner, a member of it or a superuser passes. It runs with the
-- caller's rights. A registry deletion's cascade runs as the marks table's owner.
CREATE OR REPLACE FUNCTION public.app_owner_only_writes() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NOT pg_has_role(current_user,
         (SELECT relowner FROM pg_catalog.pg_class WHERE oid = TG_RELID), 'MEMBER') THEN
        RAISE EXCEPTION USING ERRCODE = 'insufficient_privilege',
            MESSAGE = format('only the owner role of %s may write it', TG_TABLE_NAME);
    END IF;
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END $$;

DROP TRIGGER IF EXISTS owner_only_writes ON public.system_row_actor_columns;
CREATE TRIGGER owner_only_writes
    BEFORE INSERT OR UPDATE OR DELETE ON public.system_row_actor_columns
    FOR EACH ROW EXECUTE FUNCTION public.app_owner_only_writes();
DROP TRIGGER IF EXISTS owner_only_truncate ON public.system_row_actor_columns;
CREATE TRIGGER owner_only_truncate
    BEFORE TRUNCATE ON public.system_row_actor_columns
    FOR EACH STATEMENT EXECUTE FUNCTION public.app_owner_only_writes();
DROP TRIGGER IF EXISTS owner_only_writes ON public.system_data_repair_records;
CREATE TRIGGER owner_only_writes
    BEFORE INSERT OR UPDATE OR DELETE ON public.system_data_repair_records
    FOR EACH ROW EXECUTE FUNCTION public.app_owner_only_writes();
DROP TRIGGER IF EXISTS owner_only_truncate ON public.system_data_repair_records;
CREATE TRIGGER owner_only_truncate
    BEFORE TRUNCATE ON public.system_data_repair_records
    FOR EACH STATEMENT EXECUTE FUNCTION public.app_owner_only_writes();

-- The repair record is read by administrators through the administrator connection
-- only. Row security hides its rows from every other role, whatever rights the
-- installation gave them; the start-up refuses a runtime role that bypasses it.
ALTER TABLE public.system_data_repair_records ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS repair_records_owner_role ON public.system_data_repair_records;
CREATE POLICY repair_records_owner_role ON public.system_data_repair_records
    USING (pg_has_role(current_user, (SELECT relowner FROM pg_catalog.pg_class
                                      WHERE oid = 'public.system_data_repair_records'::regclass), 'MEMBER'))
    WITH CHECK (pg_has_role(current_user, (SELECT relowner FROM pg_catalog.pg_class
                                           WHERE oid = 'public.system_data_repair_records'::regclass), 'MEMBER'));

-- 4. The registry's owner setting stays the marked owner column. The setting is the
-- compatibility copy stage 1's resolver and the card visibility read; the mark decides.
CREATE OR REPLACE FUNCTION public.protect_row_owner_setting() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM public.system_row_actor_columns AS marked
               WHERE marked.table_id = OLD.id AND marked.actor_role = 'owner'
                 AND marked.column_name IS DISTINCT FROM NEW.row_policy_owner_column) THEN
        RAISE EXCEPTION USING ERRCODE = 'check_violation', CONSTRAINT = 'row_owner_setting_fixed',
            MESSAGE = 'row owner setting is fixed to the marked owner column';
    END IF;
    RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS protect_row_owner_setting ON public.system_db_tables;
CREATE TRIGGER protect_row_owner_setting
    BEFORE UPDATE OF row_policy_owner_column ON public.system_db_tables
    FOR EACH ROW EXECUTE FUNCTION public.protect_row_owner_setting();

-- 5. The person behind the current request, set per transaction by the application
-- (dbutils.ApplyRequestActorToTx). A visitor ('1') and any connection without a
-- request give NULL, so a default built on it never invents an author.
CREATE OR REPLACE FUNCTION public.app_request_actor_id() RETURNS bigint
LANGUAGE sql STABLE PARALLEL SAFE AS $$
    SELECT CASE WHEN s ~ '^[0-9]{1,18}$' AND s::bigint > 1 THEN s::bigint END
    FROM (SELECT current_setting('app.user_id', true) AS s) AS actor
$$;

-- 6. Deleting a user empties the references to that user (ON DELETE SET NULL) and
-- nothing else. These two helpers recognise exactly that change.
CREATE OR REPLACE FUNCTION public.app_user_reference_cleared(old_value bigint, new_value bigint)
RETURNS boolean LANGUAGE sql STABLE AS $$
    SELECT old_value IS NOT NULL AND new_value IS NULL
       AND NOT EXISTS (SELECT 1 FROM public.system_users WHERE id = old_value)
$$;

CREATE OR REPLACE FUNCTION public.app_only_deleted_user_references_cleared(
    old_row jsonb, new_row jsonb, reference_columns text[])
RETURNS boolean LANGUAGE sql STABLE AS $$
    SELECT (old_row - reference_columns - 'updated') = (new_row - reference_columns - 'updated')
       AND EXISTS (
           SELECT 1 FROM unnest(reference_columns) AS reference(name)
           WHERE (old_row ->> reference.name) IS DISTINCT FROM (new_row ->> reference.name))
       AND NOT EXISTS (
           SELECT 1 FROM unnest(reference_columns) AS reference(name)
           WHERE (old_row ->> reference.name) IS DISTINCT FROM (new_row ->> reference.name)
             AND NOT public.app_user_reference_cleared((old_row ->> reference.name)::bigint,
                                                       (new_row ->> reference.name)::bigint))
$$;

-- A row's creator never changes, except that deleting the creator's account empties it.
CREATE OR REPLACE FUNCTION public.protect_row_creator() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.created_by IS DISTINCT FROM OLD.created_by
       AND NOT public.app_user_reference_cleared(OLD.created_by, NEW.created_by) THEN
        RAISE EXCEPTION USING ERRCODE = 'check_violation', CONSTRAINT = 'row_creator_immutable',
            MESSAGE = 'row creator is immutable';
    END IF;
    RETURN NEW;
END $$;

-- 7. Turn a table's own triggers off for the duration of a data step and back to
-- exactly the state each had: a data step must not stamp old rows as modified, and a
-- history guard must not refuse the step. The list's shape ([{"name", "state"}]) is
-- shared with every caller. A trigger that was already off stays off.
CREATE OR REPLACE FUNCTION public.app_suspend_row_triggers(target regclass)
RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
    saved jsonb := '[]'::jsonb;
    t record;
BEGIN
    FOR t IN SELECT tgname, tgenabled FROM pg_catalog.pg_trigger
             WHERE tgrelid = target AND NOT tgisinternal AND tgenabled <> 'D'
             ORDER BY tgname LOOP
        saved := saved || jsonb_build_object('name', t.tgname, 'state', t.tgenabled::text);
        EXECUTE format('ALTER TABLE %s DISABLE TRIGGER %I', target, t.tgname);
    END LOOP;
    RETURN saved;
END $$;

CREATE OR REPLACE FUNCTION public.app_restore_row_triggers(target regclass, saved jsonb)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    item jsonb;
BEGIN
    FOR item IN SELECT value FROM jsonb_array_elements(saved) LOOP
        EXECUTE format('ALTER TABLE %s %s TRIGGER %I', target,
            CASE item->>'state' WHEN 'O' THEN 'ENABLE' WHEN 'R' THEN 'ENABLE REPLICA'
                                WHEN 'A' THEN 'ENABLE ALWAYS' END,
            item->>'name');
    END LOOP;
END $$;

-- 8. Object names: prefix_table_column, shortened with a stable digest past
-- PostgreSQL's 63-byte limit, so a rerun finds what an earlier run created.
CREATE OR REPLACE FUNCTION public.app_row_actor_object_name(prefix text, table_name text, column_name text)
RETURNS text LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE
    full_name text := prefix || '_' || table_name || '_' || column_name;
    kept text;
BEGIN
    IF octet_length(full_name) <= 63 THEN
        RETURN full_name;
    END IF;
    kept := full_name;
    WHILE octet_length(kept) > 52 LOOP
        kept := left(kept, char_length(kept) - 1);
    END LOOP;
    RETURN kept || '_' || substr(md5(full_name), 1, 10);
END $$;

-- 9. Tables whose name says they are not content (rules R1-R5): their rows are system
-- records, attachments, embeddings, links or history, so they get no actor columns.
-- Both this release's data file and dataset creation ask here; the structural rules
-- (R4's link-table shape, R6-R8) need an existing table and live in the data file.
CREATE OR REPLACE FUNCTION public.app_row_actor_side_table_reason(table_name text)
RETURNS text LANGUAGE sql IMMUTABLE AS $$
    SELECT CASE
        WHEN lower(table_name) LIKE 'system\_%' AND lower(table_name) <> 'system_about'
            THEN 'R1: system table'
        WHEN lower(table_name) LIKE '%\_assets' THEN 'R2: attachment table'
        WHEN lower(table_name) LIKE '%\_lang\_embeddings' THEN 'R3: language embedding table'
        WHEN lower(table_name) ~ '_relations?$' THEN 'R4: link table'
        WHEN lower(table_name) ~ '_(log|logs|audit|audit_log|events|history|runs)$'
            THEN 'R5: log or history table'
    END
$$;

-- 10. The columns themselves: created_by always, and owner_id when the owner column is
-- owner_id. An existing column must be integer or bigint and not generated; a missing
-- one is added as a nullable bigint without a default, which rewrites nothing.
CREATE OR REPLACE FUNCTION public.app_ensure_row_actor_columns(target regclass, owner_column text)
RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
    changes jsonb := '[]'::jsonb;
    actor_column text;
    existing record;
BEGIN
    IF owner_column IS NULL OR owner_column = '' OR owner_column = 'created_by' THEN
        RAISE EXCEPTION USING ERRCODE = 'invalid_parameter_value',
            MESSAGE = format('%s: the owner column must be named and differ from created_by', target);
    END IF;
    FOREACH actor_column IN ARRAY ARRAY['created_by', owner_column] LOOP
        SELECT attribute.atttypid, attribute.attgenerated INTO existing
          FROM pg_catalog.pg_attribute AS attribute
         WHERE attribute.attrelid = target AND attribute.attname = actor_column
           AND attribute.attnum > 0 AND NOT attribute.attisdropped;
        IF FOUND THEN
            IF existing.atttypid NOT IN ('integer'::regtype, 'bigint'::regtype) OR existing.attgenerated <> '' THEN
                RAISE EXCEPTION USING ERRCODE = 'datatype_mismatch',
                    MESSAGE = format('%s.%s must be an integer or bigint column that is not generated',
                                     target, actor_column);
            END IF;
        ELSIF actor_column IN ('created_by', 'owner_id') THEN
            EXECUTE format('ALTER TABLE %s ADD COLUMN %I bigint', target, actor_column);
            changes := changes || jsonb_build_object('action', 'column_added', 'column', actor_column);
        ELSE
            RAISE EXCEPTION USING ERRCODE = 'undefined_column',
                MESSAGE = format('%s: the kept owner column %s does not exist', target, actor_column);
        END IF;
    END LOOP;
    RETURN changes;
END $$;

-- 11. Each actor column's foreign key, index, default and, for the creator, its guard
-- trigger. Only what is missing is made, so the function can always run again.
CREATE OR REPLACE FUNCTION public.app_ensure_row_actor_constraints(target regclass, owner_column text)
RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
    changes jsonb := '[]'::jsonb;
    table_name text := (SELECT relname FROM pg_catalog.pg_class WHERE oid = target);
    actor_column text;
    column_number smallint;
    users_id_number smallint := (SELECT attnum FROM pg_catalog.pg_attribute
                                 WHERE attrelid = 'public.system_users'::regclass AND attname = 'id');
    reference record;
    reference_count integer;
    other_reference_count integer;
    wanted_name text;
    existing_index record;
    default_expression text;
    trigger_name text := public.app_row_actor_object_name('protect', table_name, 'creator');
    existing_trigger record;
BEGIN
    FOREACH actor_column IN ARRAY ARRAY['created_by', owner_column] LOOP
        SELECT attnum INTO column_number FROM pg_catalog.pg_attribute
         WHERE attrelid = target AND attname = actor_column AND attnum > 0 AND NOT attisdropped;
        IF column_number IS NULL THEN
            RAISE EXCEPTION USING ERRCODE = 'undefined_column',
                MESSAGE = format('%s.%s does not exist', target, actor_column);
        END IF;

        -- Foreign key: one to system_users(id), ON DELETE SET NULL, simple, not deferrable.
        SELECT count(*) FILTER (WHERE confrelid = 'public.system_users'::regclass
                                  AND confkey = ARRAY[users_id_number]),
               count(*) FILTER (WHERE NOT (confrelid = 'public.system_users'::regclass
                                           AND confkey = ARRAY[users_id_number]))
          INTO reference_count, other_reference_count
          FROM pg_catalog.pg_constraint
         WHERE conrelid = target AND contype = 'f' AND column_number = ANY(conkey);
        IF other_reference_count > 0 OR reference_count > 1 THEN
            RAISE EXCEPTION USING ERRCODE = 'invalid_foreign_key',
                MESSAGE = format('%s.%s must reference only system_users(id), once', target, actor_column);
        END IF;
        IF reference_count = 1 THEN
            SELECT oid, conname, confdeltype, confmatchtype, condeferrable, convalidated,
                   pg_get_constraintdef(oid) AS definition
              INTO reference
              FROM pg_catalog.pg_constraint
             WHERE conrelid = target AND contype = 'f' AND conkey = ARRAY[column_number];
            IF reference.oid IS NULL THEN
                RAISE EXCEPTION USING ERRCODE = 'invalid_foreign_key',
                    MESSAGE = format('%s.%s: its foreign key also covers other columns', target, actor_column);
            END IF;
            IF reference.confdeltype <> 'n' OR reference.confmatchtype <> 's' OR reference.condeferrable THEN
                RAISE EXCEPTION USING ERRCODE = 'invalid_foreign_key',
                    MESSAGE = format('%s.%s: foreign key %s must be ON DELETE SET NULL, simple and not deferrable: %s',
                                     target, actor_column, reference.conname, reference.definition);
            END IF;
            IF NOT reference.convalidated THEN
                EXECUTE format('ALTER TABLE %s VALIDATE CONSTRAINT %I', target, reference.conname);
                changes := changes || jsonb_build_object('action', 'fk_validated', 'column', actor_column,
                                                         'constraint', reference.conname);
            END IF;
        ELSE
            wanted_name := public.app_row_actor_object_name('fk', table_name, actor_column);
            IF EXISTS (SELECT 1 FROM pg_catalog.pg_constraint WHERE conrelid = target AND conname = wanted_name) THEN
                RAISE EXCEPTION USING ERRCODE = 'duplicate_object',
                    MESSAGE = format('%s: constraint %s already exists with another definition', target, wanted_name);
            END IF;
            EXECUTE format('ALTER TABLE %s ADD CONSTRAINT %I FOREIGN KEY (%I) '
                           'REFERENCES public.system_users(id) ON DELETE SET NULL NOT VALID',
                           target, wanted_name, actor_column);
            EXECUTE format('ALTER TABLE %s VALIDATE CONSTRAINT %I', target, wanted_name);
            changes := changes || jsonb_build_object('action', 'fk_added', 'column', actor_column,
                                                     'constraint', wanted_name);
        END IF;

        -- Index: a valid, ready, non-partial btree whose first key is the column itself.
        -- Only an invalid index (a failed concurrent build) under the wanted name is
        -- replaced. A valid index that does not qualify, such as a partial unique one,
        -- keeps its rule untouched, and the helper index gets another name.
        IF NOT EXISTS (
            SELECT 1 FROM pg_catalog.pg_index AS index_row
            JOIN pg_catalog.pg_class AS index_class ON index_class.oid = index_row.indexrelid
            JOIN pg_catalog.pg_am AS method ON method.oid = index_class.relam
            WHERE index_row.indrelid = target AND method.amname = 'btree'
              AND index_row.indisvalid AND index_row.indisready AND index_row.indpred IS NULL
              AND index_row.indkey[0] = column_number) THEN
            wanted_name := public.app_row_actor_object_name('idx', table_name, actor_column);
            SELECT index_class.oid, index_row.indrelid, index_row.indisvalid INTO existing_index
              FROM pg_catalog.pg_class AS index_class
              JOIN pg_catalog.pg_index AS index_row ON index_row.indexrelid = index_class.oid
             WHERE index_class.relname = wanted_name
               AND index_class.relnamespace = (SELECT relnamespace FROM pg_catalog.pg_class WHERE oid = target);
            IF FOUND AND existing_index.indrelid = target AND NOT existing_index.indisvalid THEN
                EXECUTE format('DROP INDEX %s', existing_index.oid::regclass);
                changes := changes || jsonb_build_object('action', 'invalid_index_replaced', 'column', actor_column,
                                                         'index', wanted_name);
            ELSIF FOUND THEN
                wanted_name := public.app_row_actor_object_name('idx', table_name, actor_column || '_actor');
                IF to_regclass(format('%I.%I',
                       (SELECT nspname FROM pg_catalog.pg_namespace
                         WHERE oid = (SELECT relnamespace FROM pg_catalog.pg_class WHERE oid = target)),
                       wanted_name)) IS NOT NULL THEN
                    RAISE EXCEPTION USING ERRCODE = 'duplicate_object',
                        MESSAGE = format('%s: index names for %s are taken by other indexes', target, actor_column);
                END IF;
            END IF;
            changes := changes || COALESCE((
                SELECT jsonb_agg(jsonb_build_object('action', 'index_not_qualifying', 'column', actor_column,
                                                    'index', index_class.relname) ORDER BY index_class.relname)
                  FROM pg_catalog.pg_index AS index_row
                  JOIN pg_catalog.pg_class AS index_class ON index_class.oid = index_row.indexrelid
                 WHERE index_row.indrelid = target AND column_number = ANY(index_row.indkey)), '[]'::jsonb);
            EXECUTE format('CREATE INDEX %I ON %s (%I)', wanted_name, target, actor_column);
            changes := changes || jsonb_build_object('action', 'index_added', 'column', actor_column,
                                                     'index', wanted_name);
        END IF;

        -- Default: the request's actor. A kept site owner column keeps a default of its own.
        SELECT pg_get_expr(column_default.adbin, column_default.adrelid) INTO default_expression
          FROM pg_catalog.pg_attrdef AS column_default
         WHERE column_default.adrelid = target AND column_default.adnum = column_number;
        IF default_expression IS NULL
           OR (actor_column IN ('created_by', 'owner_id')
               AND default_expression NOT IN ('app_request_actor_id()', 'public.app_request_actor_id()')) THEN
            EXECUTE format('ALTER TABLE %s ALTER COLUMN %I SET DEFAULT public.app_request_actor_id()',
                           target, actor_column);
            changes := changes || jsonb_build_object('action', 'default_added', 'column', actor_column,
                                                     'old_value', default_expression);
        END IF;
        default_expression := NULL;
        column_number := NULL;
    END LOOP;

    -- The creator's guard: created_by never changes, except when its user is deleted.
    SELECT trigger_row.tgenabled, trigger_row.tgfoid INTO existing_trigger
      FROM pg_catalog.pg_trigger AS trigger_row
     WHERE trigger_row.tgrelid = target AND trigger_row.tgname = trigger_name AND NOT trigger_row.tgisinternal;
    IF NOT FOUND THEN
        EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE OF created_by ON %s '
                       'FOR EACH ROW EXECUTE FUNCTION public.protect_row_creator()', trigger_name, target);
        changes := changes || jsonb_build_object('action', 'creator_trigger_added', 'trigger', trigger_name);
    ELSIF existing_trigger.tgfoid <> 'public.protect_row_creator()'::regprocedure THEN
        RAISE EXCEPTION USING ERRCODE = 'duplicate_object',
            MESSAGE = format('%s: trigger %s exists with another function', target, trigger_name);
    END IF;
    RETURN changes;
END $$;

-- 12. Registration: the columns' metadata, the actor marks with the registry setting,
-- and the relation rows of the two foreign keys. The marks and the setting are written
-- once, marks first; after that the setting follows the mark and nothing here rewrites
-- either. A metadata row the generic synchronisation already made keeps the role an
-- administrator chose; only insert and edit are closed on it.
CREATE OR REPLACE FUNCTION public.app_register_row_actor_columns(registry_id bigint, owner_column text)
RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
    changes jsonb := '[]'::jsonb;
    registry record;
    target regclass;
    users_table_uid integer;
    actor record;
    previous_flag boolean;
BEGIN
    SELECT id, table_uid, table_name, COALESCE(schema_name, 'public') AS schema_name, row_policy_owner_column
      INTO registry
      FROM public.system_db_tables WHERE id = registry_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING ERRCODE = 'no_data_found',
            MESSAGE = format('registry row %s does not exist', registry_id);
    END IF;
    target := format('%I.%I', registry.schema_name, registry.table_name)::regclass;

    FOR actor IN
        SELECT * FROM (VALUES ('creator', 'created_by', 'WL58 row creator'),
                              ('owner', owner_column, 'WL58 row owner')) AS wanted (role, column_name, spec)
    LOOP
        IF NOT EXISTS (SELECT 1 FROM public.system_column_details
                       WHERE table_uid = registry.table_uid AND column_name = actor.column_name) THEN
            INSERT INTO public.system_column_details
                (table_uid, column_name, data_type, co_number, lang_key, card_element, insertable,
                 editable_in_ui, hide_in_filter_panel, show_value_on_card, creation_spec)
            SELECT registry.table_uid, actor.column_name, format_type(attribute.atttypid, attribute.atttypmod),
                   attribute.attnum, actor.column_name, 'hidden', FALSE, FALSE, TRUE, TRUE, actor.spec
              FROM pg_catalog.pg_attribute AS attribute
             WHERE attribute.attrelid = target AND attribute.attname = actor.column_name;
            changes := changes || jsonb_build_object('action', 'column_metadata_added', 'column', actor.column_name);
        ELSE
            UPDATE public.system_column_details
               SET insertable = FALSE, editable_in_ui = FALSE, updated = now()
             WHERE table_uid = registry.table_uid AND column_name = actor.column_name
               AND (insertable IS DISTINCT FROM FALSE OR editable_in_ui IS DISTINCT FROM FALSE);
            IF FOUND THEN
                changes := changes || jsonb_build_object('action', 'column_metadata_locked', 'column', actor.column_name);
            END IF;
        END IF;
    END LOOP;

    IF NOT EXISTS (SELECT 1 FROM public.system_row_actor_columns
                   WHERE table_id = registry.id AND actor_role = 'owner') THEN
        INSERT INTO public.system_row_actor_columns (table_id, actor_role, column_name)
        VALUES (registry.id, 'creator', 'created_by')
        ON CONFLICT (table_id, actor_role) DO NOTHING;
        INSERT INTO public.system_row_actor_columns (table_id, actor_role, column_name)
        VALUES (registry.id, 'owner', owner_column);
        changes := changes || jsonb_build_object('action', 'actor_columns_marked',
                                                 'creator', 'created_by', 'owner', owner_column);
        IF registry.row_policy_owner_column IS DISTINCT FROM owner_column THEN
            UPDATE public.system_db_tables SET row_policy_owner_column = owner_column, updated = now()
             WHERE id = registry.id;
            changes := changes || jsonb_build_object('action', 'registry_owner_moved',
                                                     'old_value', registry.row_policy_owner_column,
                                                     'new_value', owner_column);
        END IF;
    END IF;

    -- A relation row lets the generic synchronisation recognise the two keys; a new
    -- source row must never be inserted with its user, so the flag is FALSE.
    SELECT table_uid INTO users_table_uid FROM public.system_db_tables
     WHERE COALESCE(schema_name, 'public') = 'public' AND table_name = 'system_users';
    IF users_table_uid IS NOT NULL THEN
        FOR actor IN SELECT unnest(ARRAY['created_by', owner_column]) AS column_name LOOP
            SELECT insert_new_source_with_target INTO previous_flag
              FROM public.system_foreign_key_relations_1_m
             WHERE source_table_uid = registry.table_uid AND target_table_uid = users_table_uid
               AND source_column_name = actor.column_name AND target_column_name = 'id';
            IF NOT FOUND THEN
                INSERT INTO public.system_foreign_key_relations_1_m
                    (source_table_uid, source_column_name, target_table_uid, target_column_name,
                     reference_direction, insert_new_source_with_target, source_insert_specs)
                VALUES (registry.table_uid, actor.column_name, users_table_uid, 'id',
                        registry.table_name || '->system_users', FALSE, '{}'::jsonb);
            ELSIF previous_flag IS DISTINCT FROM FALSE THEN
                UPDATE public.system_foreign_key_relations_1_m
                   SET insert_new_source_with_target = FALSE, updated = now()
                 WHERE source_table_uid = registry.table_uid AND target_table_uid = users_table_uid
                   AND source_column_name = actor.column_name AND target_column_name = 'id';
                changes := changes || jsonb_build_object('action', 'relation_flag_changed',
                                                         'column', actor.column_name, 'old_value', previous_flag);
            END IF;
        END LOOP;
    END IF;
    RETURN changes;
END $$;

-- 13. Reading the marks: the creator or owner column of a table, or NULL when the table
-- has no such mark. Never assume a column name (user_id, owner_id) instead.
CREATE OR REPLACE FUNCTION public.app_row_actor_column(target regclass, actor_role text)
RETURNS text LANGUAGE sql STABLE AS $$
    SELECT marked.column_name
      FROM public.system_row_actor_columns AS marked
      JOIN public.system_db_tables AS registry ON registry.id = marked.table_id
      JOIN pg_catalog.pg_class AS relation ON relation.oid = target
      JOIN pg_catalog.pg_namespace AS relation_schema ON relation_schema.oid = relation.relnamespace
     WHERE COALESCE(registry.schema_name, 'public') = relation_schema.nspname
       AND registry.table_name = relation.relname
       AND marked.actor_role = app_row_actor_column.actor_role
$$;

-- 14. The final check every structural file of this release ends with, and the public
-- bootstrap's acceptance block runs: each line is one contradiction, none means sound.
-- It checks meaning, not names: the setting against the mark, the columns' types,
-- one validated SET NULL key to system_users(id), the creator's enabled guard, and the
-- guards of the two internal tables and of the registry.
CREATE OR REPLACE FUNCTION public.app_check_row_actor_marks()
RETURNS SETOF text LANGUAGE plpgsql STABLE AS $$
DECLARE
    marked record;
    target regclass;
    column_row record;
    users_id_number smallint := (SELECT attnum FROM pg_catalog.pg_attribute
                                 WHERE attrelid = 'public.system_users'::regclass AND attname = 'id');
    guard record;
BEGIN
    -- A guard counts only when it fires on ordinary writes ('O' origin or 'A' always,
    -- not 'R' replica-only) and runs its own function.
    FOR guard IN
        SELECT * FROM (VALUES ('public.system_row_actor_columns', 'owner_only_writes', 'public.app_owner_only_writes()'),
                              ('public.system_row_actor_columns', 'owner_only_truncate', 'public.app_owner_only_writes()'),
                              ('public.system_data_repair_records', 'owner_only_writes', 'public.app_owner_only_writes()'),
                              ('public.system_data_repair_records', 'owner_only_truncate', 'public.app_owner_only_writes()'),
                              ('public.system_db_tables', 'protect_row_owner_setting', 'public.protect_row_owner_setting()'))
                 AS wanted (table_name, trigger_name, function_name)
    LOOP
        IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_trigger
                       WHERE tgrelid = guard.table_name::regclass AND tgname = guard.trigger_name
                         AND NOT tgisinternal AND tgenabled IN ('O', 'A')
                         AND tgfoid = guard.function_name::regprocedure) THEN
            RETURN NEXT format('%s: guard trigger %s is missing, not firing on ordinary writes or not running %s',
                               guard.table_name, guard.trigger_name, guard.function_name);
        END IF;
    END LOOP;
    IF NOT (SELECT relrowsecurity FROM pg_catalog.pg_class
            WHERE oid = 'public.system_data_repair_records'::regclass) THEN
        RETURN NEXT 'public.system_data_repair_records: row security is off';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_policy
                   WHERE polrelid = 'public.system_data_repair_records'::regclass
                     AND polname = 'repair_records_owner_role') THEN
        RETURN NEXT 'public.system_data_repair_records: policy repair_records_owner_role is missing';
    END IF;

    FOR marked IN
        SELECT registry.id AS table_id, registry.table_name, COALESCE(registry.schema_name, 'public') AS schema_name,
               registry.row_policy_owner_column,
               max(mark.column_name) FILTER (WHERE mark.actor_role = 'creator') AS creator_column,
               max(mark.column_name) FILTER (WHERE mark.actor_role = 'owner') AS owner_column
          FROM public.system_row_actor_columns AS mark
          JOIN public.system_db_tables AS registry ON registry.id = mark.table_id
         GROUP BY registry.id, registry.table_name, registry.schema_name, registry.row_policy_owner_column
         ORDER BY registry.table_name
    LOOP
        target := to_regclass(format('%I.%I', marked.schema_name, marked.table_name));
        IF target IS NULL THEN
            RETURN NEXT format('%s: marked table does not exist', marked.table_name);
            CONTINUE;
        END IF;
        IF marked.creator_column IS NULL OR marked.owner_column IS NULL THEN
            RETURN NEXT format('%s: needs both a creator and an owner mark', marked.table_name);
        END IF;
        IF marked.owner_column IS DISTINCT FROM marked.row_policy_owner_column THEN
            RETURN NEXT format('%s: registry owner setting %s differs from the owner mark %s',
                               marked.table_name, COALESCE(marked.row_policy_owner_column, '(empty)'),
                               COALESCE(marked.owner_column, '(none)'));
        END IF;
        FOR column_row IN
            SELECT wanted.role, wanted.column_name, attribute.attnum, attribute.atttypid
              FROM (VALUES ('creator', marked.creator_column), ('owner', marked.owner_column))
                   AS wanted (role, column_name)
              LEFT JOIN pg_catalog.pg_attribute AS attribute
                ON attribute.attrelid = target AND attribute.attname = wanted.column_name
               AND attribute.attnum > 0 AND NOT attribute.attisdropped
             WHERE wanted.column_name IS NOT NULL
        LOOP
            IF column_row.attnum IS NULL THEN
                RETURN NEXT format('%s.%s: marked %s column does not exist',
                                   marked.table_name, column_row.column_name, column_row.role);
                CONTINUE;
            END IF;
            IF column_row.atttypid NOT IN ('integer'::regtype, 'bigint'::regtype) THEN
                RETURN NEXT format('%s.%s: marked %s column is %s, not integer or bigint', marked.table_name,
                                   column_row.column_name, column_row.role, format_type(column_row.atttypid, NULL));
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM pg_catalog.pg_constraint
                 WHERE conrelid = target AND contype = 'f' AND conkey = ARRAY[column_row.attnum]
                   AND confrelid = 'public.system_users'::regclass AND confkey = ARRAY[users_id_number]
                   AND convalidated AND confdeltype = 'n' AND confmatchtype = 's' AND NOT condeferrable) THEN
                RETURN NEXT format('%s.%s: no validated ON DELETE SET NULL foreign key to system_users(id)',
                                   marked.table_name, column_row.column_name);
            END IF;
            IF (SELECT count(*) FROM pg_catalog.pg_constraint
                 WHERE conrelid = target AND contype = 'f' AND column_row.attnum = ANY(conkey)) > 1 THEN
                RETURN NEXT format('%s.%s: has more than one foreign key', marked.table_name, column_row.column_name);
            END IF;
            IF column_row.role = 'creator' AND NOT EXISTS (
                SELECT 1 FROM pg_catalog.pg_trigger
                 WHERE tgrelid = target AND NOT tgisinternal AND tgenabled IN ('O', 'A')
                   AND tgfoid = 'public.protect_row_creator()'::regprocedure) THEN
                RETURN NEXT format('%s: the creator guard trigger is missing or not firing on ordinary writes',
                                   marked.table_name);
            END IF;
        END LOOP;
    END LOOP;
    RETURN;
END $$;

-- 15. The developer history guards: deleting a user may empty that user's references
-- in otherwise immutable history (creator, owner, locker), and nothing else. Each guard
-- below is its original body (20260919000008) with that one exception first.
CREATE OR REPLACE FUNCTION public.protect_dev_agent_workline_report_history()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND public.app_only_deleted_user_references_cleared(
           to_jsonb(OLD), to_jsonb(NEW), ARRAY['created_by', 'owner_id']) THEN
        RETURN NEW;
    END IF;

    IF OLD.state = 'redacted' AND NEW IS DISTINCT FROM OLD THEN
        RAISE EXCEPTION 'redacted workline reports are terminal';
    END IF;

    IF NEW.state = 'redacted' AND OLD.state <> 'redacted' THEN
        IF NEW.title <> 'Redacted report'
           OR NEW.content <> '[redacted]'
           OR NEW.source_ref IS NOT NULL
           OR NEW.tags <> '{}'::TEXT[]
           OR NEW.metadata_json <> '{}'::JSONB
           OR NEW.context_text IS NOT NULL
           OR NEW.plain_language_text IS NOT NULL
           OR NEW.technical_text IS NOT NULL
           OR NEW.next_step_text IS NOT NULL
           OR NEW.snapshot_json <> '{}'::JSONB
           OR NEW.git_workline_changed_paths <> '{}'::TEXT[]
           OR NEW.redaction_reason IS NULL THEN
            RAISE EXCEPTION 'workline report redaction must remove all free-form fields';
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.workline_id IS DISTINCT FROM OLD.workline_id
       OR NEW.title IS DISTINCT FROM OLD.title
       OR NEW.report_type IS DISTINCT FROM OLD.report_type
       OR NEW.outcome IS DISTINCT FROM OLD.outcome
       OR NEW.content IS DISTINCT FROM OLD.content
       OR NEW.source_kind IS DISTINCT FROM OLD.source_kind
       OR NEW.source_ref IS DISTINCT FROM OLD.source_ref
       OR NEW.tags IS DISTINCT FROM OLD.tags
       OR NEW.metadata_json IS DISTINCT FROM OLD.metadata_json
       OR NEW.content_hash IS DISTINCT FROM OLD.content_hash
       OR NEW.supersedes_report_id IS DISTINCT FROM OLD.supersedes_report_id
       OR NEW.redaction_reason IS DISTINCT FROM OLD.redaction_reason
       OR NEW.created_by IS DISTINCT FROM OLD.created_by
       OR NEW.created IS DISTINCT FROM OLD.created
       OR NEW.format_version IS DISTINCT FROM OLD.format_version
       OR NEW.phase_gate IS DISTINCT FROM OLD.phase_gate
       OR NEW.current_phase IS DISTINCT FROM OLD.current_phase
       OR NEW.workline_status_snapshot IS DISTINCT FROM OLD.workline_status_snapshot
       OR NEW.changed_this_turn IS DISTINCT FROM OLD.changed_this_turn
       OR NEW.context_text IS DISTINCT FROM OLD.context_text
       OR NEW.plain_language_text IS DISTINCT FROM OLD.plain_language_text
       OR NEW.technical_text IS DISTINCT FROM OLD.technical_text
       OR NEW.next_step_text IS DISTINCT FROM OLD.next_step_text
       OR NEW.snapshot_json IS DISTINCT FROM OLD.snapshot_json
       OR NEW.git_head_commit IS DISTINCT FROM OLD.git_head_commit
       OR NEW.git_worktree_state IS DISTINCT FROM OLD.git_worktree_state
       OR NEW.git_has_other_changes IS DISTINCT FROM OLD.git_has_other_changes
       OR NEW.git_workline_changed_paths IS DISTINCT FROM OLD.git_workline_changed_paths THEN
        RAISE EXCEPTION 'workline report bodies are immutable';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.protect_dev_agent_handover_report_history()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND public.app_only_deleted_user_references_cleared(
           to_jsonb(OLD), to_jsonb(NEW), ARRAY['created_by', 'owner_id']) THEN
        RETURN NEW;
    END IF;

    IF NEW.title IS DISTINCT FROM OLD.title
       OR NEW.source_kind IS DISTINCT FROM OLD.source_kind
       OR NEW.source_ref IS DISTINCT FROM OLD.source_ref
       OR NEW.tags IS DISTINCT FROM OLD.tags
       OR NEW.metadata_json IS DISTINCT FROM OLD.metadata_json
       OR NEW.membership_hash IS DISTINCT FROM OLD.membership_hash
       OR NEW.supersedes_handover_id IS DISTINCT FROM OLD.supersedes_handover_id
       OR NEW.created_by IS DISTINCT FROM OLD.created_by
       OR NEW.created IS DISTINCT FROM OLD.created THEN
        RAISE EXCEPTION 'handover report manifests are immutable';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.protect_dev_agent_release_goal_contracts()
RETURNS TRIGGER AS $$
DECLARE
    resolved_goal_id BIGINT;
    resolved_state TEXT;
BEGIN
    IF TG_OP = 'UPDATE' AND public.app_only_deleted_user_references_cleared(
           to_jsonb(OLD), to_jsonb(NEW), ARRAY['created_by', 'owner_id']) THEN
        RETURN NEW;
    END IF;

    resolved_goal_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.release_goal_id ELSE NEW.release_goal_id END;
    SELECT decision_state INTO resolved_state
      FROM public.dev_agent_release_goals
     WHERE id = resolved_goal_id;
    IF resolved_state = 'locked' THEN
        RAISE EXCEPTION 'locked release goal contracts are immutable';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.protect_dev_agent_release_goal_lock()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND public.app_only_deleted_user_references_cleared(
           to_jsonb(OLD), to_jsonb(NEW), ARRAY['created_by', 'owner_id', 'locked_by']) THEN
        RETURN NEW;
    END IF;

    IF OLD.decision_state = 'locked' THEN
        IF NEW.identity_key IS DISTINCT FROM OLD.identity_key
           OR NEW.version IS DISTINCT FROM OLD.version
           OR NEW.title IS DISTINCT FROM OLD.title
           OR NEW.outcome IS DISTINCT FROM OLD.outcome
           OR NEW.decision_state IS DISTINCT FROM OLD.decision_state
           OR NEW.created_by IS DISTINCT FROM OLD.created_by
           OR NEW.locked_by IS DISTINCT FROM OLD.locked_by
           OR NEW.created IS DISTINCT FROM OLD.created
           OR NEW.locked_at IS DISTINCT FROM OLD.locked_at THEN
            RAISE EXCEPTION 'locked release goal identity is immutable';
        END IF;
        RETURN NEW;
    END IF;
    IF NEW.decision_state = 'locked' THEN
        IF EXISTS (
            SELECT 1
              FROM public.dev_agent_worklines AS worklines
             WHERE worklines.status = 'active'
               AND NOT EXISTS (
                    SELECT 1
                      FROM public.dev_agent_release_goal_contracts AS contracts
                     WHERE contracts.release_goal_id = NEW.id
                       AND contracts.workline_id = worklines.id
               )
        ) THEN
            RAISE EXCEPTION 'every active workline must be classified before locking a release goal';
        END IF;
        NEW.locked_at := COALESCE(NEW.locked_at, now());
    END IF;
    NEW.updated := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 16. The file's own completion marker, the one row it writes.
INSERT INTO public.system_data_repair_records (migration, action, detail)
SELECT 'wl58_row_actor_support', 'completed',
       jsonb_build_object('file', '20261005000001_add_row_actor_support.sql')
WHERE NOT EXISTS (
    SELECT 1 FROM public.system_data_repair_records
    WHERE migration = 'wl58_row_actor_support' AND action = 'completed'
);
