-- 20261005000021_create_system_favorites.sql
-- Stores account-owned favorites with a stable dataset reference and a textual row key.
-- Connects typed favorite resolvers with the shared registry and account lifecycle.
-- Exists so future target types reuse one table without accepting SQL identifiers.
-- VERSION_DB: 9.10.0
-- VERSION_DB_OWNER: 20261005000099_record_database_release_9_10_0.sql
-- COMPLETION_MARKER: system_favorites_table

CREATE TABLE IF NOT EXISTS public.system_favorites (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.system_users(id) ON DELETE CASCADE,
    target_table_uid integer NOT NULL REFERENCES public.system_db_tables(table_uid) ON DELETE CASCADE,
    target_key text NOT NULL CHECK (char_length(target_key) BETWEEN 1 AND 200),
    sort_order integer NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    created timestamptz NOT NULL DEFAULT now(),
    updated timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_system_favorites_not_visitor CHECK (user_id <> 1),
    CONSTRAINT uq_system_favorites_user_target UNIQUE (user_id, target_table_uid, target_key)
);
CREATE INDEX IF NOT EXISTS idx_system_favorites_target
    ON public.system_favorites (target_table_uid, target_key);

COMMENT ON TABLE public.system_favorites IS
    'Personal favorites. Typed server resolvers check target visibility; generic row writes are forbidden.';
COMMENT ON COLUMN public.system_favorites.user_id IS
    'Account owner, always taken from the session; visitor and site-wide favorites are not allowed.';
COMMENT ON COLUMN public.system_favorites.target_table_uid IS
    'Stable registry identity, resolved by table name on this installation, never supplied by the client.';
COMMENT ON COLUMN public.system_favorites.target_key IS
    'Text form of the target single-column primary key from the PostgreSQL catalog; integer keys use canonical decimal form. Admin tools resolve a system_functions id from their route.';
COMMENT ON COLUMN public.system_favorites.sort_order IS 'Insertion order within the account; v1 offers no reordering.';

CREATE OR REPLACE FUNCTION public.set_system_favorites_updated_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger
        WHERE tgname = 'update_system_favorites_timestamp'
          AND tgrelid = 'public.system_favorites'::regclass) THEN
        CREATE TRIGGER update_system_favorites_timestamp BEFORE UPDATE ON public.system_favorites
            FOR EACH ROW EXECUTE FUNCTION public.set_system_favorites_updated_timestamp();
    END IF;
END $$;

INSERT INTO public.system_data_repair_records (migration, action, detail)
SELECT 'system_favorites_table', 'completed',
       jsonb_build_object('file', '20261005000021_create_system_favorites.sql')
WHERE NOT EXISTS (SELECT 1 FROM public.system_data_repair_records
    WHERE migration = 'system_favorites_table' AND action = 'completed');
