-- 20261005000031_create_system_front_page_blocks.sql
-- Stores ordered common and account-specific front page blocks with stable dataset references.
-- Connects the read facade and administrator API with account and dataset lifecycles.
-- Exists so personal lists replace the common list without duplicating menu defaults.
-- VERSION_DB: 9.10.0
-- VERSION_DB_OWNER: 20261005000099_record_database_release_9_10_0.sql
-- COMPLETION_MARKER: system_front_page_blocks_table

CREATE TABLE IF NOT EXISTS public.system_front_page_blocks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint REFERENCES public.system_users(id) ON DELETE CASCADE,
    table_uid integer NOT NULL REFERENCES public.system_db_tables(table_uid) ON DELETE CASCADE,
    result_limit smallint NOT NULL DEFAULT 5 CHECK (result_limit BETWEEN 1 AND 20),
    sort_order integer NOT NULL CHECK (sort_order BETWEEN 1 AND 100),
    enabled boolean NOT NULL DEFAULT true,
    created timestamptz NOT NULL DEFAULT now(),
    updated timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_system_front_page_blocks_not_visitor CHECK (user_id <> 1),
    CONSTRAINT uq_system_front_page_blocks_dataset UNIQUE NULLS NOT DISTINCT (user_id, table_uid),
    CONSTRAINT uq_system_front_page_blocks_position UNIQUE NULLS NOT DISTINCT (user_id, sort_order)
);
CREATE INDEX IF NOT EXISTS idx_system_front_page_blocks_table ON public.system_front_page_blocks (table_uid);

COMMENT ON TABLE public.system_front_page_blocks IS
    'Front page blocks. Any account row replaces the common list; only the dedicated administrator API writes.';
COMMENT ON COLUMN public.system_front_page_blocks.user_id IS
    'NULL is the common site list; account 1 is never a personal scope. Deleting the account removes its list.';
COMMENT ON COLUMN public.system_front_page_blocks.table_uid IS
    'Installation-local stable dataset identity resolved by name; dropping a dataset removes its blocks.';
COMMENT ON COLUMN public.system_front_page_blocks.enabled IS
    'Disabled rows still make an account list its own; all disabled means deliberately empty.';
COMMENT ON COLUMN public.system_front_page_blocks.result_limit IS 'Newest visible rows requested, from 1 to 20, default 5.';
COMMENT ON COLUMN public.system_front_page_blocks.sort_order IS 'Unique position within the common or account list, from 1 to 100.';

CREATE OR REPLACE FUNCTION public.set_system_front_page_blocks_updated_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_system_front_page_blocks_timestamp'
        AND tgrelid = 'public.system_front_page_blocks'::regclass) THEN
        CREATE TRIGGER update_system_front_page_blocks_timestamp BEFORE UPDATE ON public.system_front_page_blocks
            FOR EACH ROW EXECUTE FUNCTION public.set_system_front_page_blocks_updated_timestamp();
    END IF;
END $$;

INSERT INTO public.system_data_repair_records (migration, action, detail)
SELECT 'system_front_page_blocks_table', 'completed',
       jsonb_build_object('file', '20261005000031_create_system_front_page_blocks.sql')
WHERE NOT EXISTS (SELECT 1 FROM public.system_data_repair_records
    WHERE migration = 'system_front_page_blocks_table' AND action = 'completed');
