-- 20260919000008_create_developer_workline_schema.sql
-- Creates the current workline, report, handover, and release-goal tables.
-- Bridges the shipped db_report command and Workline Observatory with public storage.
-- Exists so workline continuity no longer depends on a private composition database.
-- VERSION_DB: 9.8.0
-- VERSION_DB_OWNER: 20260919000010_record_developer_workflow_schema_release.sql

CREATE TABLE IF NOT EXISTS public.dev_agent_worklines (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               TEXT        NOT NULL CHECK (char_length(btrim(title)) BETWEEN 1 AND 300),
    status              TEXT        NOT NULL DEFAULT 'active',
    tags                TEXT[]      NOT NULL DEFAULT '{}'::TEXT[],
    created_by          INTEGER     REFERENCES public.system_users(id) ON DELETE SET NULL,
    created             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated             TIMESTAMPTZ NOT NULL DEFAULT now(),
    status_changed_by   INTEGER     REFERENCES public.system_users(id) ON DELETE SET NULL,
    status_changed_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    status_change_source TEXT       NOT NULL DEFAULT 'legacy',
    status_revision     BIGINT      NOT NULL DEFAULT 0,
    priority            TEXT        NOT NULL DEFAULT 'normal',
    priority_revision   BIGINT      NOT NULL DEFAULT 0,
    priority_changed_by INTEGER     REFERENCES public.system_users(id) ON DELETE SET NULL,
    priority_changed_at TIMESTAMPTZ,
    CONSTRAINT ck_dev_agent_worklines_status
        CHECK (status IN ('active', 'paused', 'closed', 'archived')),
    CONSTRAINT ck_dev_agent_worklines_status_change_source
        CHECK (status_change_source IN ('legacy', 'creation', 'agent_tools_api', 'report_sync', 'observatory_ui')),
    CONSTRAINT ck_dev_agent_worklines_status_revision CHECK (status_revision >= 0),
    CONSTRAINT ck_dev_agent_worklines_priority
        CHECK (priority IN ('low', 'normal', 'high', 'critical')),
    CONSTRAINT ck_dev_agent_worklines_priority_revision CHECK (priority_revision >= 0)
);

ALTER TABLE public.dev_agent_worklines
    ADD COLUMN IF NOT EXISTS status_changed_by INTEGER REFERENCES public.system_users(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS status_changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS status_change_source TEXT NOT NULL DEFAULT 'legacy',
    ADD COLUMN IF NOT EXISTS status_revision BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS priority TEXT NOT NULL DEFAULT 'normal',
    ADD COLUMN IF NOT EXISTS priority_revision BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS priority_changed_by INTEGER REFERENCES public.system_users(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS priority_changed_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS public.dev_agent_workline_reports (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workline_id                BIGINT      NOT NULL REFERENCES public.dev_agent_worklines(id) ON DELETE CASCADE,
    title                      TEXT        NOT NULL CHECK (char_length(btrim(title)) BETWEEN 1 AND 300),
    report_type                TEXT        NOT NULL DEFAULT 'completion',
    outcome                    TEXT        NOT NULL DEFAULT 'completed',
    state                      TEXT        NOT NULL DEFAULT 'final',
    content                    TEXT        NOT NULL CHECK (char_length(btrim(content)) BETWEEN 1 AND 20000),
    source_kind                TEXT        NOT NULL DEFAULT 'codex',
    source_ref                 TEXT        CHECK (source_ref IS NULL OR char_length(source_ref) BETWEEN 1 AND 500),
    tags                       TEXT[]      NOT NULL DEFAULT '{}'::TEXT[],
    metadata_json              JSONB       NOT NULL DEFAULT '{}'::JSONB CHECK (jsonb_typeof(metadata_json) = 'object'),
    content_hash               TEXT        NOT NULL CHECK (content_hash ~ '^[a-f0-9]{64}$'),
    supersedes_report_id       BIGINT      REFERENCES public.dev_agent_workline_reports(id) ON DELETE RESTRICT,
    redaction_reason           TEXT        CHECK (redaction_reason IS NULL OR char_length(btrim(redaction_reason)) BETWEEN 3 AND 500),
    created_by                 INTEGER     REFERENCES public.system_users(id) ON DELETE SET NULL,
    created                    TIMESTAMPTZ NOT NULL DEFAULT now(),
    state_changed              TIMESTAMPTZ NOT NULL DEFAULT now(),
    format_version             SMALLINT    NOT NULL DEFAULT 1,
    phase_gate                 TEXT,
    workline_status_snapshot   TEXT,
    changed_this_turn          BOOLEAN,
    context_text               TEXT,
    plain_language_text        TEXT,
    technical_text             TEXT,
    next_step_text             TEXT,
    snapshot_json              JSONB       NOT NULL DEFAULT '{}'::JSONB,
    git_head_commit            TEXT,
    git_worktree_state         TEXT,
    git_has_other_changes      BOOLEAN,
    git_workline_changed_paths TEXT[]      NOT NULL DEFAULT '{}'::TEXT[],
    current_phase              SMALLINT    NOT NULL DEFAULT 0,
    CONSTRAINT ck_dev_agent_workline_reports_type
        CHECK (report_type IN ('completion', 'progress', 'decision', 'closure')),
    CONSTRAINT ck_dev_agent_workline_reports_outcome
        CHECK (outcome IN ('completed', 'partial', 'blocked', 'no_change', 'decision')),
    CONSTRAINT ck_dev_agent_workline_reports_state
        CHECK (state IN ('final', 'superseded', 'redacted', 'archived')),
    CONSTRAINT ck_dev_agent_workline_reports_source_kind
        CHECK (source_kind ~ '^[a-z][a-z0-9_-]{0,39}$'),
    CONSTRAINT ck_dev_agent_workline_reports_not_self_superseding
        CHECK (supersedes_report_id IS NULL OR supersedes_report_id <> id),
    CONSTRAINT ck_dev_agent_workline_reports_format_version
        CHECK (format_version IN (1, 2)),
    CONSTRAINT ck_dev_agent_workline_reports_phase_gate
        CHECK (phase_gate IS NULL OR phase_gate IN ('2', '3-4', '5-6')),
    CONSTRAINT ck_dev_agent_workline_reports_status_snapshot
        CHECK (workline_status_snapshot IS NULL OR workline_status_snapshot IN ('active', 'paused', 'closed', 'archived')),
    CONSTRAINT ck_dev_agent_workline_reports_snapshot_json
        CHECK (jsonb_typeof(snapshot_json) = 'object'),
    CONSTRAINT ck_dev_agent_workline_reports_git_head
        CHECK (git_head_commit IS NULL OR git_head_commit ~ '^[a-f0-9]{7,64}$'),
    CONSTRAINT ck_dev_agent_workline_reports_git_state
        CHECK (git_worktree_state IS NULL OR git_worktree_state IN ('clean', 'dirty', 'unknown')),
    CONSTRAINT ck_dev_agent_workline_reports_git_scope
        CHECK (
            git_has_other_changes IS NULL
            OR (git_worktree_state = 'clean' AND git_has_other_changes = FALSE
                AND cardinality(git_workline_changed_paths) = 0)
            OR (git_worktree_state = 'dirty'
                AND (git_has_other_changes = TRUE OR cardinality(git_workline_changed_paths) > 0))
        ),
    CONSTRAINT ck_dev_agent_workline_reports_current_phase
        CHECK (current_phase BETWEEN 0 AND 6),
    CONSTRAINT ck_dev_agent_workline_reports_structured_shape
        CHECK (
            format_version = 1
            OR state = 'redacted'
            OR (
                phase_gate IS NOT NULL
                AND workline_status_snapshot IS NOT NULL
                AND changed_this_turn IS NOT NULL
                AND context_text IS NOT NULL
                AND char_length(btrim(context_text)) BETWEEN 1 AND 4000
                AND plain_language_text IS NOT NULL
                AND char_length(btrim(plain_language_text)) BETWEEN 1 AND 6000
                AND technical_text IS NOT NULL
                AND char_length(btrim(technical_text)) BETWEEN 1 AND 8000
                AND jsonb_typeof(snapshot_json) = 'object'
                AND git_head_commit IS NOT NULL
                AND git_worktree_state IS NOT NULL
                AND git_has_other_changes IS NOT NULL
                AND (
                    (workline_status_snapshot IN ('active', 'paused')
                        AND next_step_text IS NOT NULL
                        AND char_length(btrim(next_step_text)) BETWEEN 1 AND 4000)
                    OR (workline_status_snapshot IN ('closed', 'archived')
                        AND next_step_text IS NULL)
                )
            )
        )
);

ALTER TABLE public.dev_agent_workline_reports
    ADD COLUMN IF NOT EXISTS format_version SMALLINT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS phase_gate TEXT,
    ADD COLUMN IF NOT EXISTS workline_status_snapshot TEXT,
    ADD COLUMN IF NOT EXISTS changed_this_turn BOOLEAN,
    ADD COLUMN IF NOT EXISTS context_text TEXT,
    ADD COLUMN IF NOT EXISTS plain_language_text TEXT,
    ADD COLUMN IF NOT EXISTS technical_text TEXT,
    ADD COLUMN IF NOT EXISTS next_step_text TEXT,
    ADD COLUMN IF NOT EXISTS snapshot_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    ADD COLUMN IF NOT EXISTS git_head_commit TEXT,
    ADD COLUMN IF NOT EXISTS git_worktree_state TEXT,
    ADD COLUMN IF NOT EXISTS git_has_other_changes BOOLEAN,
    ADD COLUMN IF NOT EXISTS git_workline_changed_paths TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
    ADD COLUMN IF NOT EXISTS current_phase SMALLINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.dev_agent_workline_tasks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workline_id BIGINT      NOT NULL REFERENCES public.dev_agent_worklines(id) ON DELETE CASCADE,
    task_id     INTEGER     NOT NULL REFERENCES public.dev_agent_tasks(id) ON DELETE CASCADE,
    created_by  INTEGER     REFERENCES public.system_users(id) ON DELETE SET NULL,
    created     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_dev_agent_workline_tasks UNIQUE (workline_id, task_id)
);

CREATE TABLE IF NOT EXISTS public.dev_agent_handover_reports (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                  TEXT        NOT NULL CHECK (char_length(btrim(title)) BETWEEN 1 AND 300),
    state                  TEXT        NOT NULL DEFAULT 'final',
    source_kind            TEXT        NOT NULL DEFAULT 'codex',
    source_ref             TEXT        CHECK (source_ref IS NULL OR char_length(source_ref) BETWEEN 1 AND 500),
    tags                   TEXT[]      NOT NULL DEFAULT '{}'::TEXT[],
    metadata_json          JSONB       NOT NULL DEFAULT '{}'::JSONB CHECK (jsonb_typeof(metadata_json) = 'object'),
    membership_hash        TEXT        NOT NULL CHECK (membership_hash ~ '^[a-f0-9]{64}$'),
    supersedes_handover_id BIGINT      REFERENCES public.dev_agent_handover_reports(id) ON DELETE RESTRICT,
    created_by             INTEGER     REFERENCES public.system_users(id) ON DELETE SET NULL,
    created                TIMESTAMPTZ NOT NULL DEFAULT now(),
    state_changed          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_dev_agent_handover_reports_state
        CHECK (state IN ('final', 'superseded', 'archived')),
    CONSTRAINT ck_dev_agent_handover_reports_source_kind
        CHECK (source_kind ~ '^[a-z][a-z0-9_-]{0,39}$'),
    CONSTRAINT ck_dev_agent_handover_reports_not_self_superseding
        CHECK (supersedes_handover_id IS NULL OR supersedes_handover_id <> id)
);

CREATE TABLE IF NOT EXISTS public.dev_agent_handover_report_items (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    handover_report_id BIGINT      NOT NULL REFERENCES public.dev_agent_handover_reports(id) ON DELETE RESTRICT,
    workline_id        BIGINT      NOT NULL REFERENCES public.dev_agent_worklines(id) ON DELETE RESTRICT,
    workline_report_id BIGINT      NOT NULL REFERENCES public.dev_agent_workline_reports(id) ON DELETE RESTRICT,
    sort_order         INTEGER     NOT NULL CHECK (sort_order BETWEEN 1 AND 200),
    created            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_dev_agent_handover_report_items_workline UNIQUE (handover_report_id, workline_id),
    CONSTRAINT uq_dev_agent_handover_report_items_report UNIQUE (handover_report_id, workline_report_id),
    CONSTRAINT uq_dev_agent_handover_report_items_order UNIQUE (handover_report_id, sort_order)
);

CREATE TABLE IF NOT EXISTS public.dev_agent_release_goals (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_key   TEXT        NOT NULL CHECK (identity_key ~ '^[a-z0-9][a-z0-9._-]{1,79}$'),
    version        INTEGER     NOT NULL CHECK (version >= 1),
    title          TEXT        NOT NULL CHECK (char_length(btrim(title)) BETWEEN 1 AND 300),
    outcome        TEXT        NOT NULL CHECK (char_length(btrim(outcome)) BETWEEN 1 AND 2000),
    decision_state TEXT        NOT NULL DEFAULT 'draft',
    is_selected    BOOLEAN     NOT NULL DEFAULT FALSE,
    created_by     INTEGER     REFERENCES public.system_users(id) ON DELETE SET NULL,
    locked_by      INTEGER     REFERENCES public.system_users(id) ON DELETE SET NULL,
    created        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated        TIMESTAMPTZ NOT NULL DEFAULT now(),
    locked_at      TIMESTAMPTZ,
    CONSTRAINT uq_dev_agent_release_goals_identity_version UNIQUE (identity_key, version),
    CONSTRAINT ck_dev_agent_release_goals_state CHECK (decision_state IN ('draft', 'locked')),
    CONSTRAINT ck_dev_agent_release_goals_lock_shape CHECK (
        (decision_state = 'draft' AND locked_at IS NULL)
        OR (decision_state = 'locked' AND locked_at IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS public.dev_agent_release_goal_contracts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_goal_id BIGINT      NOT NULL REFERENCES public.dev_agent_release_goals(id) ON DELETE RESTRICT,
    workline_id     BIGINT      NOT NULL REFERENCES public.dev_agent_worklines(id) ON DELETE RESTRICT,
    completion_rule TEXT        NOT NULL,
    target_phase    SMALLINT,
    created_by      INTEGER     REFERENCES public.system_users(id) ON DELETE SET NULL,
    created         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_dev_agent_release_goal_contracts_workline UNIQUE (release_goal_id, workline_id),
    CONSTRAINT ck_dev_agent_release_goal_contracts_rule CHECK (
        completion_rule IN ('must_complete', 'must_remain_incomplete', 'must_be_in_phase', 'must_not_start', 'outside_release')
    ),
    CONSTRAINT ck_dev_agent_release_goal_contracts_target_phase CHECK (
        (target_phase IS NULL OR target_phase BETWEEN 0 AND 6)
        AND (completion_rule <> 'must_be_in_phase' OR target_phase IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_dev_agent_worklines_status_updated
    ON public.dev_agent_worklines (status, updated DESC);
CREATE INDEX IF NOT EXISTS idx_dev_agent_worklines_tags
    ON public.dev_agent_worklines USING GIN (tags);
CREATE INDEX IF NOT EXISTS idx_dev_agent_worklines_status_changed
    ON public.dev_agent_worklines (status_changed_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_dev_agent_workline_reports_workline_created
    ON public.dev_agent_workline_reports (workline_id, created DESC);
CREATE INDEX IF NOT EXISTS idx_dev_agent_workline_reports_state_created
    ON public.dev_agent_workline_reports (state, created DESC);
CREATE INDEX IF NOT EXISTS idx_dev_agent_workline_reports_tags
    ON public.dev_agent_workline_reports USING GIN (tags);
CREATE INDEX IF NOT EXISTS idx_dev_agent_workline_tasks_task
    ON public.dev_agent_workline_tasks (task_id, workline_id);
CREATE INDEX IF NOT EXISTS idx_dev_agent_handover_reports_state_created
    ON public.dev_agent_handover_reports (state, created DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_dev_agent_handover_report_items_workline
    ON public.dev_agent_handover_report_items (workline_id, handover_report_id DESC);
CREATE INDEX IF NOT EXISTS idx_dev_agent_handover_report_items_report
    ON public.dev_agent_handover_report_items (workline_report_id, handover_report_id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_dev_agent_release_goals_selected
    ON public.dev_agent_release_goals (is_selected) WHERE is_selected = TRUE;
CREATE INDEX IF NOT EXISTS idx_dev_agent_release_goal_contracts_workline
    ON public.dev_agent_release_goal_contracts (workline_id, release_goal_id);

CREATE OR REPLACE FUNCTION public.set_dev_agent_worklines_updated_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.protect_dev_agent_workline_report_history()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.state = 'redacted' AND NEW IS DISTINCT FROM OLD THEN
        RAISE EXCEPTION 'redacted workline reports are terminal';
    END IF;

    IF NEW.state = 'redacted' AND OLD.state <> 'redacted' THEN
        IF NEW.title <> 'Redacted report'
           OR NEW.content <> '[redacted]'
           OR NEW.source_ref IS NOT NULL
           OR NEW.tags <> '{}'::TEXT[]
           OR NEW.metadata_json <> '{}'::JSONB
           OR NEW.context_text IS NOT NULL
           OR NEW.plain_language_text IS NOT NULL
           OR NEW.technical_text IS NOT NULL
           OR NEW.next_step_text IS NOT NULL
           OR NEW.snapshot_json <> '{}'::JSONB
           OR NEW.git_workline_changed_paths <> '{}'::TEXT[]
           OR NEW.redaction_reason IS NULL THEN
            RAISE EXCEPTION 'workline report redaction must remove all free-form fields';
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.workline_id IS DISTINCT FROM OLD.workline_id
       OR NEW.title IS DISTINCT FROM OLD.title
       OR NEW.report_type IS DISTINCT FROM OLD.report_type
       OR NEW.outcome IS DISTINCT FROM OLD.outcome
       OR NEW.content IS DISTINCT FROM OLD.content
       OR NEW.source_kind IS DISTINCT FROM OLD.source_kind
       OR NEW.source_ref IS DISTINCT FROM OLD.source_ref
       OR NEW.tags IS DISTINCT FROM OLD.tags
       OR NEW.metadata_json IS DISTINCT FROM OLD.metadata_json
       OR NEW.content_hash IS DISTINCT FROM OLD.content_hash
       OR NEW.supersedes_report_id IS DISTINCT FROM OLD.supersedes_report_id
       OR NEW.redaction_reason IS DISTINCT FROM OLD.redaction_reason
       OR NEW.created_by IS DISTINCT FROM OLD.created_by
       OR NEW.created IS DISTINCT FROM OLD.created
       OR NEW.format_version IS DISTINCT FROM OLD.format_version
       OR NEW.phase_gate IS DISTINCT FROM OLD.phase_gate
       OR NEW.current_phase IS DISTINCT FROM OLD.current_phase
       OR NEW.workline_status_snapshot IS DISTINCT FROM OLD.workline_status_snapshot
       OR NEW.changed_this_turn IS DISTINCT FROM OLD.changed_this_turn
       OR NEW.context_text IS DISTINCT FROM OLD.context_text
       OR NEW.plain_language_text IS DISTINCT FROM OLD.plain_language_text
       OR NEW.technical_text IS DISTINCT FROM OLD.technical_text
       OR NEW.next_step_text IS DISTINCT FROM OLD.next_step_text
       OR NEW.snapshot_json IS DISTINCT FROM OLD.snapshot_json
       OR NEW.git_head_commit IS DISTINCT FROM OLD.git_head_commit
       OR NEW.git_worktree_state IS DISTINCT FROM OLD.git_worktree_state
       OR NEW.git_has_other_changes IS DISTINCT FROM OLD.git_has_other_changes
       OR NEW.git_workline_changed_paths IS DISTINCT FROM OLD.git_workline_changed_paths THEN
        RAISE EXCEPTION 'workline report bodies are immutable';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.protect_dev_agent_handover_report_history()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.title IS DISTINCT FROM OLD.title
       OR NEW.source_kind IS DISTINCT FROM OLD.source_kind
       OR NEW.source_ref IS DISTINCT FROM OLD.source_ref
       OR NEW.tags IS DISTINCT FROM OLD.tags
       OR NEW.metadata_json IS DISTINCT FROM OLD.metadata_json
       OR NEW.membership_hash IS DISTINCT FROM OLD.membership_hash
       OR NEW.supersedes_handover_id IS DISTINCT FROM OLD.supersedes_handover_id
       OR NEW.created_by IS DISTINCT FROM OLD.created_by
       OR NEW.created IS DISTINCT FROM OLD.created THEN
        RAISE EXCEPTION 'handover report manifests are immutable';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.protect_dev_agent_release_goal_contracts()
RETURNS TRIGGER AS $$
DECLARE
    resolved_goal_id BIGINT;
    resolved_state TEXT;
BEGIN
    resolved_goal_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.release_goal_id ELSE NEW.release_goal_id END;
    SELECT decision_state INTO resolved_state
      FROM public.dev_agent_release_goals
     WHERE id = resolved_goal_id;
    IF resolved_state = 'locked' THEN
        RAISE EXCEPTION 'locked release goal contracts are immutable';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.protect_dev_agent_release_goal_lock()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.decision_state = 'locked' THEN
        IF NEW.identity_key IS DISTINCT FROM OLD.identity_key
           OR NEW.version IS DISTINCT FROM OLD.version
           OR NEW.title IS DISTINCT FROM OLD.title
           OR NEW.outcome IS DISTINCT FROM OLD.outcome
           OR NEW.decision_state IS DISTINCT FROM OLD.decision_state
           OR NEW.created_by IS DISTINCT FROM OLD.created_by
           OR NEW.locked_by IS DISTINCT FROM OLD.locked_by
           OR NEW.created IS DISTINCT FROM OLD.created
           OR NEW.locked_at IS DISTINCT FROM OLD.locked_at THEN
            RAISE EXCEPTION 'locked release goal identity is immutable';
        END IF;
        RETURN NEW;
    END IF;
    IF NEW.decision_state = 'locked' THEN
        IF EXISTS (
            SELECT 1
              FROM public.dev_agent_worklines AS worklines
             WHERE worklines.status = 'active'
               AND NOT EXISTS (
                    SELECT 1
                      FROM public.dev_agent_release_goal_contracts AS contracts
                     WHERE contracts.release_goal_id = NEW.id
                       AND contracts.workline_id = worklines.id
               )
        ) THEN
            RAISE EXCEPTION 'every active workline must be classified before locking a release goal';
        END IF;
        NEW.locked_at := COALESCE(NEW.locked_at, now());
    END IF;
    NEW.updated := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_dev_agent_worklines_updated ON public.dev_agent_worklines;
CREATE TRIGGER set_dev_agent_worklines_updated
    BEFORE UPDATE ON public.dev_agent_worklines
    FOR EACH ROW EXECUTE FUNCTION public.set_dev_agent_worklines_updated_timestamp();
DROP TRIGGER IF EXISTS protect_dev_agent_workline_report_history ON public.dev_agent_workline_reports;
CREATE TRIGGER protect_dev_agent_workline_report_history
    BEFORE UPDATE ON public.dev_agent_workline_reports
    FOR EACH ROW EXECUTE FUNCTION public.protect_dev_agent_workline_report_history();
DROP TRIGGER IF EXISTS protect_dev_agent_handover_report_history ON public.dev_agent_handover_reports;
CREATE TRIGGER protect_dev_agent_handover_report_history
    BEFORE UPDATE ON public.dev_agent_handover_reports
    FOR EACH ROW EXECUTE FUNCTION public.protect_dev_agent_handover_report_history();
DROP TRIGGER IF EXISTS protect_dev_agent_release_goal_contracts ON public.dev_agent_release_goal_contracts;
CREATE TRIGGER protect_dev_agent_release_goal_contracts
    BEFORE INSERT OR UPDATE OR DELETE ON public.dev_agent_release_goal_contracts
    FOR EACH ROW EXECUTE FUNCTION public.protect_dev_agent_release_goal_contracts();
DROP TRIGGER IF EXISTS protect_dev_agent_release_goal_lock ON public.dev_agent_release_goals;
CREATE TRIGGER protect_dev_agent_release_goal_lock
    BEFORE UPDATE ON public.dev_agent_release_goals
    FOR EACH ROW EXECUTE FUNCTION public.protect_dev_agent_release_goal_lock();

COMMENT ON TABLE public.dev_agent_worklines IS
    'Stable development work identities shared by reports and optional ticket links.';
COMMENT ON TABLE public.dev_agent_workline_reports IS
    'Append-first workline reports whose body is immutable after creation.';
COMMENT ON TABLE public.dev_agent_handover_reports IS
    'Immutable handover manifests referencing exact workline report versions.';
COMMENT ON TABLE public.dev_agent_release_goals IS
    'Versioned release decisions and their explicit workline completion contracts.';
