-- 20261005000035_add_row_group_classifications.sql
-- Adds multilingual headings above the existing reusable row-group values.
-- Connects heading-aware selection and facets without changing membership identity.
-- Exists so one heading widens a selection and different headings narrow it.
-- VERSION_DB: 9.10.0
-- VERSION_DB_OWNER: 20261005000099_record_database_release_9_10_0.sql
-- COMPLETION_MARKER: wl103_row_group_classifications

CREATE TABLE IF NOT EXISTS public.system_row_group_classifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9][a-z0-9_-]{0,63}$'),
    title jsonb NOT NULL CHECK (jsonb_typeof(title) = 'object' AND title <> '{}'::jsonb),
    is_single boolean NOT NULL DEFAULT false,
    sort_order integer NOT NULL DEFAULT 0 CHECK (sort_order BETWEEN -100000 AND 100000),
    enabled boolean NOT NULL DEFAULT true,
    created timestamptz NOT NULL DEFAULT now(),
    updated timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.system_row_groups ADD COLUMN IF NOT EXISTS classification_id bigint
    REFERENCES public.system_row_group_classifications(id) ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_system_row_groups_classification
    ON public.system_row_groups (classification_id, sort_order);

COMMENT ON TABLE public.system_row_group_classifications IS
    'Multilingual classification headings. Writes require the administrator row-group API; headings never grant row access.';
COMMENT ON COLUMN public.system_row_group_classifications.is_single IS
    'Class permits one value per row; category permits several. Fixed after creation by the administrator API.';
COMMENT ON COLUMN public.system_row_group_classifications.enabled IS
    'Disabling a heading hides all its values and removes their selection, preserving assignments.';
COMMENT ON COLUMN public.system_row_groups.classification_id IS
    'Optional heading; NULL values share one untitled group. Deletion of a used heading is restricted.';

CREATE OR REPLACE FUNCTION public.set_system_row_group_classifications_updated_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger
        WHERE tgname = 'update_system_row_group_classifications_timestamp'
          AND tgrelid = 'public.system_row_group_classifications'::regclass) THEN
        CREATE TRIGGER update_system_row_group_classifications_timestamp
            BEFORE UPDATE ON public.system_row_group_classifications
            FOR EACH ROW EXECUTE FUNCTION public.set_system_row_group_classifications_updated_timestamp();
    END IF;
END $$;

INSERT INTO public.system_data_repair_records (migration, action, detail)
SELECT 'wl103_row_group_classifications', 'completed',
       jsonb_build_object('file', '20261005000035_add_row_group_classifications.sql')
WHERE NOT EXISTS (SELECT 1 FROM public.system_data_repair_records
    WHERE migration = 'wl103_row_group_classifications' AND action = 'completed');
