-- 20260929000005_seed_missing_media_check_language_keys.sql
-- Seeds the copy of the missing media files section of the media maintenance screen.
-- Bridges the section (missing_media_check_panel.js, its result printer and
-- missing_media_check_translation_fallbacks.js) with the language keys of the
-- installation.
-- Exists because the copy of the section was written by a startup routine, which ran
-- at every server start outside the migrations and the public bootstrap, filled the
-- key columns without a description or the reviewed Finnish and English rows, and
-- knew nothing of the settings, notices and details this release adds. The routine
-- is retired: this file seeds its keys in the same wording, and the new keys. Only
-- the two keys of the unused-file list it wrote are reworded, to files no
-- recognised reference uses, because a picture linked from free text is not
-- recognised and such a file is not safe to remove unseen.
-- A nonempty translation is never overwritten; only the exact wording of the
-- routine listed in step 1 gives way. Running the file again changes nothing. The
-- public bootstrap runs this same file, so a new installation receives the same rows.
-- Finnish and English are served from the columns of system_lang_keys and are
-- mirrored into the normalized table as reviewed copy. Chinese (ch) and
-- Cantonese (yue) fill only their own columns, as the earlier seeds do: they
-- are not a review of the zh-CN, zh-TW or zh-HK locales.
-- VERSION_DB: 9.9.2
-- VERSION_DB_OWNER: 20260929000006_record_database_release_9_9_2.sql

-- 1. The wording the retired startup routine wrote for the unused-file list,
--    withdrawn where a site still holds exactly it. It then counts as missing
--    copy and is filled in step 2 like any empty value. Any other text, a
--    reviewed translation included, stays as it is.
WITH superseded_copy(lang_key, fi, en, ch, yue) AS (
    VALUES
        ('missing_media_check_unused_files_setting', 'Kerro myös tiedostoista, joita mikään rivi ei käytä', 'Also report files that no row uses', '同时报告没有任何行使用的文件', '同時報告冇任何行用緊嘅檔案'),
        ('missing_media_check_unused_files', 'Käyttämättömiä tiedostoja', 'Unused files', '未使用的文件', '冇用到嘅檔案')
), withdrawn_translations AS (
    DELETE FROM public.system_lang_key_translations AS stored
    USING public.system_lang_keys AS keys, superseded_copy AS superseded
    WHERE keys.id = stored.lang_key_id
      AND keys.lang_key = superseded.lang_key
      AND ((stored.language_code = 'fi' AND stored.translation = superseded.fi)
        OR (stored.language_code = 'en' AND stored.translation = superseded.en))
    RETURNING stored.lang_key_id
)
UPDATE public.system_lang_keys AS keys
SET fi = CASE WHEN keys.fi = superseded.fi THEN NULL ELSE keys.fi END,
    en = CASE WHEN keys.en = superseded.en THEN NULL ELSE keys.en END,
    ch = CASE WHEN keys.ch = superseded.ch THEN NULL ELSE keys.ch END,
    yue = CASE WHEN keys.yue = superseded.yue THEN NULL ELSE keys.yue END,
    updated = now()
FROM superseded_copy AS superseded
WHERE keys.lang_key = superseded.lang_key
  AND (keys.fi = superseded.fi OR keys.en = superseded.en
    OR keys.ch = superseded.ch OR keys.yue = superseded.yue);

-- 2. Add the missing keys, fill only empty columns, and mirror the served Finnish
--    and English into the normalized table where a row is missing.
WITH authored_keys(lang_key, fi, en, ch, yue, creation_spec) AS (
    VALUES
        -- Heading, actions and status (missing_media_check_panel.js).
        ('missing_media_check',
         'Puuttuvat mediatiedostot',
         'Missing media files',
         '缺失的媒体文件',
         '唔見咗嘅媒體檔案',
         'Missing media files check on the media maintenance screen: heading of the section.'),
        ('missing_media_check_description',
         'Tarkistaa, ovatko rivien käyttämät kuvat ja liitteet yhä levyllä. Ei korjaa eikä poista mitään, vaan kertoo mikä puuttuu.',
         'Checks whether the pictures and attachments that rows use are still on disk. It repairs nothing and deletes nothing; it only reports what is missing.',
         '检查各行所使用的图片和附件是否仍在磁盘上。它不会修复或删除任何内容，只报告缺失的文件。',
         '檢查各行用緊嘅圖片同附件係咪仲喺磁碟上。佢唔會修復或者刪除任何嘢，只係報告咩唔見咗。',
         'Missing media files check on the media maintenance screen: explanation under the heading of what the check does, and that it repairs and deletes nothing.'),
        ('missing_media_check_run_now',
         'Tarkista nyt',
         'Check now',
         '立即检查',
         '即刻檢查',
         'Missing media files check on the media maintenance screen: button that starts a check now.'),
        ('missing_media_check_save_settings',
         'Tallenna asetukset',
         'Save settings',
         '保存设置',
         '儲存設定',
         'Missing media files check on the media maintenance screen: button that saves the settings of the check.'),
        ('missing_media_check_settings_saved',
         'Asetukset tallennettu.',
         'Settings saved.',
         '设置已保存。',
         '設定已儲存。',
         'Missing media files check on the media maintenance screen: status after the settings were saved.'),
        ('missing_media_check_running',
         'Tarkistus on käynnissä…',
         'The check is running…',
         '检查进行中…',
         '檢查進行緊…',
         'Missing media files check on the media maintenance screen: status while a check runs.'),
        ('missing_media_check_never_run',
         'Tarkistusta ei ole vielä ajettu.',
         'The check has not run yet.',
         '检查尚未运行。',
         '檢查仲未執行過。',
         'Missing media files check on the media maintenance screen: shown in place of the result when the check has never run.'),
        ('missing_media_check_disabled',
         'Tarkistus on poistettu käytöstä asetuksista.',
         'The check is switched off in the settings.',
         '该检查已在设置中关闭。',
         '呢個檢查喺設定入面已經閂咗。',
         'Missing media files check on the media maintenance screen: status when a check was asked for while the check is switched off in its settings.'),
        ('missing_media_check_settings_problem',
         'Tallennettuja asetuksia ei voitu lukea, joten näkyvissä ovat oletusarvot eikä tarkistusta ajeta. Asetusten tallentaminen korvaa tallennetun arvon.',
         'The stored settings could not be read, so the shipped defaults are shown and the check does not run. Saving the settings replaces the stored value.',
         '无法读取已保存的设置，因此显示的是默认值，检查也不会运行。保存设置会替换已保存的值。',
         '讀取唔到已儲存嘅設定，所以而家顯示緊預設值，檢查亦唔會執行。儲存設定會取代已儲存嘅值。',
         'Missing media files check on the media maintenance screen: notice that the stored settings cannot be read, so the defaults are shown and the check does not run until the settings are saved again.'),
        -- Every setting of the check, in the order the section shows them.
        ('missing_media_check_enabled_setting',
         'Tarkistus käytössä',
         'Check switched on',
         '启用检查',
         '開啟檢查',
         'Missing media files check on the media maintenance screen: setting that switches the whole check on or off.'),
        ('missing_media_check_max_rows_setting',
         'Rivien yläraja yhdessä ajossa',
         'Row limit for one run',
         '单次运行的行数上限',
         '單次執行嘅行數上限',
         'Missing media files check on the media maintenance screen: setting of the most rows one run checks, shared between the datasets.'),
        ('missing_media_check_min_rows_setting',
         'Tarkistettavia rivejä vähintään kustakin aineistosta',
         'Rows checked at least in each dataset',
         '每个数据集至少检查的行数',
         '每個資料集最少檢查嘅行數',
         'Missing media files check on the media maintenance screen: setting of the fewest rows checked in each dataset while the row limit allows it.'),
        ('missing_media_check_sampling_setting',
         'Miten suuren aineiston rivit valitaan',
         'How rows of a large dataset are picked',
         '如何挑选大型数据集中的行',
         '點樣揀大型資料集入面嘅行',
         'Missing media files check on the media maintenance screen: setting of how the rows of a dataset too large to check completely are picked, also shown with the result.'),
        ('missing_media_check_sampling_even',
         'Tasaisesti vanhimmasta uusimpaan',
         'Evenly from oldest to newest',
         '从最旧到最新均匀挑选',
         '由最舊到最新平均咁揀',
         'Missing media files check on the media maintenance screen: sampling choice that spreads the checked rows evenly from the oldest row to the newest.'),
        ('missing_media_check_sampling_random',
         'Satunnaisesti',
         'At random',
         '随机挑选',
         '隨機揀',
         'Missing media files check on the media maintenance screen: sampling choice that picks the checked rows at random.'),
        ('missing_media_check_max_seconds_setting',
         'Aikaraja sekunteina',
         'Time limit in seconds',
         '时间上限（秒）',
         '時間上限（秒）',
         'Missing media files check on the media maintenance screen: setting of the most seconds one run may take.'),
        ('missing_media_check_run_after_update_setting',
         'Tarkista kerran jokaisen päivityksen jälkeen',
         'Check once after every update',
         '每次更新后检查一次',
         '每次更新之後檢查一次',
         'Missing media files check on the media maintenance screen: setting that runs the check once by itself after an application or database update.'),
        ('missing_media_check_run_on_startup_setting',
         'Tarkista jokaisella palvelimen käynnistyksellä',
         'Check at every server start',
         '每次服务器启动时检查',
         '每次伺服器啟動嗰陣檢查',
         'Missing media files check on the media maintenance screen: setting that runs the check every time the server starts.'),
        ('missing_media_check_startup_delay_setting',
         'Odotus palvelimen käynnistyksen jälkeen sekunteina',
         'Wait after the server starts, in seconds',
         '服务器启动后等待的秒数',
         '伺服器啟動之後等候嘅秒數',
         'Missing media files check on the media maintenance screen: setting of how many seconds an automatic check waits after the server has started.'),
        ('missing_media_check_exact_count_setting',
         'Yhden aineiston rivit lasketaan tarkasti enintään',
         'Rows counted exactly in one dataset, at most',
         '每个数据集最多精确计数的行数',
         '每個資料集最多準確計算嘅行數',
         'Missing media files check on the media maintenance screen: setting of how many rows of one dataset are counted exactly; a larger dataset is estimated.'),
        ('missing_media_check_unused_files_setting',
         'Kerro myös tiedostoista, joihin mikään tunnistettu viittaus ei osoita',
         'Also report files no recognised reference uses',
         '同时报告没有被任何已识别引用使用的文件',
         '同時報告冇任何已識別引用用到嘅檔案',
         'Missing media files check on the media maintenance screen: setting that also lists stored files no recognised reference uses, that is no media row and no picture field.'),
        ('missing_media_check_max_reported_missing_setting',
         'Puuttuvia tiedostoja luetellaan enintään',
         'Missing files listed, at most',
         '最多列出的缺失文件数',
         '最多列出嘅唔見咗檔案數目',
         'Missing media files check on the media maintenance screen: setting of how many missing files the stored result lists at most, also the limit of each list of card pictures.'),
        ('missing_media_check_max_reported_unused_setting',
         'Tiedostoja, joihin mikään tunnistettu viittaus ei osoita, luetellaan enintään',
         'Files no recognised reference uses, listed at most',
         '最多列出的没有被任何已识别引用使用的文件数',
         '最多列出嘅冇任何已識別引用用到嘅檔案數目',
         'Missing media files check on the media maintenance screen: setting of how many files no recognised reference uses the stored result lists at most.'),
        -- Summary of the last check (missing_media_check_result_printer.js).
        ('missing_media_check_last_run',
         'Viimeisin tarkistus',
         'Last check',
         '上次检查',
         '上次檢查',
         'Missing media files check on the media maintenance screen: label of the local time the last check finished.'),
        ('missing_media_check_trigger',
         'Käynnistäjä',
         'Started by',
         '启动方式',
         '啟動方式',
         'Missing media files check on the media maintenance screen: label of what started the last check, followed by an administrator, the server start or an update.'),
        ('missing_media_check_trigger_manual',
         'ylläpitäjä',
         'an administrator',
         '管理员',
         '管理員',
         'Missing media files check on the media maintenance screen: shown after Started by when an administrator started the last check.'),
        ('missing_media_check_trigger_startup',
         'palvelimen käynnistys',
         'the server start',
         '服务器启动',
         '伺服器啟動',
         'Missing media files check on the media maintenance screen: shown after Started by when the server start started the last check.'),
        ('missing_media_check_trigger_update',
         'päivitys',
         'an update',
         '更新',
         '更新',
         'Missing media files check on the media maintenance screen: shown after Started by when an application or database update started the last check.'),
        ('missing_media_check_app_version',
         'Sovelluksen versio',
         'Application version',
         '应用程序版本',
         '應用程式版本',
         'Missing media files check on the media maintenance screen: label of the application version the last check ran on.'),
        ('missing_media_check_db_version',
         'Tietokannan versio',
         'Database version',
         '数据库版本',
         '資料庫版本',
         'Missing media files check on the media maintenance screen: label of the database version the last check ran on.'),
        ('missing_media_check_datasets_checked',
         'Tarkistettuja aineistoja',
         'Datasets checked',
         '已检查的数据集',
         '已檢查嘅資料集',
         'Missing media files check on the media maintenance screen: label of how many of the datasets that hold media the last check reached.'),
        ('missing_media_check_rows_checked',
         'Tarkistettuja rivejä',
         'Rows checked',
         '已检查的行数',
         '已檢查嘅行數',
         'Missing media files check on the media maintenance screen: label of how many of the media rows the last check read.'),
        ('missing_media_check_missing_files',
         'Puuttuvia tiedostoja',
         'Missing files',
         '缺失的文件',
         '唔見咗嘅檔案',
         'Missing media files check on the media maintenance screen: label of how many files the last check found missing.'),
        ('missing_media_check_card_pictures_checked',
         'Tarkistettuja korttikuvia',
         'Card pictures checked',
         '已检查的卡片图片',
         '已檢查嘅卡片圖片',
         'Missing media files check on the media maintenance screen: label of how many values of picture fields the last check read, the card picture and every other field a card can show a picture from.'),
        ('missing_media_check_missing_card_pictures',
         'Puuttuvia korttikuvia',
         'Missing card pictures',
         '缺失的卡片图片',
         '唔見咗嘅卡片圖片',
         'Missing media files check on the media maintenance screen: label of how many pictures of picture fields the last check found missing, also the heading of their list in the details.'),
        ('missing_media_check_unused_files',
         'Tiedostoja, joihin mikään tunnistettu viittaus ei osoita',
         'Files no recognised reference uses',
         '没有被任何已识别引用使用的文件',
         '冇任何已識別引用用到嘅檔案',
         'Missing media files check on the media maintenance screen: label of how many stored files no recognised reference uses, that is no media row and no picture field, also the heading of their list.'),
        ('missing_media_check_all_present',
         'Jokainen tarkistettu tiedosto löytyi levyltä.',
         'Every checked file was found on disk.',
         '所有已检查的文件都在磁盘上找到。',
         '所有已檢查嘅檔案都喺磁碟上搵到。',
         'Missing media files check on the media maintenance screen: result when no checked file was missing and every card picture could be checked.'),
        ('missing_media_check_legacy_filename',
         'vanha tiedostonimimuoto',
         'retired filename form',
         '旧的文件名格式',
         '舊嘅檔案名格式',
         'Missing media files check on the media maintenance screen: tag on a missing file whose row stores the retired flat filename form.'),
        ('missing_media_check_unresolved_reference',
         'viittausta ei voi paikantaa levyltä',
         'the reference cannot be placed on disk',
         '无法在磁盘上定位该引用',
         '喺磁碟上定位唔到呢個引用',
         'Missing media files check on the media maintenance screen: tag on a row whose stored reference names no place in storage.'),
        -- Notices about how far the last check reached.
        ('missing_media_check_run_failed',
         'Viimeisin tarkistus epäonnistui ennen kuin se valmistui. Syyt ovat alla olevissa tiedoissa.',
         'The last check failed before it finished. The reasons are in the details below.',
         '上次检查在完成前失败。原因见下方详情。',
         '上次檢查喺完成之前失敗咗。原因喺下面嘅詳情入面。',
         'Missing media files check on the media maintenance screen: notice that the last check failed before it finished, with the reasons in the details.'),
        ('missing_media_check_datasets_exceed_budget',
         'Aineistoja on enemmän kuin työmäärän yläraja sallii rivejä, joten osa aineistoista jäi kokonaan tarkistamatta. Nosta ylärajaa.',
         'There are more datasets than the work limit allows rows, so some datasets were not checked at all. Raise the limit.',
         '数据集数量超过了工作量上限所允许的行数，因此有些数据集完全没有被检查。请提高上限。',
         '資料集嘅數量多過工作量上限容許嘅行數，所以有啲資料集完全冇檢查過。請調高上限。',
         'Missing media files check on the media maintenance screen: notice that there are more datasets than the row limit allows rows, so some datasets were not checked at all.'),
        ('missing_media_check_minimum_not_met',
         'Rivien yläraja oli liian pieni, jotta jokaisesta aineistosta olisi tarkistettu vähimmäismäärä rivejä.',
         'The row limit was too small to check the minimum number of rows in every dataset.',
         '行数上限太小，无法在每个数据集中检查最少行数。',
         '行數上限太細，冇辦法喺每個資料集檢查最少嘅行數。',
         'Missing media files check on the media maintenance screen: notice that the row limit was too small for the minimum number of rows in every dataset.'),
        ('missing_media_check_time_budget_reached',
         'Aikaraja tuli vastaan, joten tarkistus jäi kesken.',
         'The time limit was reached, so the check stopped early.',
         '已达到时间上限，因此检查提前停止。',
         '已經到咗時間上限，所以檢查提早停咗。',
         'Missing media files check on the media maintenance screen: notice that the time limit stopped the last check early.'),
        ('missing_media_check_row_budget_reached',
         'Työmäärän yläraja tuli vastaan: tarkistettiin otos, ei kaikkia rivejä.',
         'The work limit was reached: a sample was checked instead of every row.',
         '已达到工作量上限：检查的是样本，而不是全部行。',
         '已經到咗工作量上限：檢查嘅係樣本，唔係全部行。',
         'Missing media files check on the media maintenance screen: notice that the row limit made the last check read a sample instead of every row.'),
        ('missing_media_check_row_count_estimated',
         'Osa aineistoista on niin suuria, että niiden rivimäärä arvioitiin laskematta, joten niitä ei koskaan ilmoiteta kokonaan tarkistetuiksi.',
         'Some datasets are so large that their rows were estimated instead of counted, so they are never reported as fully checked.',
         '有些数据集太大，其行数是估算而非计数得出的，因此它们永远不会被报告为已完全检查。',
         '有啲資料集太大，佢哋嘅行數係估算出嚟而唔係數出嚟，所以佢哋永遠唔會被報告為完全檢查過。',
         'Missing media files check on the media maintenance screen: notice that some datasets were estimated instead of counted and are therefore never reported as fully checked.'),
        ('missing_media_check_card_pass_incomplete',
         'Korttikuvien tarkistus pysähtyi ennen kuin se oli lukenut jokaisen kuvakentän, joten osa korttikuvista jäi tarkistamatta. Sen pysäytti rivien yläraja, aikaraja tai alla olevissa tiedoissa näkyvä virhe.',
         'The card picture check stopped before it had read every picture field, so some card pictures were not checked. The row limit, the time limit or an error shown in the details below stopped it.',
         '卡片图片检查在读完每个图片字段之前就停止了，因此有些卡片图片没有被检查。导致停止的是行数上限、时间上限或下方详情中显示的错误。',
         '卡片圖片檢查喺讀晒每個圖片欄位之前已經停咗，所以有啲卡片圖片冇檢查到。令佢停低嘅係行數上限、時間上限，或者下面詳情入面顯示嘅錯誤。',
         'Missing media files check on the media maintenance screen: notice that the check of card pictures and the other picture fields stopped before every field was read, because of the row limit, the time limit or an error.'),
        ('missing_media_check_missing_list_truncated',
         'Puuttuvista tiedostoista luetellaan vain ensimmäiset $count.',
         'Only the first $count missing files are listed.',
         '只列出前 $count 个缺失的文件。',
         '只列出頭 $count 個唔見咗嘅檔案。',
         'Missing media files check on the media maintenance screen: notice that only the first $count missing files are listed; $count is a number.'),
        ('missing_media_check_unused_list_truncated',
         'Tiedostoista, joihin mikään tunnistettu viittaus ei osoita, luetellaan vain ensimmäiset $count.',
         'Only the first $count files no recognised reference uses are listed.',
         '只列出前 $count 个没有被任何已识别引用使用的文件。',
         '只列出頭 $count 個冇任何已識別引用用到嘅檔案。',
         'Missing media files check on the media maintenance screen: notice that only the first $count files no recognised reference uses are listed; $count is a number.'),
        ('missing_media_check_unused_walk_incomplete',
         'Aikaraja loppui kesken sellaisten tiedostojen etsinnän, joihin mikään tunnistettu viittaus ei osoita, joten niiden luettelo on vajaa.',
         'The time limit ran out while files no recognised reference uses were being looked for, so their list is incomplete.',
         '查找没有被任何已识别引用使用的文件期间，时间上限已到，因此该列表不完整。',
         '搵緊冇任何已識別引用用到嘅檔案嗰陣，時間上限已經到咗，所以呢份清單唔完整。',
         'Missing media files check on the media maintenance screen: notice that the time limit ran out while files no recognised reference uses were looked for, so their list is incomplete.'),
        ('missing_media_check_unused_withheld_datasets_incomplete',
         'Tiedostoja, joihin mikään tunnistettu viittaus ei osoita, ei etsitty, koska kaikkia aineistoja ei tarkistettu kokonaan. Minkä tahansa aineiston rivi voi osoittaa mihin tahansa kansioon, joten luettelo edellyttää jokaisen aineiston ja jokaisen kuvakentän lukemista kokonaan.',
         'Files no recognised reference uses were not looked for, because not every dataset was checked completely. A row of any dataset can point into any folder, so that list needs every dataset and every picture field read in full.',
         '本次未查找“没有被任何已识别引用使用的文件”，因为并非每个数据集都已完全检查。任何数据集的行都可能指向任何文件夹，因此必须完整读取每个数据集和每个图片字段，才能列出这些文件。',
         '今次冇去搵「冇任何已識別引用用到嘅檔案」，因為唔係每個資料集都完全檢查過。任何資料集嘅行都可能指向任何資料夾，所以一定要完整讀晒每個資料集同每個圖片欄位，先可以列出呢啲檔案。',
         'Missing media files check on the media maintenance screen: notice that files no recognised reference uses were not looked for because not every dataset was checked completely; a row of any dataset can point into any folder.'),
        ('missing_media_check_unused_withheld_card_pass_incomplete',
         'Tiedostoja, joihin mikään tunnistettu viittaus ei osoita, ei etsitty, koska kaikkia kuvakenttiä ei luettu. Minkä tahansa aineiston rivi voi osoittaa mihin tahansa kansioon, joten luettelo edellyttää jokaisen aineiston ja jokaisen kuvakentän lukemista kokonaan.',
         'Files no recognised reference uses were not looked for, because not every picture field was read. A row of any dataset can point into any folder, so that list needs every dataset and every picture field read in full.',
         '本次未查找“没有被任何已识别引用使用的文件”，因为并非每个图片字段都已读取。任何数据集的行都可能指向任何文件夹，因此必须完整读取每个数据集和每个图片字段，才能列出这些文件。',
         '今次冇去搵「冇任何已識別引用用到嘅檔案」，因為唔係每個圖片欄位都讀過。任何資料集嘅行都可能指向任何資料夾，所以一定要完整讀晒每個資料集同每個圖片欄位，先可以列出呢啲檔案。',
         'Missing media files check on the media maintenance screen: notice that files no recognised reference uses were not looked for because the card picture check did not read every picture field; a row of any dataset can point into any folder.'),
        -- The collapsible details of the last check.
        ('missing_media_check_details',
         'Viimeisimmän tarkistuksen tiedot',
         'Details of the last check',
         '上次检查的详情',
         '上次檢查嘅詳情',
         'Missing media files check on the media maintenance screen: title of the collapsible block with the details of the last check.'),
        ('missing_media_check_errors',
         'Virheet',
         'Errors',
         '错误',
         '錯誤',
         'Missing media files check on the media maintenance screen: heading of the list of errors of the last check.'),
        ('missing_media_check_unreached_datasets',
         'Aineistot, joita ei tarkistettu',
         'Datasets that were not checked',
         '未被检查的数据集',
         '冇檢查到嘅資料集',
         'Missing media files check on the media maintenance screen: heading of the list of datasets of which the last check read no row, each with its reason.'),
        ('missing_media_check_unreached_lookup_failed',
         'sen tallennuskansiota ei löytynyt',
         'its storage folder could not be found',
         '找不到其存储文件夹',
         '搵唔到佢嘅儲存資料夾',
         'Missing media files check on the media maintenance screen: reason a dataset was not checked: the storage folder of the dataset could not be found.'),
        ('missing_media_check_unreached_count_failed',
         'sen rivejä ei voitu laskea',
         'its rows could not be counted',
         '无法统计其行数',
         '數唔到佢嘅行數',
         'Missing media files check on the media maintenance screen: reason a dataset was not checked: its rows could not be counted.'),
        ('missing_media_check_unreached_read_failed',
         'sen rivejä ei voitu lukea',
         'its rows could not be read',
         '无法读取其行',
         '讀取唔到佢嘅行',
         'Missing media files check on the media maintenance screen: reason a dataset was not checked: its rows could not be read.'),
        ('missing_media_check_unreached_time_limit',
         'aikaraja loppui ensin',
         'the time limit ran out first',
         '时间上限先到了',
         '時間上限先到咗',
         'Missing media files check on the media maintenance screen: reason a dataset was not checked: the time limit ran out before it.'),
        ('missing_media_check_unreached_no_budget',
         'rivien yläraja ei jättänyt sille rivejä',
         'the row limit left no rows for it',
         '行数上限没有给它留下任何行',
         '行數上限冇留低任何行畀佢',
         'Missing media files check on the media maintenance screen: reason a dataset was not checked: the row limit left no rows for it.'),
        ('missing_media_check_column_dataset',
         'Aineisto',
         'Dataset',
         '数据集',
         '資料集',
         'Missing media files check on the media maintenance screen: column heading of the dataset name in the table of datasets.'),
        ('missing_media_check_column_rows',
         'Rivejä',
         'Rows',
         '行数',
         '行數',
         'Missing media files check on the media maintenance screen: column heading of the number of media rows of a dataset.'),
        ('missing_media_check_column_planned',
         'Suunniteltu',
         'Planned',
         '计划',
         '計劃',
         'Missing media files check on the media maintenance screen: column heading of how many rows of a dataset the check planned to read.'),
        ('missing_media_check_column_checked',
         'Tarkistettu',
         'Checked',
         '已检查',
         '已檢查',
         'Missing media files check on the media maintenance screen: column heading of how many rows of a dataset were actually checked.'),
        ('missing_media_check_column_missing',
         'Puuttuu',
         'Missing',
         '缺失',
         '唔見咗',
         'Missing media files check on the media maintenance screen: column heading of how many files of a dataset were missing.'),
        ('missing_media_check_column_complete',
         'Kokonaan tarkistettu',
         'Fully checked',
         '已完全检查',
         '完全檢查過',
         'Missing media files check on the media maintenance screen: column heading of whether every row of a dataset was checked.'),
        ('missing_media_check_column_unused',
         'Ei tunnistettua viittausta',
         'No recognised reference',
         '无已识别引用',
         '冇已識別引用',
         'Missing media files check on the media maintenance screen: column heading of how many stored files of a dataset no recognised reference uses.'),
        ('missing_media_check_yes',
         'kyllä',
         'yes',
         '是',
         '係',
         'Missing media files check on the media maintenance screen: table value: every row of the dataset was checked.'),
        ('missing_media_check_no',
         'ei',
         'no',
         '否',
         '唔係',
         'Missing media files check on the media maintenance screen: table value: not every row of the dataset was checked.'),
        ('missing_media_check_estimated',
         'arvio',
         'estimated',
         '估算',
         '估算',
         'Missing media files check on the media maintenance screen: tag after a row count that is an estimate.'),
        ('missing_media_check_unused_skipped',
         'ei etsitty',
         'not looked for',
         '未查找',
         '冇搵',
         'Missing media files check on the media maintenance screen: shown in place of the number of files no recognised reference uses, in the summary and in the table of datasets, when they were not looked for because not every row and picture field that could use them was read.'),
        -- The card picture lists of the last check, in the details.
        ('missing_media_check_kept_card_pictures',
         'Toisen rivin kansiosta säilytetyt korttikuvat',
         'Card pictures kept from another row''s folder',
         '来自其他行文件夹并被保留的卡片图片',
         '嚟自其他行資料夾、仍然保留緊嘅卡片圖片',
         'Missing media files check on the media maintenance screen: heading of the list of card pictures whose file lies in the folder of another row and which the card keeps, followed by how many there are.'),
        ('missing_media_check_kept_card_pictures_explanation',
         'Tällainen korttikuva pysyy kortissa silloinkin, kun rivillä on omia kuvia, kunnes ylläpitäjä tyhjentää korttikuvakentän.',
         'Such a card picture stays on its card, even when the row has pictures of its own, until an administrator clears the card picture field.',
         '这类卡片图片会一直留在卡片上，即使该行有自己的图片也是如此，直到管理员清空卡片图片字段为止。',
         '呢類卡片圖片會一直留喺卡片上，就算嗰行有自己嘅圖片都係噉，直到管理員清空卡片圖片欄位為止。',
         'Missing media files check on the media maintenance screen: explanation under the list of card pictures kept from the folder of another row: such a picture stays until an administrator clears the card picture field.'),
        ('missing_media_check_unchecked_card_pictures',
         'Kuvat, joita ei voitu tarkistaa',
         'Pictures that could not be checked',
         '无法检查的图片',
         '檢查唔到嘅圖片',
         'Missing media files check on the media maintenance screen: label of how many pictures of picture fields the last check could not check, because a disk or permission error hid whether their file exists, shown only when there are any; also the heading of their list in the details, followed by how many there are.'),
        ('missing_media_check_unchecked_files',
         'Tiedostot, joita ei voitu tarkistaa',
         'Files that could not be checked',
         '无法检查的文件',
         '檢查唔到嘅檔案',
         'Missing media files check on the media maintenance screen: label of how many gallery and attachment files the last check could not check, because a disk or permission error hid whether the file exists, shown only when there are any; such files are not reported as missing.'),
        ('missing_media_check_unchecked_card_pictures_explanation',
         'Levy- tai käyttöoikeusvirhe esti selvittämästä, onko tiedosto olemassa, joten näitä kuvia ei ilmoiteta puuttuviksi.',
         'A disk or permission error kept the check from telling whether these files exist, so they are not reported as missing.',
         '磁盘或权限错误使检查无法确定这些文件是否存在，因此它们不会被报告为缺失。',
         '磁碟或者權限錯誤令檢查判斷唔到呢啲檔案係咪存在，所以佢哋唔會被報告為唔見咗。',
         'Missing media files check on the media maintenance screen: explanation under the list of pictures that could not be checked: a disk or permission error hid whether the file exists, so it is not reported as missing.'),
        ('missing_media_check_card_list_truncated',
         'Näistä luetellaan vain ensimmäiset $count.',
         'Only the first $count of these are listed.',
         '这里只列出前 $count 项。',
         '呢度只列出頭 $count 項。',
         'Missing media files check on the media maintenance screen: notice under a list of card pictures that only its first $count are listed; $count is a number.'),
        ('missing_media_check_unused_files_note',
         'Pelkästään vapaassa tekstissä, esimerkiksi kuvauksen sisällä, olevaa kuvalinkkiä ei tunnisteta, joten varmista jokainen luettelon tiedosto ennen kuin poistat sen. Tarkistus itse ei poista mitään.',
         'A picture linked only from free text, for example inside a description, is not recognised, so verify each file on this list before you remove it. The check itself never deletes anything.',
         '仅在自由文本中链接的图片，例如描述中的图片，不会被识别，因此在删除此列表中的文件之前，请先逐一核实。检查本身从不删除任何内容。',
         '只喺自由文字入面連結嘅圖片，例如描述入面嘅圖片，唔會被識別，所以刪除呢個清單入面嘅檔案之前，請先逐個核實。檢查本身從來唔會刪除任何嘢。',
         'Missing media files check on the media maintenance screen: note under the list of files no recognised reference uses: a picture linked only from free text is not recognised, so each file is to be verified before removal, and the check deletes nothing.'),
        ('missing_media_check_sampling_seed',
         'Satunnaisuuden siemen',
         'Random seed',
         '随机种子',
         '隨機種子',
         'Missing media files check on the media maintenance screen: label of the number that repeats the random sample of the last check.')
), written_keys AS (
    INSERT INTO public.system_lang_keys AS existing (lang_key, fi, en, ch, yue, creation_spec)
    SELECT lang_key, fi, en, ch, yue, creation_spec
    FROM authored_keys
    ON CONFLICT (lang_key) DO UPDATE
    SET fi = CASE WHEN NULLIF(btrim(existing.fi), '') IS NULL THEN EXCLUDED.fi ELSE existing.fi END,
        en = CASE WHEN NULLIF(btrim(existing.en), '') IS NULL THEN EXCLUDED.en ELSE existing.en END,
        ch = CASE WHEN NULLIF(btrim(existing.ch), '') IS NULL THEN EXCLUDED.ch ELSE existing.ch END,
        yue = CASE WHEN NULLIF(btrim(existing.yue), '') IS NULL THEN EXCLUDED.yue ELSE existing.yue END,
        creation_spec = CASE WHEN NULLIF(btrim(existing.creation_spec), '') IS NULL
                             THEN EXCLUDED.creation_spec ELSE existing.creation_spec END,
        updated = now()
    WHERE NULLIF(btrim(existing.fi), '') IS NULL
       OR NULLIF(btrim(existing.en), '') IS NULL
       OR NULLIF(btrim(existing.ch), '') IS NULL
       OR NULLIF(btrim(existing.yue), '') IS NULL
       OR NULLIF(btrim(existing.creation_spec), '') IS NULL
    RETURNING existing.id, existing.lang_key, existing.fi, existing.en
), served_keys AS (
    -- One statement does not read its own writes, so the keys as they read
    -- after it are the rows written above plus the rest of the authored keys.
    SELECT id, fi, en FROM written_keys
    UNION ALL
    SELECT keys.id, keys.fi, keys.en
    FROM public.system_lang_keys AS keys
    JOIN authored_keys USING (lang_key)
    WHERE keys.lang_key NOT IN (SELECT lang_key FROM written_keys)
)
INSERT INTO public.system_lang_key_translations (
    lang_key_id, language_code, translation, source_kind, review_status
)
SELECT served.id, copy.language_code, copy.translation, 'manual', 'approved'
FROM served_keys AS served
CROSS JOIN LATERAL (VALUES ('fi', served.fi), ('en', served.en)) AS copy(language_code, translation)
JOIN public.system_languages AS languages ON languages.language_code = copy.language_code
WHERE NULLIF(btrim(copy.translation), '') IS NOT NULL
ON CONFLICT (lang_key_id, language_code) DO NOTHING;
