// row_group_window_postgres_test.go
// Proves class replacement, idempotence, legacy stable keys and competing writes.
// Bridges exact released migrations with two independent disposable PostgreSQL connections.
// Exists to test lock snapshots and persistence that a mock database cannot establish.
package system_table_tools

import (
	"context"
	"database/sql"
	"errors"
	"os"
	"strings"
	"testing"
	"time"
)

func rowGroupWindowPostgres(t *testing.T) *sql.DB {
	t.Helper()
	db := sitePresentationDisposableDB(t) // Opt-in check occurs before any cluster or SQL access.
	fixture := `CREATE TABLE system_users(id bigint PRIMARY KEY);
 CREATE TABLE system_db_tables(table_uid integer PRIMARY KEY,table_name text,schema_name text);
 CREATE TABLE system_languages(language_code text PRIMARY KEY,is_default boolean);
 CREATE TABLE wl103_window_rows(id bigint PRIMARY KEY);
 INSERT INTO system_languages VALUES('fi',true),('en',false);
 INSERT INTO system_db_tables VALUES(103,'wl103_window_rows','public'),(104,'system_config','public');
 INSERT INTO wl103_window_rows SELECT generate_series(1,200);
 ALTER TABLE system_config ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
 INSERT INTO system_config(key) VALUES('wl103_setting');`
	if _, err := db.Exec(fixture); err != nil {
		t.Fatal(err)
	}
	for _, input := range []struct{ path, boundary string }{
		{"20260822000001_create_system_row_groups.sql", "WITH desired_tables"},
		{"20261005000035_add_row_group_classifications.sql", "INSERT INTO public.system_data_repair_records"},
	} {
		source, err := os.ReadFile("../../../server_tools/migrations/" + input.path)
		if err != nil {
			t.Fatal(err)
		}
		schema, _, found := strings.Cut(string(source), input.boundary)
		if !found {
			t.Fatalf("missing schema boundary: %s", input.path)
		}
		if _, err = db.Exec(schema); err != nil {
			t.Fatal(err)
		}
	}
	if _, err := db.Exec(`INSERT INTO system_row_group_classifications(slug,title,is_single) VALUES('transport','{"fi":"Matka"}',true);
  INSERT INTO system_row_groups(slug,title,classification_id,enabled) VALUES
   ('boat','{"fi":"Laiva"}',1,true),('train','{"fi":"Juna"}',1,true),('hidden','{"fi":"Piilossa"}',1,false);
  INSERT INTO system_row_groups(slug,title) VALUES('legacy','{"fi":"Vanha"}');`); err != nil {
		t.Fatal(err)
	}
	return db
}

func rowGroupWindowTx(t *testing.T, db *sql.DB, operation func(*sql.Tx) error) error {
	t.Helper()
	tx, err := db.BeginTx(context.Background(), &sql.TxOptions{Isolation: sql.LevelReadCommitted})
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback()
	if err = operation(tx); err != nil {
		return err
	}
	return tx.Commit()
}

func TestRowGroupWindowCatalogueCreatesUpdatesAndDefaultTitlePostgres(t *testing.T) {
	db := rowGroupWindowPostgres(t)
	for _, heading := range []bool{true, false} {
		body := `{"slug":"hotel","classification_id":2,"title":{"fi":"Hotelli","en":"Hotel"}}`
		if heading {
			body = `{"classification":{"slug":"stay","title":{"fi":"Majoitus","en":"Stay"},"is_single":false}}`
		}
		request, err := decodeCreateRowGroupRequest(strings.NewReader(body))
		if err != nil {
			t.Fatal(err)
		}
		if heading {
			request = *request.Classification
		}
		var result RowGroup
		err = rowGroupWindowTx(t, db, func(tx *sql.Tx) error {
			var err error
			result, err = saveRowGroupInDB(context.Background(), tx, request, heading)
			return err
		})
		if err != nil {
			t.Fatal(err)
		}
		order, enabled := -7, false
		err = rowGroupWindowTx(t, db, func(tx *sql.Tx) error {
			updated, err := saveRowGroupInDB(context.Background(), tx, createRowGroupRequest{ID: result.ID, Title: map[string]string{"fi": "Uusi", "en": "New"}, SortOrder: &order, Enabled: &enabled}, heading)
			if err == nil && (updated.Slug != request.Slug || updated.Enabled || updated.SortOrder != -7) {
				t.Fatalf("update: %+v", updated)
			}
			return err
		})
		if err != nil {
			t.Fatal(err)
		}
		err = rowGroupWindowTx(t, db, func(tx *sql.Tx) error {
			_, err := saveRowGroupInDB(context.Background(), tx, createRowGroupRequest{ID: result.ID, Title: map[string]string{"en": "Missing default"}}, heading)
			return err
		})
		if !errors.Is(err, errRowGroupLanguages) {
			t.Fatalf("missing default title: %v", err)
		}
	}
	var single bool
	if err := db.QueryRow(`SELECT is_single FROM system_row_group_classifications WHERE slug='stay'`).Scan(&single); err != nil || single {
		t.Fatalf("fixed type: %v, %v", single, err)
	}
}

func TestRowGroupWindowBulkAtomicIdempotentDisabledAndStableKeysPostgres(t *testing.T) {
	db := rowGroupWindowPostgres(t)
	ids := make([]int64, 200)
	for i := range ids {
		ids[i] = int64(i + 1)
	}
	request := rowGroupMembershipRequest{GroupID: 1, Dataset: "wl103_window_rows", RowIDs: ids}
	for i := 0; i < 2; i++ {
		if err := rowGroupWindowTx(t, db, func(tx *sql.Tx) error { return assignRowGroupInDB(context.Background(), tx, request) }); err != nil {
			t.Fatal(err)
		}
	}
	var count int
	if err := db.QueryRow(`SELECT count(*) FROM system_row_group_memberships`).Scan(&count); err != nil || count != 200 {
		t.Fatalf("idempotent bulk: %d %v", count, err)
	}
	request.GroupID = 2
	request.RowIDs = []int64{1, 999}
	err := rowGroupWindowTx(t, db, func(tx *sql.Tx) error { return assignRowGroupInDB(context.Background(), tx, request) })
	if !errors.Is(err, errRowAccessRows) {
		t.Fatalf("unknown row: %v", err)
	}
	if err := db.QueryRow(`SELECT count(*) FROM system_row_group_memberships WHERE group_id=1`).Scan(&count); err != nil || count != 200 {
		t.Fatalf("unknown row altered assignments: %d %v", count, err)
	}
	if _, err := db.Exec(`INSERT INTO system_row_group_memberships(group_id,table_uid,row_id) VALUES(3,103,1)`); err != nil {
		t.Fatal(err)
	}
	request.RowIDs = []int64{1}
	if err := rowGroupWindowTx(t, db, func(tx *sql.Tx) error { return assignRowGroupInDB(context.Background(), tx, request) }); err != nil {
		t.Fatal(err)
	}
	if err := db.QueryRow(`SELECT count(*) FROM system_row_group_memberships WHERE table_uid=103 AND row_id=1`).Scan(&count); err != nil || count != 1 {
		t.Fatalf("disabled peer not replaced: %d %v", count, err)
	}
	legacy, err := decodeRowGroupMembershipRequest(strings.NewReader(`{"group_id":4,"table_uid":104,"row_id":1}`))
	if err != nil {
		t.Fatal(err)
	}
	for i := 0; i < 2; i++ {
		if err := rowGroupWindowTx(t, db, func(tx *sql.Tx) error { return assignRowGroupInDB(context.Background(), tx, legacy) }); err != nil {
			t.Fatal(err)
		}
	}
	var key string
	if err := db.QueryRow(`SELECT target_stable_key FROM system_row_group_memberships WHERE group_id=4 AND table_uid=104`).Scan(&key); err != nil || key != "wl103_setting" {
		t.Fatalf("legacy stable key: %q %v", key, err)
	}
	// A restored setting may receive a new row ID: the same key updates one membership.
	if _, err := db.Exec(`UPDATE system_config SET id=2 WHERE key='wl103_setting'`); err != nil {
		t.Fatal(err)
	}
	legacy.RowID = 2
	legacy.RowIDs = []int64{2}
	if err := rowGroupWindowTx(t, db, func(tx *sql.Tx) error { return assignRowGroupInDB(context.Background(), tx, legacy) }); err != nil {
		t.Fatal(err)
	}
	if err := db.QueryRow(`SELECT count(*) FROM system_row_group_memberships WHERE group_id=4 AND table_uid=104 AND row_id=2 AND target_stable_key='wl103_setting'`).Scan(&count); err != nil || count != 1 {
		t.Fatalf("stable upsert: %d %v", count, err)
	}
	if err := rowGroupWindowTx(t, db, func(tx *sql.Tx) error { return removeRowGroupInDB(context.Background(), tx, legacy) }); err != nil {
		t.Fatal(err)
	}
	if err := db.QueryRow(`SELECT count(*) FROM system_row_group_memberships WHERE table_uid=104`).Scan(&count); err != nil || count != 0 {
		t.Fatalf("legacy removal: %d %v", count, err)
	}
}

func TestRowGroupWindowClassConcurrencyBothOrdersAndPostDeletePostgres(t *testing.T) {
	db := rowGroupWindowPostgres(t)
	cases := []struct {
		name                  string
		first, second         int64
		firstPost, secondPost bool
		winner                int64
	}{
		{"boat then train", 1, 2, true, true, 2}, {"train then boat", 2, 1, true, true, 1},
		{"post then delete", 1, 1, true, false, 0}, {"delete then post", 1, 2, false, true, 2},
	}
	for _, test := range cases {
		t.Run(test.name, func(t *testing.T) {
			if _, err := db.Exec(`DELETE FROM system_row_group_memberships; INSERT INTO system_row_group_memberships(group_id,table_uid,row_id) VALUES(1,103,1)`); err != nil {
				t.Fatal(err)
			}
			ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
			defer cancel()
			firstConn, err := db.Conn(ctx)
			if err != nil {
				t.Fatal(err)
			}
			defer firstConn.Close()
			secondConn, err := db.Conn(ctx)
			if err != nil {
				t.Fatal(err)
			}
			defer secondConn.Close()
			first, err := firstConn.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelReadCommitted})
			if err != nil {
				t.Fatal(err)
			}
			defer first.Rollback()
			second, err := secondConn.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelReadCommitted})
			if err != nil {
				t.Fatal(err)
			}
			defer second.Rollback()
			request := rowGroupMembershipRequest{Dataset: "wl103_window_rows", RowIDs: []int64{1}, GroupID: test.first}
			if err := mutateRowGroupMembership(ctx, first, request, test.firstPost); err != nil {
				t.Fatal(err)
			}
			var pid int
			if err := second.QueryRowContext(ctx, `SELECT pg_backend_pid()`).Scan(&pid); err != nil {
				t.Fatal(err)
			}
			finished := make(chan error, 1)
			request.GroupID = test.second
			go func() {
				err := mutateRowGroupMembership(ctx, second, request, test.secondPost)
				if err == nil {
					err = second.Commit()
				}
				finished <- err
			}()
			// Observe the second connection waiting on the actual heading lock, not a timer guess.
			waiting := false
			for deadline := time.Now().Add(2 * time.Second); time.Now().Before(deadline); {
				var blocked bool
				if err := db.QueryRowContext(ctx, `SELECT EXISTS(SELECT 1 FROM pg_locks WHERE pid=$1 AND locktype='advisory' AND NOT granted)`, pid).Scan(&blocked); err != nil {
					t.Fatal(err)
				}
				if blocked {
					waiting = true
					break
				}
				select {
				case err := <-finished:
					t.Fatalf("second writer did not wait: %v", err)
				case <-time.After(10 * time.Millisecond):
				}
			}
			if !waiting {
				t.Fatal("second writer never reached the heading advisory lock")
			}
			if err := first.Commit(); err != nil {
				t.Fatal(err)
			}
			if err := <-finished; err != nil {
				t.Fatal(err)
			}
			var count int
			var winner int64
			if err := db.QueryRow(`SELECT count(*),COALESCE(max(group_id),0) FROM system_row_group_memberships WHERE table_uid=103 AND row_id=1`).Scan(&count, &winner); err != nil {
				t.Fatal(err)
			}
			if count > 1 || winner != test.winner {
				t.Fatalf("concurrent class has count=%d winner=%d; want <=1 / %d", count, winner, test.winner)
			}
		})
	}
}
