// add_row_relation_keys_postgres_test.go
// Proves non-id relation writes, upload caches and complete request rollback on PostgreSQL.
// Connects the real create orchestration and upload writer to the existing disposable fixture.
// Exists so default/generated keys, both bridge orientations and physical authorization
// are verified together. No test connects to an application's database.
package dtt_1_row_create

import (
	"bytes"
	"database/sql"
	"encoding/json"
	"mime/multipart"
	"net"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	backend "easelect/backend/core_components"
	"easelect/backend/core_components/dbutils"
	"easelect/backend/core_components/middlewares"
)

// Reuse WL124's cluster, account/read-policy fixture and session. Probe the socket
// boundary first so a sandbox without socket permission skips instead of failing.
func relationKeysPostgres(t *testing.T) *sql.DB {
	t.Helper()
	if os.Getenv("FILTEREST_TEST_DISPOSABLE_POSTGRES") != "1" {
		t.Skip("set FILTEREST_TEST_DISPOSABLE_POSTGRES=1")
	}
	listener, err := net.Listen("unix", filepath.Join(t.TempDir(), "probe"))
	if err != nil {
		if strings.Contains(err.Error(), "operation not permitted") || strings.Contains(err.Error(), "permission denied") {
			t.Skip("sandbox refuses disposable PostgreSQL Unix sockets")
		}
		t.Fatal(err)
	}
	_ = listener.Close()
	owner, _ := raceCluster(t)
	original := backend.Db
	backend.Db = owner
	t.Cleanup(func() { backend.Db = original })
	raceExec(t, owner, relationKeysFixture)
	return owner
}

const relationKeysFixture = `
ALTER TABLE system_db_tables ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;
UPDATE system_db_tables SET id = table_uid + 1000;
ALTER TABLE review_notes ADD COLUMN table_uid integer NOT NULL DEFAULT 9044 UNIQUE;
ALTER TABLE review_notes ADD COLUMN slug text GENERATED ALWAYS AS ('note-' || id::text) STORED UNIQUE;
ALTER TABLE review_notes ADD COLUMN nullable_key text UNIQUE;
ALTER TABLE review_notes ADD COLUMN uploaded_filename text;
CREATE TABLE linked_children (id integer PRIMARY KEY, parent_key integer REFERENCES review_notes(table_uid));
CREATE TABLE text_children (id integer PRIMARY KEY, parent_key text REFERENCES review_notes(slug));
CREATE TABLE owned_docs (id serial PRIMARY KEY, parent_key integer REFERENCES review_notes(table_uid), filename text);
CREATE TABLE owned_locations (id serial PRIMARY KEY, parent_key text REFERENCES review_notes(slug), position point);
CREATE TABLE linked_tags (id integer PRIMARY KEY, slug text NOT NULL DEFAULT '9044' UNIQUE, nullable_key text UNIQUE);
CREATE TABLE key_bridge (parent_key integer REFERENCES review_notes(table_uid), tag_key text REFERENCES linked_tags(slug));
CREATE TABLE null_bridge (parent_key integer REFERENCES review_notes(table_uid), tag_key text REFERENCES linked_tags(nullable_key));
INSERT INTO system_db_tables (id, table_uid, table_name) VALUES
 (1030,30,'linked_children'), (1031,31,'text_children'), (1032,32,'owned_docs'),
 (1033,33,'owned_locations'), (1040,40,'linked_tags'), (1041,41,'key_bridge'), (1042,42,'null_bridge');
INSERT INTO system_column_details (table_uid,column_name,insertable) VALUES (32,'filename',true),(33,'position',true);
INSERT INTO system_foreign_key_relations_1_m
 (id,source_table_uid,target_table_uid,source_column_name,target_column_name,target_insert_specs,insert_new_source_with_target) VALUES
 (50,30,20,'parent_key','table_uid','{}',false),
 (51,31,20,'parent_key','slug','{}',false),
 (52,32,20,'parent_key','table_uid',
  '{"file_upload":{"enabled":true,"profile_key":"attachment","allowed_file_types":["pdf"],"asset_kinds":["document"],"filename_column":"filename","cache_targets":[{"table":"review_notes","column":"uploaded_filename"}]}}',true),
 (53,33,20,'parent_key','slug','{}',true);
INSERT INTO system_foreign_key_relations_m_m
 (id,table_a_uid,table_b_uid,bridging_table_uid,bridging_col_a,bridging_col_b,table_a_column,table_b_column) VALUES
 (100,20,40,41,'parent_key','tag_key','table_uid','slug'),
 (101,40,20,41,'tag_key','parent_key','slug','table_uid'),
 (102,20,40,42,'parent_key','tag_key','table_uid','nullable_key');
INSERT INTO system_functions (id,url_route_endpoint) VALUES (12,'/api/update-row');
INSERT INTO system_group_table_func_rights (user_group_id,function_id,target_table_uid) VALUES
 (3,12,30),(3,12,31),(3,11,32),(3,11,33),(3,10,40),(3,11,41),(3,11,42);
INSERT INTO linked_children VALUES (7,NULL);
INSERT INTO text_children VALUES (8,NULL);
INSERT INTO linked_tags (id) VALUES (11);
-- Its reference key equals the physical id the new row will get, so an old id
-- cache write would touch this row. Its own physical id deliberately differs.
INSERT INTO review_notes (id,title,table_uid,uploaded_filename) VALUES (9044,'other parent',1,'untouched');
`

func TestCreateNonIDRelationsAndNestedUploadPostgres(t *testing.T) {
	db := relationKeysPostgres(t)
	request := raceRequest(t)
	for _, bridgeID := range []int64{100, 101} {
		t.Run("bridge orientation "+string(rune('A'+bridgeID-100)), func(t *testing.T) {
			tx, err := db.Begin()
			if err != nil {
				t.Fatal(err)
			}
			defer tx.Rollback()
			payload := map[string]interface{}{
				"title": "new parent",
				"_childRows": []ChildRowPayload{
					{RelationID: 52, Data: map[string]interface{}{}},
					{RelationID: 53, Data: map[string]interface{}{}},
				},
				"_existingLinks": []ExistingRelationLinkPayload{
					{RelationKind: existingRelationOneToMany, RelationID: 50, RowIDs: []int64{7}},
					{RelationKind: existingRelationOneToMany, RelationID: 51, RowIDs: []int64{8}},
					{RelationKind: existingRelationManyToMany, RelationID: bridgeID, RowIDs: []int64{11}},
				},
			}
			response := httptest.NewRecorder()
			id, children, err := insertDataAccordingToPayload(response, request, "review_notes", "20", payload, tx)
			if err != nil {
				t.Fatalf("create response=%d %s error=%v", response.Code, response.Body.String(), err)
			}
			var correct bool
			if err := tx.QueryRow(`SELECT
                (SELECT parent_key=9044 FROM linked_children WHERE id=7) AND
                (SELECT parent_key=p.slug FROM text_children WHERE id=8) AND
                (SELECT parent_key=9044 FROM owned_docs WHERE id=$2) AND
                (SELECT parent_key=p.slug AND position IS NULL FROM owned_locations WHERE id=$3) AND
                (SELECT parent_key=9044 AND tag_key='9044' FROM key_bridge)
                FROM review_notes p WHERE p.id=$1`, id, children[0].ChildRowID, children[1].ChildRowID).Scan(&correct); err != nil || !correct {
				t.Fatalf("stored reference checks=%v error=%v", correct, err)
			}
			var body bytes.Buffer
			writer := multipart.NewWriter(&body)
			part, err := writer.CreateFormFile("file_child_0", "fixture.pdf")
			if err != nil {
				t.Fatal(err)
			}
			_, _ = part.Write([]byte("%PDF-1.7\nsynthetic reference fixture\n"))
			_ = writer.Close()
			form, err := multipart.NewReader(&body, writer.Boundary()).ReadForm(1024)
			if err != nil {
				t.Fatal(err)
			}
			defer form.RemoveAll()
			if err := saveUploadedFiles(request.Context(), tx, response, form.File, t.TempDir(), "review_notes", "20", id, children); err != nil {
				t.Fatalf("upload response=%d %s error=%v", response.Code, response.Body.String(), err)
			}
			if err := tx.QueryRow(`SELECT p.uploaded_filename=d.filename AND
                (SELECT uploaded_filename='untouched' FROM review_notes WHERE id=9044)
                FROM review_notes p JOIN owned_docs d ON d.parent_key=p.table_uid WHERE p.id=$1`, id).Scan(&correct); err != nil || !correct {
				t.Fatalf("only intended upload cache changed=%v error=%v", correct, err)
			}
		})
	}
}

func TestCreateMissingReferenceRollsBackEarlierWritesPostgres(t *testing.T) {
	db := relationKeysPostgres(t)
	request := raceRequest(t)
	for _, missingParent := range []bool{false, true} {
		t.Run(map[bool]string{false: "related NULL after earlier links", true: "parent NULL after earlier child"}[missingParent], func(t *testing.T) {
			if missingParent {
				raceExec(t, db, `UPDATE system_foreign_key_relations_1_m SET target_column_name='nullable_key' WHERE id=53`)
			}
			tx, err := db.Begin()
			if err != nil {
				t.Fatal(err)
			}
			defer tx.Rollback()
			payload := map[string]interface{}{"title": "refused parent",
				"_childRows": []ChildRowPayload{{RelationID: 52, Data: map[string]interface{}{}}, {RelationID: 53, Data: map[string]interface{}{}}},
				"_existingLinks": []ExistingRelationLinkPayload{
					{RelationKind: existingRelationOneToMany, RelationID: 50, RowIDs: []int64{7}},
					{RelationKind: existingRelationManyToMany, RelationID: 100, RowIDs: []int64{11}},
					{RelationKind: existingRelationManyToMany, RelationID: 102, RowIDs: []int64{11}},
				}}
			response := httptest.NewRecorder()
			_, _, err = insertDataAccordingToPayload(response, request, "review_notes", "20", payload, tx)
			if err == nil || response.Code != 400 || !strings.Contains(response.Body.String(), "error_relation_reference_missing") {
				t.Fatalf("missing key refusal=%v response=%d %s", err, response.Code, response.Body.String())
			}
			if err := tx.Rollback(); err != nil {
				t.Fatal(err)
			}
			var clean bool
			if err := db.QueryRow(`SELECT
                (SELECT count(*)=1 FROM review_notes) AND
                (SELECT count(*)=0 FROM owned_docs) AND
                (SELECT count(*)=0 FROM owned_locations) AND
                (SELECT count(*)=0 FROM key_bridge) AND
                (SELECT count(*)=0 FROM null_bridge) AND
                (SELECT parent_key IS NULL FROM linked_children WHERE id=7)`).Scan(&clean); err != nil || !clean {
				t.Fatalf("full rollback=%v error=%v", clean, err)
			}
		})
	}
}

func TestCreateRelationAuthorizationUsesPhysicalIDPostgres(t *testing.T) {
	db := relationKeysPostgres(t)
	request := raceRequest(t)
	// A reference value that exists is not a selectable physical row identifier.
	var payload map[string]interface{}
	_ = json.Unmarshal([]byte(`{"title":"guessed key","_existingLinks":[{"relationKind":"many_to_many","relationId":100,"rowIds":[9044]}]}`), &payload)
	tx, err := db.Begin()
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback()
	response := httptest.NewRecorder()
	_, _, err = insertDataAccordingToPayload(response, request, "review_notes", "20", payload, tx)
	if err == nil || response.Code != 403 || !strings.Contains(response.Body.String(), relatedRowsUnreadable) {
		t.Fatalf("physical-id authorization refusal=%v response=%d %s", err, response.Code, response.Body.String())
	}
}

func TestCreateReadDeniedNonIDTargetMatchesMissingPostgres(t *testing.T) {
	db := relationKeysPostgres(t)
	originalBasic := backend.DbBasic
	backend.DbBasic = db
	defer func() { backend.DbBasic = originalBasic }()
	const secretReference = "private-reference-canary"
	raceExec(t, db, `UPDATE linked_tags SET slug=$1 WHERE id=11`, secretReference)
	raceExec(t, db, `INSERT INTO system_row_access_rules (table_uid,action_id,row_id,user_id,effect)
        VALUES (40,1,11,4,'deny')`)
	var exists bool
	if err := db.QueryRow(`SELECT EXISTS (SELECT 1 FROM linked_tags WHERE id=11 AND slug=$1)`, secretReference).Scan(&exists); err != nil || !exists {
		t.Fatalf("read-denied target must exist with its non-id key: %v %v", exists, err)
	}
	before := relationRowsSnapshot(t, db)
	request := raceRequest(t)
	var missingBody string
	for _, rowID := range []int64{99999, 11} {
		response := httptest.NewRecorder()
		handler := middlewares.WithLazyTransaction(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			tx, ok := dbutils.RequireTx(r.Context())
			if !ok {
				t.Fatal("request transaction did not start")
			}
			payload := map[string]interface{}{"title": "hidden reference",
				"_existingLinks": []ExistingRelationLinkPayload{
					{RelationKind: existingRelationManyToMany, RelationID: 100, RowIDs: []int64{rowID}},
				}}
			if _, _, err := insertDataAccordingToPayload(w, r, "review_notes", "20", payload, tx); err == nil {
				t.Fatal("unreadable related row was accepted")
			}
		}))
		handler.ServeHTTP(response, request)
		body := response.Body.String()
		if response.Code != http.StatusForbidden || !strings.Contains(body, relatedRowsUnreadable) || strings.Contains(body, secretReference) {
			t.Fatalf("unreadable related-row response=%d %s", response.Code, body)
		}
		if rowID == 99999 {
			missingBody = body
		} else if body != missingBody {
			t.Fatalf("read denial reveals whether the target exists: missing=%s denied=%s", missingBody, body)
		}
		if relationRowsSnapshot(t, db) != before {
			t.Fatal("read denial left main, child, bridge or cache writes")
		}
	}
}
