"""Verify independent article settings and legacy naming on disposable PostgreSQL.

Connects the canonical migration to real constraints, assignments and permission rows.
Protects existing site values, card choices and repeatable upgrades without live DB writes.
"""
from pathlib import Path
from test_field_settings_language_seed import database

MIGRATION = Path(__file__).resolve().parents[2] / "server_tools/migrations/20260908000004_add_article_view_and_field_settings.sql"
SCHEMA = """
CREATE TABLE system_languages (language_code text PRIMARY KEY);
INSERT INTO system_languages VALUES ('fi'), ('en'), ('zh-CN'), ('zh-TW'), ('zh-HK');
ALTER TABLE system_lang_key_translations ADD FOREIGN KEY (language_code) REFERENCES system_languages(language_code);
CREATE TABLE system_table_views (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text, view_key text UNIQUE, status text);
CREATE TABLE system_view_field_set_assignments (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint, group_id bigint,
 table_uid integer, view_id integer REFERENCES system_table_views(id), field_set_id bigint,
 group_priority integer DEFAULT 0, created_by bigint, created timestamptz DEFAULT now(), updated timestamptz DEFAULT now(),
 UNIQUE NULLS NOT DISTINCT (user_id,group_id,table_uid,view_id)
);
CREATE TABLE system_functions (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text UNIQUE, package text, disabled boolean,
 specific_table_related boolean, url_route_endpoint text, ui_only boolean,
 rate_limit_amount integer, rate_limit_minutes integer, creation_spec text
);
CREATE TABLE system_group_table_func_rights (
 user_group_id bigint, function_id bigint REFERENCES system_functions(id), target_schema_name text,
 target_table_uid integer, creation_spec text,
 UNIQUE NULLS NOT DISTINCT (user_group_id,function_id,target_schema_name,target_table_uid)
);
INSERT INTO system_table_views (name,view_key,status) VALUES ('card','card','active');
INSERT INTO system_functions(name,url_route_endpoint) VALUES ('ui.view.card','/ui/view/card'),
 ('ui.admin.view_field_assignments','/ui/admin/view_field_assignments');
INSERT INTO system_group_table_func_rights VALUES(8,1,'public',13,'existing scoped card'),(2,2,'public',NULL,'existing admin');
INSERT INTO system_view_field_set_assignments(user_id,group_id,table_uid,view_id,field_set_id)
 VALUES(NULL,NULL,13,1,100),(7,NULL,13,1,101),(NULL,8,13,1,102);
"""

def snapshot(database):
    return database("""SELECT jsonb_build_object(
        'views',(SELECT jsonb_agg(to_jsonb(v) ORDER BY id) FROM system_table_views v),
        'assignments',(SELECT jsonb_agg(to_jsonb(a) ORDER BY id) FROM system_view_field_set_assignments a),
        'rights',(SELECT jsonb_agg(to_jsonb(p) ORDER BY function_id,user_group_id) FROM system_group_table_func_rights p),
        'copy',(SELECT jsonb_agg(to_jsonb(k) ORDER BY id) FROM system_lang_keys k),
        'translations',(SELECT jsonb_agg(to_jsonb(t) ORDER BY lang_key_id,language_code) FROM system_lang_key_translations t),
        'versions',(SELECT jsonb_agg(to_jsonb(v)) FROM system_db_version v)
    )""")

def test_fresh_article_is_independent_and_migration_is_idempotent(database):
    database(SCHEMA)
    old = database("SELECT jsonb_agg(to_jsonb(a) ORDER BY id) FROM system_view_field_set_assignments a")
    database(MIGRATION.read_text())
    assert database("SELECT count(*) FROM system_table_views WHERE view_key='article_view'") == "1"
    assert database("SELECT jsonb_agg(to_jsonb(a) ORDER BY id) FROM system_view_field_set_assignments a") == old
    assert database("SELECT count(*) FROM system_group_table_func_rights") == "4"
    assert database("SELECT count(*) FROM system_lang_key_translations") == "4"
    first = snapshot(database)
    database(MIGRATION.read_text())
    assert snapshot(database) == first

def test_legacy_dimension_keeps_identity_settings_and_site_copy(database):
    database(SCHEMA)
    database("""
       INSERT INTO system_table_views(name,view_key,status) VALUES('Custom article','article','active'),('Legacy large card','big_card','active');
       INSERT INTO system_view_field_set_assignments(user_id,table_uid,view_id,field_set_id)
       VALUES(7,13,2,901),(9,13,3,902);
       INSERT INTO system_lang_keys(lang_key,fi,en,ch,yue,creation_spec)
       VALUES('view_field_settings','  Oma otsikko  ','Own settings','自訂','自訂','Own context');
    """)
    database(MIGRATION.read_text())
    assert database("SELECT id||':'||name FROM system_table_views WHERE view_key='article_view'") == "2:Custom article"
    assert database("SELECT field_set_id FROM system_view_field_set_assignments WHERE view_id=2 AND user_id=7") == "901"
    assert database("SELECT field_set_id FROM system_view_field_set_assignments WHERE view_id=2 AND user_id=9") == "902"
    assert database("SELECT '['||fi||']' FROM system_lang_keys WHERE lang_key='view_field_settings'") == "[  Oma otsikko  ]"
    first = snapshot(database)
    database(MIGRATION.read_text())
    assert snapshot(database) == first
