-- grant_catalogue.sql
-- Synthetic catalogue for a disposable PostgreSQL cluster only.
-- Exercises separate role identities and dependency discovery without live data.
-- Contains no application or installation credentials.
CREATE TABLE system_db_tables(id bigint PRIMARY KEY,table_uid bigint UNIQUE,table_name text,schema_name text,cached_oid bigint,fk_display_column text);
CREATE TABLE system_functions(id bigint PRIMARY KEY,url_route_endpoint text,disabled boolean,ui_only boolean,specific_table_related boolean);
CREATE TABLE system_user_groups(id bigint PRIMARY KEY,name text);
CREATE TABLE system_user_group_memberships(user_id bigint,group_id bigint,id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE TABLE system_group_table_func_rights(user_group_id bigint,function_id bigint,target_table_uid bigint,id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE TABLE system_users(id bigserial PRIMARY KEY,enabled boolean,name text,private text);
CREATE TABLE system_row_actor_columns(table_uid bigint,actor_role text,column_name text);
CREATE TABLE system_data_repair_records(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
ALTER TABLE system_data_repair_records ENABLE ROW LEVEL SECURITY;
CREATE TABLE system_row_groups(id bigserial PRIMARY KEY);
CREATE TABLE system_row_group_memberships(id bigserial PRIMARY KEY);
CREATE TABLE system_column_field_sets(id bigserial PRIMARY KEY);
CREATE TABLE system_column_field_set_members(id bigserial PRIMARY KEY);
CREATE TABLE system_view_field_set_assignments(id bigserial PRIMARY KEY);
CREATE TABLE system_dataset_sort_defaults(id bigserial PRIMARY KEY);
CREATE TABLE system_user_visual_preferences(id bigserial PRIMARY KEY);
CREATE TABLE system_media_assets(id bigint PRIMARY KEY);
CREATE TABLE system_media_asset_usages(created timestamptz,PRIMARY KEY(created));
CREATE TABLE deletion_log(id bigserial PRIMARY KEY);
CREATE TABLE system_embedding_refresh_jobs(id bigserial PRIMARY KEY);
CREATE TABLE dev_agent_worklines(id bigserial PRIMARY KEY);
CREATE TABLE system_triggers(source_table text,target_table text,action_values jsonb,id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE TABLE system_foreign_key_relations_1_m(source_table_uid bigint,target_table_uid bigint,source_column_name text,target_column_name text,cached_name_col_in_src text,insert_new_source_with_target boolean,target_insert_specs jsonb,id bigint);
CREATE TABLE system_foreign_key_relations_m_m(table_a_uid bigint,table_b_uid bigint,bridging_table_uid bigint,id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE TABLE fresh_target(id integer PRIMARY KEY,title text,private text);
CREATE TABLE fresh_source(id serial PRIMARY KEY,target_id integer REFERENCES fresh_target(id),title text,search_vector_simple tsvector,created_by bigint REFERENCES system_users(id));
CREATE TABLE owned_child(id serial PRIMARY KEY,parent_id integer REFERENCES fresh_source(id),filename text);
CREATE TABLE bridge(id serial PRIMARY KEY,a_id integer REFERENCES fresh_source(id),b_id integer REFERENCES fresh_target(id));
CREATE TABLE fresh_source_lang_embeddings(id bigint PRIMARY KEY,embedding text);
CREATE TABLE identity_content(id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,title text);
CREATE SEQUENCE legacy_shared_seq;
CREATE TABLE legacy_content(id integer DEFAULT nextval('legacy_shared_seq'),title text);
CREATE TABLE automation_destination(id serial PRIMARY KEY,title text);
CREATE VIEW account_view AS SELECT id,enabled,name FROM system_users;
CREATE VIEW nested_account_view AS SELECT id,enabled FROM account_view;
CREATE SCHEMA restricted;
CREATE TABLE restricted.users_restricted(id bigserial PRIMARY KEY);
CREATE TABLE restricted.verification_codes(id bigserial PRIMARY KEY);
CREATE TABLE restricted.otp_send_events(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY);
INSERT INTO system_db_tables VALUES
 (10,1,'fresh_source','public','fresh_source'::regclass::oid,NULL),
 (11,2,'fresh_target','public','fresh_target'::regclass::oid,NULL),
 (12,3,'owned_child','public','owned_child'::regclass::oid,NULL),
 (13,4,'bridge','public','bridge'::regclass::oid,NULL),
 (14,5,'identity_content','public','identity_content'::regclass::oid,NULL),
 (15,6,'legacy_content','public','legacy_content'::regclass::oid,NULL),
 (16,7,'automation_destination','public','automation_destination'::regclass::oid,NULL);
INSERT INTO system_user_groups VALUES(1,'admins'),(2,'users'),(3,'guests'),(4,'empty'),(5,'anonymous_extra');
INSERT INTO system_user_group_memberships VALUES(1,5);
INSERT INTO system_functions VALUES
 (1,'/api/get-results',false,false,true),
 (2,'/api/add-row-multipart',false,false,true),
 (3,'/api/update-row',false,false,true),
 (4,'/api/delete-rows',false,false,true),
 (5,'/api/get-filter-options',NULL,false,true),
 (6,'/api/get-columns',false,false,true),
 (7,'/api/retired',true,false,true);
INSERT INTO system_group_table_func_rights VALUES(4,1,1),(5,1,1),(2,2,1),(4,2,3),(4,2,4),(2,1,2),(4,2,5),(4,2,6),(2,6,2),(2,7,2);
INSERT INTO system_row_actor_columns VALUES(1,'creator','created_by');
INSERT INTO system_foreign_key_relations_1_m VALUES(3,1,'parent_id','id',NULL,true,'{"file_upload":{"filename_column":"filename","cache_targets":[]}}',1);
INSERT INTO system_foreign_key_relations_m_m VALUES(1,2,4);
INSERT INTO system_triggers VALUES('fresh_source','automation_destination','{"title":"fixture-only value"}');
-- Unregistered relation-sync rows cannot reach the application's UID joins.
-- Give them upload/cache metadata too: each row must be reported only once.
INSERT INTO system_foreign_key_relations_1_m VALUES
 (NULL,1,NULL,NULL,NULL,true,'{"file_upload":{"cache_targets":[{"table":"missing_cache","column":"title"}]}}',757),
 (3,NULL,'parent_id',NULL,NULL,true,'{"file_upload":{"cache_targets":true}}',758),
 (NULL,NULL,NULL,NULL,NULL,true,'{"file_upload":{"cache_targets":true}}',759);
INSERT INTO system_db_tables VALUES(760,NULL,'unregistered_metadata','public',NULL,NULL);
INSERT INTO system_foreign_key_relations_m_m VALUES(NULL,2,4,761),(1,NULL,4,762),(1,2,NULL,763);
INSERT INTO system_row_actor_columns VALUES(NULL,'owner',NULL);
INSERT INTO system_triggers VALUES(NULL,NULL,'{"title":"fixture-only value"}',764);
INSERT INTO fresh_target VALUES(1,'visible label','must not be disclosed');
INSERT INTO fresh_source(target_id,title) VALUES(1,'fixture row value');
