// runtime_role_write_revocations_postgres_test.go
// Proves the guest and privilege-editing revocations on a disposable PostgreSQL 16 cluster.
// Bridges a database shaped like serlog.com and the local development database with the startup step.
// Exists to show that exactly the intended rights disappear, that existing triggers keep firing,
// that repeated and simultaneous starts agree, and that an unsafe setup changes nothing.
package backend

import (
	"database/sql"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"testing"
)

const writeRevocationClusterRoles = `
CREATE ROLE guest_role LOGIN;
CREATE ROLE basic_role LOGIN;
CREATE ROLE readonly_role LOGIN;
CREATE ROLE confidential_role LOGIN;
CREATE ROLE granting_editor NOLOGIN;
`

// writeRevocationFixture reproduces the grants found on production and on the
// local development database: the guest writing starter datasets and their
// sequences, emptying tables and attaching triggers, a column-level write, a
// grant recorded under another grantor, default privileges that hand every
// future table to the guest, and the privilege-editing views with their
// trigger functions. It also holds what must keep working: an ordinary writable
// view, a definer-rights audit trigger and the row-access function.
const writeRevocationFixture = `
CREATE SCHEMA restricted;
CREATE TABLE public.notes (id serial PRIMARY KEY, title text);
CREATE TABLE public.tickets (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title text);
CREATE TABLE public.system_users (id integer PRIMARY KEY, username text);
CREATE TABLE public.note_audit (note_id integer, written_by text);
CREATE TABLE public.admin_managed (id integer);
CREATE TABLE restricted.users_restricted (user_id integer PRIMARY KEY, password_hash text);
CREATE VIEW public.recent_notes AS SELECT id, title FROM public.notes;

CREATE VIEW public.systemview_role_table_privileges AS
    SELECT grantee::text AS role_name, table_schema::text AS table_schema,
           table_name::text AS table_name, privilege_type::text AS privilege
    FROM information_schema.role_table_grants;
CREATE FUNCTION public.systemview_role_table_privileges_upd() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    EXECUTE format('GRANT %s ON %I.%I TO %I', NEW.privilege, NEW.table_schema, NEW.table_name, NEW.role_name);
    RETURN NEW;
END $$;
CREATE TRIGGER trg_role_table_privileges INSTEAD OF INSERT ON public.systemview_role_table_privileges
    FOR EACH ROW EXECUTE FUNCTION public.systemview_role_table_privileges_upd();
CREATE VIEW public.systemview_column_role_privileges_with_source AS
    SELECT grantee::text AS role_name, table_name::text AS table_name, column_name::text AS column_name
    FROM information_schema.column_privileges;
CREATE FUNCTION public.systemview_role_column_privileges_upd() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER AS $$ BEGIN RETURN NEW; END $$;
CREATE FUNCTION public.record_note_audit() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
BEGIN
    INSERT INTO public.note_audit (note_id, written_by) VALUES (NEW.id, session_user);
    RETURN NEW;
END $$;
CREATE TRIGGER trg_note_audit AFTER INSERT ON public.notes FOR EACH ROW EXECUTE FUNCTION public.record_note_audit();
CREATE FUNCTION public.resolve_effective_row_access() RETURNS boolean
    LANGUAGE sql SECURITY DEFINER SET search_path = pg_catalog, public AS $$ SELECT true $$;

GRANT USAGE ON SCHEMA public TO guest_role, basic_role, readonly_role, confidential_role;
GRANT USAGE ON SCHEMA restricted TO confidential_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.notes, public.tickets TO guest_role;
GRANT USAGE, SELECT ON SEQUENCE public.notes_id_seq TO guest_role;
GRANT TRUNCATE, REFERENCES, TRIGGER ON public.notes TO guest_role;
GRANT SELECT ON public.system_users, public.recent_notes TO guest_role;
GRANT UPDATE (username) ON public.system_users TO guest_role;
GRANT INSERT ON public.tickets TO granting_editor WITH GRANT OPTION;
SET ROLE granting_editor;
GRANT INSERT ON public.tickets TO guest_role;
RESET ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.notes, public.tickets, public.recent_notes TO basic_role;
GRANT TRIGGER ON public.tickets TO basic_role;
GRANT USAGE ON SEQUENCE public.notes_id_seq TO basic_role;
GRANT UPDATE (username) ON public.system_users TO basic_role;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON restricted.users_restricted TO confidential_role;
GRANT SELECT (id) ON public.system_users TO confidential_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.systemview_role_table_privileges,
    public.systemview_column_role_privileges_with_source TO guest_role, basic_role, confidential_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO guest_role, basic_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO guest_role;
`

// writeRevocationPrivilegeMatrix lists what each runtime role may do, written
// independently of the production statements so it can judge them.
const writeRevocationPrivilegeMatrix = `
WITH roles (name) AS (VALUES ('guest_role'), ('basic_role'), ('readonly_role'), ('confidential_role')),
relations AS (
    SELECT c.oid, c.relkind, format('%I.%I', n.nspname, c.relname) AS name
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname IN ('public', 'restricted') AND c.relkind IN ('r', 'v', 'S')
)
SELECT entry FROM (
    SELECT r.name || ' ' || rel.name || ' ' || p.name AS entry
    FROM roles r CROSS JOIN relations rel
    CROSS JOIN (VALUES ('SELECT'), ('INSERT'), ('UPDATE'), ('DELETE'), ('TRUNCATE'), ('REFERENCES'), ('TRIGGER')) AS p (name)
    WHERE rel.relkind <> 'S' AND has_table_privilege(r.name, rel.oid, p.name)
    UNION ALL
    SELECT r.name || ' ' || rel.name || '(' || a.attname || ') ' || p.name
    FROM roles r CROSS JOIN relations rel
    JOIN pg_attribute a ON a.attrelid = rel.oid AND a.attnum > 0 AND NOT a.attisdropped
    CROSS JOIN (VALUES ('SELECT'), ('INSERT'), ('UPDATE'), ('REFERENCES')) AS p (name)
    WHERE rel.relkind <> 'S' AND NOT has_table_privilege(r.name, rel.oid, p.name)
      AND has_column_privilege(r.name, rel.oid, a.attnum, p.name)
    UNION ALL
    SELECT r.name || ' ' || rel.name || ' ' || p.name
    FROM roles r CROSS JOIN relations rel
    CROSS JOIN (VALUES ('USAGE'), ('SELECT'), ('UPDATE')) AS p (name)
    WHERE rel.relkind = 'S' AND has_sequence_privilege(r.name, rel.oid, p.name)
    UNION ALL
    SELECT r.name || ' ' || format('%I.%I', n.nspname, f.proname) || ' EXECUTE'
    FROM roles r CROSS JOIN pg_proc f JOIN pg_namespace n ON n.oid = f.pronamespace
    WHERE n.nspname = 'public' AND has_function_privilege(r.name, f.oid, 'EXECUTE')
) AS matrix
ORDER BY entry`

type writeRevocationCluster struct {
	t      *testing.T
	socket string
	port   int
}

// startWriteRevocationCluster starts a disposable cluster whose initial
// superuser plays the administrator connection, and creates the runtime roles.
func startWriteRevocationCluster(t *testing.T) *writeRevocationCluster {
	t.Helper()
	if os.Getenv("FILTEREST_TEST_DISPOSABLE_POSTGRES") != "1" {
		t.Skip("set FILTEREST_TEST_DISPOSABLE_POSTGRES=1 to run isolated PostgreSQL verification")
	}
	root := t.TempDir()
	socket := filepath.Join(root, "socket")
	if err := os.Mkdir(socket, 0o700); err != nil {
		t.Fatal(err)
	}
	data := filepath.Join(root, "db")
	bin := "/usr/lib/postgresql/16/bin/"
	run := func(name string, args ...string) {
		t.Helper()
		if output, err := exec.Command(bin+name, args...).CombinedOutput(); err != nil {
			t.Fatalf("%s: %v: %s", name, err, output)
		}
	}
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("find an unused port: %v", err)
	}
	port := listener.Addr().(*net.TCPAddr).Port
	if err := listener.Close(); err != nil {
		t.Fatalf("release the port: %v", err)
	}
	run("initdb", "-D", data, "-A", "trust", "-U", "test_owner", "--no-locale", "--encoding=UTF8")
	t.Cleanup(func() {
		_, _ = exec.Command(bin+"pg_ctl", "-D", data, "-m", "immediate", "-w", "stop").CombinedOutput()
	})
	run("pg_ctl", "-D", data, "-l", filepath.Join(root, "postgres.log"),
		"-o", fmt.Sprintf("-h '' -k '%s' -p %d", socket, port), "-w", "start")

	cluster := &writeRevocationCluster{t: t, socket: socket, port: port}
	cluster.exec(cluster.open("test_owner", "postgres"), writeRevocationClusterRoles)

	t.Setenv("DB_GUEST_USER", "guest_role")
	t.Setenv("DB_BASIC_USER", "basic_role")
	t.Setenv("DB_READONLY_USER", "readonly_role")
	t.Setenv("DB_CONFIDENTIAL_USER", "confidential_role")
	t.Setenv("DB_ADMIN_USER", "test_owner")
	t.Setenv("DB_USER", "")
	return cluster
}

func (cluster *writeRevocationCluster) open(user, database string) *sql.DB {
	cluster.t.Helper()
	db, err := sql.Open("postgres", fmt.Sprintf("host=%s port=%d user=%s dbname=%s sslmode=disable",
		cluster.socket, cluster.port, user, database))
	if err != nil {
		cluster.t.Fatal(err)
	}
	cluster.t.Cleanup(func() { _ = db.Close() })
	return db
}

func (cluster *writeRevocationCluster) exec(db *sql.DB, statements string) {
	cluster.t.Helper()
	if _, err := db.Exec(statements); err != nil {
		cluster.t.Fatalf("%v\n%s", err, statements)
	}
}

// newDatabase creates a database loaded with the fixture and returns its
// administrator connection.
func (cluster *writeRevocationCluster) newDatabase(name string) *sql.DB {
	cluster.t.Helper()
	cluster.exec(cluster.open("test_owner", "postgres"), "CREATE DATABASE "+name)
	owner := cluster.open("test_owner", name)
	cluster.exec(owner, writeRevocationFixture)
	return owner
}

func writeRevocationMatrix(t *testing.T, db *sql.DB) map[string]bool {
	t.Helper()
	rows, err := db.Query(writeRevocationPrivilegeMatrix)
	if err != nil {
		t.Fatal(err)
	}
	defer rows.Close()
	matrix := map[string]bool{}
	for rows.Next() {
		var entry string
		if err := rows.Scan(&entry); err != nil {
			t.Fatal(err)
		}
		matrix[entry] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatal(err)
	}
	return matrix
}

func writeRevocationDifference(from, to map[string]bool) []string {
	var missing []string
	for entry := range from {
		if !to[entry] {
			missing = append(missing, entry)
		}
	}
	sort.Strings(missing)
	return missing
}

// expectedWriteRevocationLosses is everything stage 1 may take away in the
// fixture, and nothing else: the guest's writes and sequence use, every runtime
// role's writes on the two privilege-editing views, and EXECUTE on the three
// trigger functions that run with their owner's rights.
func expectedWriteRevocationLosses() []string {
	var losses []string
	for _, role := range []string{"guest_role", "basic_role", "readonly_role", "confidential_role"} {
		for _, function := range []string{"public.record_note_audit", "public.systemview_role_column_privileges_upd", "public.systemview_role_table_privileges_upd"} {
			losses = append(losses, role+" "+function+" EXECUTE")
		}
	}
	for _, role := range []string{"guest_role", "basic_role", "confidential_role"} {
		for _, view := range []string{"public.systemview_role_table_privileges", "public.systemview_column_role_privileges_with_source"} {
			for _, privilege := range []string{"INSERT", "UPDATE", "DELETE"} {
				losses = append(losses, role+" "+view+" "+privilege)
			}
		}
	}
	for _, privilege := range []string{"INSERT", "UPDATE", "DELETE", "TRUNCATE", "REFERENCES", "TRIGGER"} {
		losses = append(losses, "guest_role public.notes "+privilege)
	}
	for _, privilege := range []string{"INSERT", "UPDATE", "DELETE"} {
		losses = append(losses, "guest_role public.tickets "+privilege)
	}
	losses = append(losses, "guest_role public.system_users(username) UPDATE", "guest_role public.notes_id_seq USAGE")
	sort.Strings(losses)
	return losses
}

func requireWriteRevocationOutcome(t *testing.T, before, after map[string]bool) {
	t.Helper()
	if gained := writeRevocationDifference(after, before); len(gained) > 0 {
		t.Fatalf("rights gained: %v", gained)
	}
	lost := writeRevocationDifference(before, after)
	if want := expectedWriteRevocationLosses(); strings.Join(lost, "\n") != strings.Join(want, "\n") {
		t.Fatalf("rights lost:\n%s\nwant exactly:\n%s", strings.Join(lost, "\n"), strings.Join(want, "\n"))
	}
}

func TestGuestAndPrivilegeViewWriteRevocationsPostgres(t *testing.T) {
	cluster := startWriteRevocationCluster(t)
	owner := cluster.newDatabase("serlog_shape")
	before := writeRevocationMatrix(t, owner)

	if err := EnsureGuestAndPrivilegeViewWriteRevocations(owner); err != nil {
		t.Fatalf("first start: %v", err)
	}
	after := writeRevocationMatrix(t, owner)
	requireWriteRevocationOutcome(t, before, after)

	// A second start finds nothing to do and changes nothing.
	if err := EnsureGuestAndPrivilegeViewWriteRevocations(owner); err != nil {
		t.Fatalf("second start: %v", err)
	}
	if again := writeRevocationMatrix(t, owner); len(writeRevocationDifference(after, again))+len(writeRevocationDifference(again, after)) > 0 {
		t.Fatalf("second start changed rights: lost %v, gained %v", writeRevocationDifference(after, again), writeRevocationDifference(again, after))
	}

	guest := cluster.open("guest_role", "serlog_shape")
	basic := cluster.open("basic_role", "serlog_shape")

	// The guest still reads and writes nothing.
	var visibleNotes int
	if err := guest.QueryRow(`SELECT count(*) FROM public.notes`).Scan(&visibleNotes); err != nil {
		t.Fatalf("guest read: %v", err)
	}
	if _, err := guest.Exec(`INSERT INTO public.notes (title) VALUES ('from a visitor')`); err == nil || !strings.Contains(err.Error(), "permission denied") {
		t.Fatalf("guest insert error = %v, want permission denied", err)
	}

	// A signed-in user's write still fires the existing audit trigger, although
	// no runtime role may execute its function any more.
	if _, err := basic.Exec(`INSERT INTO public.notes (title) VALUES ('from a signed-in user')`); err != nil {
		t.Fatalf("basic insert: %v", err)
	}
	var audited int
	if err := owner.QueryRow(`SELECT count(*) FROM public.note_audit WHERE written_by = 'basic_role'`).Scan(&audited); err != nil || audited != 1 {
		t.Fatalf("audit rows for basic = %d (%v), want 1", audited, err)
	}
	if _, err := basic.Exec(`INSERT INTO public.recent_notes (title) VALUES ('through an ordinary view')`); err != nil {
		t.Fatalf("basic write through an ordinary view: %v", err)
	}
	var rowAccess bool
	if err := basic.QueryRow(`SELECT public.resolve_effective_row_access()`).Scan(&rowAccess); err != nil || !rowAccess {
		t.Fatalf("row-access function as basic = %v (%v), want true", rowAccess, err)
	}

	// Nor can a signed-in user reach the privilege-editing machinery, directly
	// or by attaching its function to a trigger of their own.
	if _, err := basic.Exec(`INSERT INTO public.systemview_role_table_privileges VALUES ('basic_role', 'public', 'admin_managed', 'SELECT')`); err == nil || !strings.Contains(err.Error(), "permission denied") {
		t.Fatalf("basic write to the privilege view error = %v, want permission denied", err)
	}
	if _, err := basic.Exec(`CREATE TRIGGER borrowed BEFORE INSERT ON public.tickets FOR EACH ROW EXECUTE FUNCTION public.systemview_role_table_privileges_upd()`); err == nil || !strings.Contains(err.Error(), "permission denied") {
		t.Fatalf("basic trigger on the definer function error = %v, want permission denied", err)
	}

	// Tables created later keep the guest's read default but none of its writes.
	cluster.exec(owner, `CREATE TABLE public.later_notes (id serial PRIMARY KEY, title text)`)
	for _, check := range []struct {
		query string
		want  bool
	}{
		{`SELECT has_table_privilege('guest_role', 'public.later_notes', 'SELECT')`, true},
		{`SELECT has_table_privilege('guest_role', 'public.later_notes', 'INSERT')`, false},
		{`SELECT has_sequence_privilege('guest_role', 'public.later_notes_id_seq', 'USAGE')`, false},
		{`SELECT has_table_privilege('basic_role', 'public.later_notes', 'INSERT')`, true},
	} {
		var got bool
		if err := owner.QueryRow(check.query).Scan(&got); err != nil || got != check.want {
			t.Fatalf("%s = %v (%v), want %v", check.query, got, err, check.want)
		}
	}

	// The administrator's privilege tooling still works.
	cluster.exec(owner, `INSERT INTO public.systemview_role_table_privileges VALUES ('basic_role', 'public', 'admin_managed', 'SELECT')`)
	var granted bool
	if err := owner.QueryRow(`SELECT has_table_privilege('basic_role', 'public.admin_managed', 'SELECT')`).Scan(&granted); err != nil || !granted {
		t.Fatalf("administrator grant through the privilege view = %v (%v), want true", granted, err)
	}
}

func TestGuestAndPrivilegeViewWriteRevocationsSimultaneousStartsPostgres(t *testing.T) {
	cluster := startWriteRevocationCluster(t)
	owner := cluster.newDatabase("simultaneous")
	before := writeRevocationMatrix(t, owner)

	var wait sync.WaitGroup
	errs := make([]error, 3)
	for index := range errs {
		instance := cluster.open("test_owner", "simultaneous")
		wait.Add(1)
		go func(index int, instance *sql.DB) {
			defer wait.Done()
			errs[index] = EnsureGuestAndPrivilegeViewWriteRevocations(instance)
		}(index, instance)
	}
	wait.Wait()
	for index, err := range errs {
		if err != nil {
			t.Fatalf("start %d: %v", index, err)
		}
	}
	requireWriteRevocationOutcome(t, before, writeRevocationMatrix(t, owner))
}

func TestGuestAndPrivilegeViewWriteRevocationsChangeNothingWhenUnsafePostgres(t *testing.T) {
	cluster := startWriteRevocationCluster(t)
	administrator := cluster.open("test_owner", "postgres")
	for _, testCase := range []struct {
		name      string
		database  string
		setup     string
		undo      string
		wantError string
	}{
		{
			name:      "the other roles rely on a right granted to PUBLIC",
			database:  "public_write",
			setup:     `GRANT INSERT ON public.tickets TO PUBLIC`,
			wantError: "readonly public.tickets INSERT",
		},
		{
			name:      "a runtime role inherits through membership",
			database:  "membership",
			setup:     `GRANT readonly_role TO basic_role`,
			undo:      `REVOKE readonly_role FROM basic_role`,
			wantError: "role inherits rights as a member of another role: basic",
		},
		{
			name:      "the guest is a superuser",
			database:  "superuser_guest",
			setup:     `ALTER ROLE guest_role SUPERUSER`,
			undo:      `ALTER ROLE guest_role NOSUPERUSER`,
			wantError: "role is a superuser: guest",
		},
		{
			// Row security alone keeps the data repair record to its owner role.
			name:      "the confidential role bypasses row security",
			database:  "bypassing_confidential",
			setup:     `ALTER ROLE confidential_role BYPASSRLS`,
			undo:      `ALTER ROLE confidential_role NOBYPASSRLS`,
			wantError: "role bypasses row security: confidential (confidential_role); remove it with ALTER ROLE <role> NOBYPASSRLS",
		},
		{
			name:      "the guest bypasses row security",
			database:  "bypassing_guest",
			setup:     `ALTER ROLE guest_role BYPASSRLS`,
			undo:      `ALTER ROLE guest_role NOBYPASSRLS`,
			wantError: "role bypasses row security: guest (guest_role)",
		},
	} {
		t.Run(testCase.name, func(t *testing.T) {
			owner := cluster.newDatabase(testCase.database)
			cluster.exec(owner, testCase.setup)
			if testCase.undo != "" {
				t.Cleanup(func() { _, _ = administrator.Exec(testCase.undo) })
			}
			before := writeRevocationMatrix(t, owner)

			err := EnsureGuestAndPrivilegeViewWriteRevocations(owner)
			if err == nil || !strings.Contains(err.Error(), testCase.wantError) {
				t.Fatalf("error = %v, want %q", err, testCase.wantError)
			}
			after := writeRevocationMatrix(t, owner)
			if lost, gained := writeRevocationDifference(before, after), writeRevocationDifference(after, before); len(lost)+len(gained) > 0 {
				t.Fatalf("a refused start changed rights: lost %v, gained %v", lost, gained)
			}
		})
	}
}

// The counterpart of the bypass refusal: the same role without the attribute
// starts normally, so the refusal is about the attribute and nothing else.
func TestGuestAndPrivilegeViewWriteRevocationsAcceptARoleOnceItNoLongerBypassesPostgres(t *testing.T) {
	cluster := startWriteRevocationCluster(t)
	administrator := cluster.open("test_owner", "postgres")
	owner := cluster.newDatabase("bypass_removed")
	cluster.exec(owner, `ALTER ROLE confidential_role BYPASSRLS`)
	t.Cleanup(func() { _, _ = administrator.Exec(`ALTER ROLE confidential_role NOBYPASSRLS`) })

	if err := EnsureGuestAndPrivilegeViewWriteRevocations(owner); err == nil ||
		!strings.Contains(err.Error(), "role bypasses row security: confidential") {
		t.Fatalf("error = %v, want the bypass refusal", err)
	}
	cluster.exec(owner, `ALTER ROLE confidential_role NOBYPASSRLS`)
	if err := EnsureGuestAndPrivilegeViewWriteRevocations(owner); err != nil {
		t.Fatalf("start refused once the role no longer bypasses row security: %v", err)
	}
}
