// favorites_postgres_test.go
// Exercises actual queries, ownership and route identity on an opt-in disposable cluster.
// Follows runtime_grants/grant_auditor_postgres_test.go's Unix-socket-only fixture.
// Never connects to installation databases or reads installation credentials.
package favorites

import (
	"context"
	"database/sql"
	"encoding/json"
	"net/http/httptest"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	backend "easelect/backend/core_components"
	"easelect/backend/core_components/dbutils"
	_ "github.com/lib/pq"
)

func favoritesDisposableDB(t *testing.T) *sql.DB {
	t.Helper()
	if os.Getenv("FILTEREST_TEST_DISPOSABLE_POSTGRES") != "1" {
		t.Skip("set FILTEREST_TEST_DISPOSABLE_POSTGRES=1 for isolated PostgreSQL checks")
	}
	bin := os.Getenv("PG_TEST_BIN")
	if bin == "" {
		bin = "/usr/lib/postgresql/16/bin"
	}
	if _, err := os.Stat(filepath.Join(bin, "initdb")); err != nil {
		t.Skip("PostgreSQL test binaries unavailable")
	}
	root, err := os.MkdirTemp("", "filterest-favorites-")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { os.RemoveAll(root) })
	socket, data := filepath.Join(root, "socket"), filepath.Join(root, "db")
	if err := os.Mkdir(socket, 0700); err != nil {
		t.Fatal(err)
	}
	run := func(name string, args ...string) {
		t.Helper()
		if out, err := exec.Command(filepath.Join(bin, name), args...).CombinedOutput(); err != nil {
			log, _ := os.ReadFile(filepath.Join(root, "postgres.log"))
			t.Fatalf("disposable %s: %v: %s\n%s", name, err, out, log)
		}
	}
	run("initdb", "-D", data, "-A", "trust", "-U", "fixture_owner", "--no-locale", "--encoding=UTF8")
	run("pg_ctl", "-D", data, "-l", filepath.Join(root, "postgres.log"), "-o", "-h '' -k '"+socket+"' -p 15464", "-w", "start")
	t.Cleanup(func() { run("pg_ctl", "-D", data, "-m", "immediate", "-w", "stop") })
	db, err := sql.Open("postgres", "host="+socket+" port=15464 user=fixture_owner dbname=postgres sslmode=disable")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { db.Close() })
	execFavoriteSQL(t, db, `
        CREATE TABLE public.system_users(id bigint PRIMARY KEY);
        CREATE TABLE public.system_db_tables(table_uid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          table_name text, schema_name text, folder_id integer, is_removable boolean, description text,
          cached_oid integer, fk_display_column text, filterbar_visible_by_default boolean, display_name text, sql_dump_policy text);
        CREATE TABLE public.system_table_folders(id integer PRIMARY KEY, folder_name text);
        CREATE TABLE public.system_column_details(table_uid integer, column_name text, data_type text,
          co_number integer, lang_key text, insertable boolean, editable_in_ui boolean);
        CREATE TABLE public.system_data_repair_records(migration text, action text, detail jsonb);
        CREATE TABLE public.system_functions(id bigint PRIMARY KEY, disabled boolean, url_route_endpoint text);
        CREATE TABLE public.system_group_table_func_rights(function_id bigint, user_group_id integer);
        CREATE TABLE public.system_user_group_memberships(group_id integer, user_id bigint);
        INSERT INTO public.system_users VALUES (1),(42),(73);
        INSERT INTO public.system_table_folders VALUES (5,'system');
        INSERT INTO public.system_db_tables(table_uid,table_name,schema_name) VALUES (56,'system_functions','public');
        INSERT INTO public.system_functions VALUES (10,false,'/tool'),(20,true,'/disabled'),(30,false,'/ungranted'),(40,false,'/other-tool');
        INSERT INTO public.system_group_table_func_rights VALUES (10,2),(10,3),(20,2),(40,2),(40,3);
        INSERT INTO public.system_user_group_memberships VALUES (2,42),(3,73);`)
	for i := 0; i < 2; i++ {
		for _, filename := range []string{"20261005000021_create_system_favorites.sql", "20261005000023_register_system_favorites.sql"} {
			content, err := os.ReadFile(filepath.Join("..", "..", "..", "server_tools", "migrations", filename))
			if err != nil {
				t.Fatal(err)
			}
			execFavoriteSQL(t, db, string(content))
		}
	}
	oldDB := backend.Db
	backend.Db = db
	t.Cleanup(func() { backend.Db = oldDB })
	return db
}

func execFavoriteSQL(t *testing.T, db *sql.DB, query string) {
	t.Helper()
	if _, err := db.Exec(query); err != nil {
		t.Fatal(err)
	}
}

func favoriteCount(t *testing.T, db *sql.DB, query string) int {
	t.Helper()
	var count int
	if err := db.QueryRow(query).Scan(&count); err != nil {
		t.Fatal(err)
	}
	return count
}

func addFavoriteInTest(t *testing.T, db *sql.DB, userID int, route string) (favorite, bool, error) {
	t.Helper()
	lazy := dbutils.NewLazyTx(db)
	defer lazy.Rollback()
	item, created, err := addFavorite(dbutils.SetLazyTx(context.Background(), lazy), userID, route)
	if err == nil {
		err = lazy.Commit()
	}
	return item, created, err
}

func deleteFavoriteInTest(t *testing.T, db *sql.DB, userID int, request favoriteRequest) bool {
	t.Helper()
	lazy := dbutils.NewLazyTx(db)
	defer lazy.Rollback()
	removed, err := deleteFavorite(dbutils.SetLazyTx(context.Background(), lazy), userID, request)
	if err != nil {
		t.Fatal(err)
	}
	if err := lazy.Commit(); err != nil {
		t.Fatal(err)
	}
	return removed
}

func TestFavoritesPostgresRoutesAndOwnership(t *testing.T) {
	db := favoritesDisposableDB(t)
	item, created, err := addFavoriteInTest(t, db, 42, "/tool")
	if err != nil || !created || item.Route != "/tool" {
		t.Fatal(item, created, err)
	}
	again, created, err := addFavoriteInTest(t, db, 42, "/tool")
	if err != nil || created || item.ID != again.ID {
		t.Fatal(again, created, err)
	}
	other, otherCreated, err := addFavoriteInTest(t, db, 73, "/tool")
	if err != nil || !otherCreated || other.ID == item.ID {
		t.Fatal("accounts must receive distinct favorite ids", item, other, otherCreated, err)
	}
	otherOnly, created, err := addFavoriteInTest(t, db, 73, "/other-tool")
	if err != nil || !created {
		t.Fatal(otherOnly, created, err)
	}
	// Both routes are granted to the caller, but only the caller's favorite may appear.
	items, err := readFavorites(context.Background(), 42)
	if err != nil || len(items) != 1 || items[0].ID != item.ID || items[0].Route != "/tool" {
		t.Fatal("GET exposed another account's favorite", items, err)
	}
	for _, route := range []string{"/missing", "/disabled", "/ungranted"} {
		if _, _, err := addFavoriteInTest(t, db, 42, route); err != errTargetNotFound {
			t.Fatal(route, err)
		}
	}
	// POST, including an idempotent add, cleans only this owner's gone targets.
	execFavoriteSQL(t, db, `INSERT INTO public.system_favorites(user_id,target_table_uid,target_key,sort_order)
        VALUES (42,56,'gone',3),(73,56,'gone',3);`)
	if _, created, err := addFavoriteInTest(t, db, 42, "/tool"); err != nil || created {
		t.Fatal(created, err)
	}
	if favoriteCount(t, db, "SELECT count(*) FROM system_favorites WHERE user_id=42 AND target_key='gone'") != 0 || favoriteCount(t, db, "SELECT count(*) FROM system_favorites WHERE user_id=73 AND target_key='gone'") != 1 {
		t.Fatal("POST cleanup escaped owner")
	}
	execFavoriteSQL(t, db, "DELETE FROM system_favorites WHERE target_key='gone'")
	// Disabled rows remain hidden unless an enabled replacement with the same route is granted.
	execFavoriteSQL(t, db, "UPDATE public.system_functions SET disabled=true WHERE id=10")
	items, err = readFavorites(context.Background(), 42)
	if err != nil || len(items) != 0 {
		t.Fatal(items, err)
	}
	execFavoriteSQL(t, db, `INSERT INTO public.system_functions VALUES (11,false,'/tool'); INSERT INTO public.system_group_table_func_rights VALUES (11,2),(11,3);`)
	items, err = readFavorites(context.Background(), 42)
	if err != nil || len(items) != 1 || items[0].ID != item.ID {
		t.Fatal("handler rename", items, err)
	}
	// A race over a grant change may have stored both function identities.
	execFavoriteSQL(t, db, `INSERT INTO public.system_favorites(user_id,target_table_uid,target_key,sort_order) VALUES (42,56,'11',2),(42,56,'bad-key',3);`)
	db.SetMaxOpenConns(1)
	execFavoriteSQL(t, db, "SET default_transaction_read_only=on")
	items, err = readFavorites(context.Background(), 42)
	if err != nil || len(items) != 1 {
		t.Fatal("read-only, deduplicated GET", items, err)
	}
	execFavoriteSQL(t, db, "SET default_transaction_read_only=off")
	if favoriteCount(t, db, "SELECT count(*) FROM system_favorites WHERE user_id=42") != 3 {
		t.Fatal("GET cleaned data")
	}
	execFavoriteSQL(t, db, "DELETE FROM public.system_group_table_func_rights WHERE function_id IN (10,11) AND user_group_id=2")
	if _, _, err := addFavoriteInTest(t, db, 42, "/tool"); err != errTargetNotFound {
		t.Fatal("grant checked before existing row", err)
	}
	items, err = readFavorites(context.Background(), 42)
	if err != nil || len(items) != 0 {
		t.Fatal("ungranted target visible", items, err)
	}
	if deleteFavoriteInTest(t, db, 42, favoriteRequest{ID: other.ID}) {
		t.Fatal("deleted another owner")
	}
	if !deleteFavoriteInTest(t, db, 42, favoriteRequest{Type: "admin_tool", Route: "/tool"}) {
		t.Fatal("could not remove by route after grant removal")
	}
	if favoriteCount(t, db, "SELECT count(*) FROM system_favorites WHERE user_id=42") != 0 {
		t.Fatal("route-wide removal/cleanup failed")
	}
	items, err = readFavorites(context.Background(), 73)
	if err != nil || len(items) != 2 || items[0].ID != other.ID || items[1].ID != otherOnly.ID {
		t.Fatal("other owner changed")
	}
	if !deleteFavoriteInTest(t, db, 73, favoriteRequest{ID: otherOnly.ID}) {
		t.Fatal("other route removal")
	}
	// Cleared routes and deleted target rows are always removable by their own id.
	execFavoriteSQL(t, db, "UPDATE public.system_functions SET url_route_endpoint=NULL WHERE id=10")
	if !deleteFavoriteInTest(t, db, 73, favoriteRequest{ID: other.ID}) {
		t.Fatal("cleared route removal")
	}
	execFavoriteSQL(t, db, `INSERT INTO public.system_favorites(user_id,target_table_uid,target_key) VALUES (42,56,'11'),(73,56,'11'); DELETE FROM public.system_functions WHERE id=11;`)
	if deleteFavoriteInTest(t, db, 42, favoriteRequest{Route: "/missing"}) {
		t.Fatal("reported nonexistent removal")
	}
	if favoriteCount(t, db, "SELECT count(*) FROM system_favorites WHERE user_id=42") != 0 || favoriteCount(t, db, "SELECT count(*) FROM system_favorites WHERE user_id=73") != 1 {
		t.Fatal("cleanup escaped owner")
	}
}

func TestFavoritesPostgresMigrationsConstraintsAndCascades(t *testing.T) {
	db := favoritesDisposableDB(t)
	if favoriteCount(t, db, `SELECT count(*) FROM system_db_tables t JOIN system_table_folders f ON f.id=t.folder_id WHERE t.table_name='system_favorites' AND NOT t.is_removable AND f.folder_name='system'`) != 1 {
		t.Fatal("registry/folder")
	}
	if favoriteCount(t, db, `SELECT count(*) FROM system_column_details WHERE table_uid=(SELECT table_uid FROM system_db_tables WHERE table_name='system_favorites') AND NOT insertable AND NOT editable_in_ui`) != 7 {
		t.Fatal("column metadata")
	}
	if favoriteCount(t, db, "SELECT count(*) FROM system_data_repair_records WHERE action='completed'") != 2 {
		t.Fatal("duplicate/missing markers")
	}
	var created, beforeUpdate, afterUpdate, createdAfterUpdate time.Time
	var sortOrder int
	if err := db.QueryRow(`INSERT INTO system_favorites(user_id,target_table_uid,target_key) VALUES (42,56,'10')
        RETURNING created,updated,sort_order`).Scan(&created, &beforeUpdate, &sortOrder); err != nil {
		t.Fatal(err)
	}
	if !created.Equal(beforeUpdate) || sortOrder != 0 {
		t.Fatal("timestamp/order defaults", created, beforeUpdate, sortOrder)
	}
	// Separate transactions make now() advance; the trigger must override a supplied stale timestamp.
	if err := db.QueryRow(`UPDATE system_favorites SET sort_order=1,updated='2000-01-01'
        WHERE user_id=42 RETURNING created,updated`).Scan(&createdAfterUpdate, &afterUpdate); err != nil {
		t.Fatal(err)
	}
	if !afterUpdate.After(beforeUpdate) || !createdAfterUpdate.Equal(created) {
		t.Fatal("updated trigger", beforeUpdate, afterUpdate, createdAfterUpdate)
	}
	for _, values := range []string{"42,56,'10',0", "1,56,'visitor',0", "42,56,'',0", "42,56,'negative',-1", "NULL,56,'null',0", "42,56,'" + strings.Repeat("x", 201) + "',0"} {
		if _, err := db.Exec("INSERT INTO system_favorites(user_id,target_table_uid,target_key,sort_order) VALUES (" + values + ")"); err == nil {
			t.Fatal("constraint accepted", values)
		}
	}
	execFavoriteSQL(t, db, "DELETE FROM system_users WHERE id=42")
	if favoriteCount(t, db, "SELECT count(*) FROM system_favorites") != 0 {
		t.Fatal("account cascade")
	}
	execFavoriteSQL(t, db, `INSERT INTO system_favorites(user_id,target_table_uid,target_key) VALUES (73,56,'10'); DELETE FROM system_db_tables WHERE table_uid=56;`)
	if favoriteCount(t, db, "SELECT count(*) FROM system_favorites") != 0 {
		t.Fatal("registry cascade")
	}
}

func TestFavoritesPostgresHandlerUsesRequestTransaction(t *testing.T) {
	db := favoritesDisposableDB(t)
	var ids []int64
	for _, owner := range []struct {
		userID int
		path   string
	}{{42, "/api/favorites?user_id=73"}, {73, "/api/favorites?user_id=42"}} {
		cookie := favoriteSession(t, owner.userID)
		lazy := dbutils.NewLazyTx(db)
		defer lazy.Rollback()
		request := httptest.NewRequest("POST", owner.path, strings.NewReader(`{"type":"admin_tool","route":"/tool"}`))
		request.AddCookie(cookie)
		request = request.WithContext(dbutils.SetLazyTx(request.Context(), lazy))
		response := httptest.NewRecorder()
		FavoritesHandler(response, request)
		if response.Code != 200 {
			t.Fatal(response.Code, response.Body.String())
		}
		var result struct {
			Favorite favorite `json:"favorite"`
			Created  bool     `json:"created"`
		}
		if err := json.Unmarshal(response.Body.Bytes(), &result); err != nil || !result.Created || result.Favorite.ID <= 0 {
			t.Fatal("POST response", result, err)
		}
		ids = append(ids, result.Favorite.ID)
		if err := lazy.Commit(); err != nil {
			t.Fatal(err)
		}
	}
	if ids[0] == ids[1] {
		t.Fatal("two accounts' POSTs returned the same favorite id", ids)
	}
	if favoriteCount(t, db, "SELECT count(*) FROM system_favorites WHERE user_id=42") != 1 || favoriteCount(t, db, "SELECT count(*) FROM system_favorites WHERE user_id=73") != 1 {
		t.Fatal("owner")
	}
}

func TestFavoritesPostgresConcurrentAddIsIdempotent(t *testing.T) {
	db := favoritesDisposableDB(t)
	start := make(chan struct{})
	results := make(chan struct {
		item    favorite
		created bool
		err     error
	}, 2)
	for i := 0; i < 2; i++ {
		go func() {
			<-start
			lazy := dbutils.NewLazyTx(db)
			defer lazy.Rollback()
			item, created, err := addFavorite(dbutils.SetLazyTx(context.Background(), lazy), 42, "/tool")
			if err == nil {
				err = lazy.Commit()
			}
			results <- struct {
				item    favorite
				created bool
				err     error
			}{item, created, err}
		}()
	}
	close(start)
	left, right := <-results, <-results
	if left.err != nil || right.err != nil || left.item.ID != right.item.ID || left.created == right.created {
		t.Fatal(left, right)
	}
	if favoriteCount(t, db, "SELECT count(*) FROM system_favorites") != 1 {
		t.Fatal("double-click duplicated favorite")
	}
}
