-- 20260816000002_add_external_embedding_policy_queue.sql
-- Adds fail-closed field consent and a durable, content-free row refresh queue
-- for embeddings generated by an external provider.
-- VERSION_DB: 8.0.60
-- VERSION_DB_OWNER: 20260816000001_seed_calendar_view_lang_keys.sql

ALTER TABLE public.system_column_details
    ADD COLUMN IF NOT EXISTS external_embedding_allowed BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN public.system_column_details.external_embedding_allowed IS
    'Explicit admin consent for sending this text column to the configured external embedding provider. Defaults to false.';

CREATE TABLE IF NOT EXISTS public.system_embedding_refresh_jobs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_uid        INTEGER NOT NULL REFERENCES public.system_db_tables(table_uid) ON DELETE CASCADE,
    row_id           BIGINT NOT NULL,
    generation       BIGINT NOT NULL DEFAULT 1,
    attempt_count    INTEGER NOT NULL DEFAULT 0,
    available_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    lease_token      TEXT NOT NULL DEFAULT '',
    lease_expires_at TIMESTAMPTZ,
    last_error_code  TEXT NOT NULL DEFAULT '',
    created          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_system_embedding_refresh_jobs_row UNIQUE (table_uid, row_id),
    CONSTRAINT ck_system_embedding_refresh_jobs_generation CHECK (generation >= 1),
    CONSTRAINT ck_system_embedding_refresh_jobs_attempt_count CHECK (attempt_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_system_embedding_refresh_jobs_claim
    ON public.system_embedding_refresh_jobs (available_at, lease_expires_at, id);

INSERT INTO public.system_db_tables (
    table_name,
    description,
    cached_oid,
    schema_name,
    filterbar_visible_by_default,
    is_removable,
    display_name,
    sql_dump_policy
)
SELECT
    'system_embedding_refresh_jobs',
    'Content-free durable queue for refreshing row embeddings after committed data changes',
    cls.oid::integer,
    'public',
    FALSE,
    FALSE,
    'Embedding Refresh Jobs',
    'schema_only'
FROM pg_class cls
JOIN pg_namespace ns ON ns.oid = cls.relnamespace AND ns.nspname = 'public'
WHERE cls.relname = 'system_embedding_refresh_jobs'
  AND NOT EXISTS (
      SELECT 1
      FROM public.system_db_tables existing
      WHERE existing.table_name = 'system_embedding_refresh_jobs'
        AND COALESCE(NULLIF(existing.schema_name, ''), 'public') = 'public'
  );

UPDATE public.system_db_tables target
SET description = 'Content-free durable queue for refreshing row embeddings after committed data changes',
    cached_oid = cls.oid::integer,
    schema_name = 'public',
    filterbar_visible_by_default = FALSE,
    is_removable = FALSE,
    display_name = 'Embedding Refresh Jobs',
    sql_dump_policy = 'schema_only',
    updated = now()
FROM pg_class cls
JOIN pg_namespace ns ON ns.oid = cls.relnamespace AND ns.nspname = 'public'
WHERE cls.relname = 'system_embedding_refresh_jobs'
  AND target.table_name = cls.relname
  AND COALESCE(NULLIF(target.schema_name, ''), 'public') = 'public';

DO $$
DECLARE
    metadata_table_uid INTEGER;
    queue_table_uid INTEGER;
BEGIN
    SELECT table_uid INTO metadata_table_uid
    FROM public.system_db_tables
    WHERE table_name = 'system_column_details'
      AND COALESCE(NULLIF(schema_name, ''), 'public') = 'public'
    LIMIT 1;

    SELECT table_uid INTO queue_table_uid
    FROM public.system_db_tables
    WHERE table_name = 'system_embedding_refresh_jobs'
      AND COALESCE(NULLIF(schema_name, ''), 'public') = 'public'
    LIMIT 1;

    IF metadata_table_uid IS NOT NULL THEN
        INSERT INTO public.system_column_details (
            table_uid, column_name, data_type, co_number, editable_in_ui, created, updated
        )
        SELECT
            metadata_table_uid,
            c.column_name,
            c.data_type,
            c.ordinal_position,
            FALSE,
            now(),
            now()
        FROM information_schema.columns c
        WHERE c.table_schema = 'public'
          AND c.table_name = 'system_column_details'
          AND c.column_name = 'external_embedding_allowed'
          AND NOT EXISTS (
              SELECT 1
              FROM public.system_column_details existing
              WHERE existing.table_uid = metadata_table_uid
                AND existing.column_name = c.column_name
          );
    END IF;

    IF queue_table_uid IS NOT NULL THEN
        INSERT INTO public.system_column_details (
            table_uid, column_name, data_type, co_number, editable_in_ui, created, updated
        )
        SELECT
            queue_table_uid,
            c.column_name,
            c.data_type,
            c.ordinal_position,
            FALSE,
            now(),
            now()
        FROM information_schema.columns c
        WHERE c.table_schema = 'public'
          AND c.table_name = 'system_embedding_refresh_jobs'
          AND NOT EXISTS (
              SELECT 1
              FROM public.system_column_details existing
              WHERE existing.table_uid = queue_table_uid
                AND existing.column_name = c.column_name
          )
        ORDER BY c.ordinal_position;
    END IF;
END $$;

INSERT INTO public.system_lang_keys (lang_key, fi, en, ch, yue, creation_spec)
VALUES
    (
        'embedding_external_fields',
        'Ulkoiseen embedding-palveluun lähetettävät kentät',
        'Fields sent to the external embedding provider',
        '发送到外部嵌入服务的字段',
        '傳送到外部嵌入服務嘅欄位',
        'Admin label for selecting dataset fields that may leave the server for embedding generation.'
    ),
    (
        'embedding_external_warning',
        'Vain valittujen kenttien sisältö lähetetään määritetylle ulkoiselle embedding-palvelulle (OpenAI tai Google). Älä valitse salaisia tai henkilötietoja sisältäviä kenttiä ilman hyväksyntää.',
        'Only selected fields are sent to the configured external embedding provider (OpenAI or Google). Do not select secret or personal-data fields without approval.',
        '只有所选字段会发送到已配置的外部嵌入服务（OpenAI 或 Google）。未经批准，请勿选择包含机密或个人数据的字段。',
        '只有揀選咗嘅欄位會傳送到已設定嘅外部嵌入服務（OpenAI 或 Google）。未經批准，請勿揀選包含機密或個人資料嘅欄位。',
        'Privacy warning shown beside the external embedding field selector.'
    ),
    (
        'embedding_save_field_policy',
        'Tallenna kenttävalinta',
        'Save field selection',
        '保存字段选择',
        '儲存欄位選擇',
        'Admin action that saves external embedding field consent and schedules a rebuild.'
    ),
    (
        'embedding_field_policy_saved',
        'Embedding-kenttävalinta tallennettu ja päivitys jonotettu',
        'Embedding field selection saved and refresh queued',
        '嵌入字段选择已保存，刷新已排队',
        '嵌入欄位選擇已儲存，重新整理已排程',
        'Confirmation after saving external embedding field consent.'
    )
ON CONFLICT (lang_key) DO UPDATE
SET fi = EXCLUDED.fi,
    en = EXCLUDED.en,
    ch = EXCLUDED.ch,
    yue = EXCLUDED.yue,
    creation_spec = EXCLUDED.creation_spec;
