-- 20260817000002_normalize_ui_languages.sql
-- Adds a canonical UI-language registry and normalized per-key translations.
-- Keeps the legacy wide language columns available for the later runtime cutover.
-- VERSION_DB: 9.0.0
-- VERSION_DB_OWNER: 20260817000007_repair_filterest_admin_schema_permissions.sql

CREATE TABLE IF NOT EXISTS public.system_languages (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code            TEXT        NOT NULL UNIQUE,
    english_name             TEXT        NOT NULL,
    native_name              TEXT        NOT NULL,
    script_code              TEXT        NOT NULL,
    region_code              TEXT,
    is_enabled               BOOLEAN     NOT NULL DEFAULT FALSE,
    is_default               BOOLEAN     NOT NULL DEFAULT FALSE,
    fallback_language_code   TEXT        REFERENCES public.system_languages(language_code) ON DELETE RESTRICT,
    coverage_status          TEXT        NOT NULL DEFAULT 'not_started',
    review_status            TEXT        NOT NULL DEFAULT 'unreviewed',
    public_selector_ready    BOOLEAN     NOT NULL DEFAULT FALSE,
    sort_order               INTEGER     NOT NULL DEFAULT 100,
    created                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_system_languages_code
        CHECK (language_code ~ '^[a-z]{2,3}(-[A-Z]{2})?$'),
    CONSTRAINT ck_system_languages_script
        CHECK (script_code ~ '^[A-Z][a-z]{3}$'),
    CONSTRAINT ck_system_languages_region
        CHECK (region_code IS NULL OR region_code ~ '^[A-Z]{2}$'),
    CONSTRAINT ck_system_languages_code_region_match
        CHECK (
            (region_code IS NULL AND language_code !~ '-')
            OR language_code = split_part(language_code, '-', 1) || '-' || region_code
        ),
    CONSTRAINT ck_system_languages_coverage
        CHECK (coverage_status IN ('not_started', 'partial', 'complete')),
    CONSTRAINT ck_system_languages_review
        CHECK (review_status IN ('unreviewed', 'needs_review', 'approved')),
    CONSTRAINT ck_system_languages_default_enabled
        CHECK (is_default IS FALSE OR is_enabled IS TRUE),
    CONSTRAINT ck_system_languages_fallback
        CHECK (
            (is_default IS TRUE AND fallback_language_code IS NULL)
            OR
            (
                is_default IS FALSE
                AND fallback_language_code IS NOT NULL
                AND fallback_language_code <> language_code
            )
        ),
    CONSTRAINT ck_system_languages_public_selector_gate
        CHECK (
            public_selector_ready IS FALSE
            OR (
                is_enabled IS TRUE
                AND coverage_status = 'complete'
                AND review_status = 'approved'
            )
        )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_system_languages_one_default
    ON public.system_languages (is_default)
    WHERE is_default IS TRUE;

CREATE TABLE IF NOT EXISTS public.system_lang_key_translations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lang_key_id       BIGINT      NOT NULL REFERENCES public.system_lang_keys(id) ON DELETE CASCADE,
    language_code     TEXT        NOT NULL REFERENCES public.system_languages(language_code) ON DELETE RESTRICT,
    translation       TEXT        NOT NULL CHECK (btrim(translation) <> ''),
    source_kind       TEXT        NOT NULL,
    review_status     TEXT        NOT NULL DEFAULT 'unreviewed',
    created           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated           TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_system_lang_key_translations_key_language
        UNIQUE (lang_key_id, language_code),
    CONSTRAINT ck_system_lang_key_translations_source
        CHECK (source_kind IN ('legacy_en', 'legacy_fi', 'legacy_ch', 'manual', 'import')),
    CONSTRAINT ck_system_lang_key_translations_review
        CHECK (review_status IN ('unreviewed', 'needs_review', 'approved'))
);

CREATE INDEX IF NOT EXISTS idx_system_lang_key_translations_language
    ON public.system_lang_key_translations (language_code, lang_key_id);

CREATE OR REPLACE FUNCTION public.set_system_languages_updated_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.set_system_lang_key_translations_updated_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'update_system_languages_timestamp'
          AND tgrelid = 'public.system_languages'::regclass
    ) THEN
        CREATE TRIGGER update_system_languages_timestamp
            BEFORE UPDATE ON public.system_languages
            FOR EACH ROW EXECUTE FUNCTION public.set_system_languages_updated_timestamp();
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'update_system_lang_key_translations_timestamp'
          AND tgrelid = 'public.system_lang_key_translations'::regclass
    ) THEN
        CREATE TRIGGER update_system_lang_key_translations_timestamp
            BEFORE UPDATE ON public.system_lang_key_translations
            FOR EACH ROW EXECUTE FUNCTION public.set_system_lang_key_translations_updated_timestamp();
    END IF;
END $$;

COMMENT ON TABLE public.system_languages IS
    'Canonical registry for UI locales, site enablement, fallback, review, and public-selector eligibility.';
COMMENT ON COLUMN public.system_languages.language_code IS
    'Canonical case-sensitive BCP 47 language tag used by application contracts.';
COMMENT ON COLUMN public.system_languages.fallback_language_code IS
    'Explicit fallback locale; NULL is reserved for the enabled default/root locale.';
COMMENT ON COLUMN public.system_languages.public_selector_ready IS
    'Release/admin approval for public selection; the database gate also requires enabled, complete, and approved.';
COMMENT ON TABLE public.system_lang_key_translations IS
    'Normalized one-language-per-row translations keyed to the stable system_lang_keys row.';
COMMENT ON COLUMN public.system_lang_key_translations.source_kind IS
    'Provenance of the copied or authored value; legacy_ch means the old simplified-Chinese column.';

WITH desired_languages (
    language_code,
    english_name,
    native_name,
    script_code,
    region_code,
    is_enabled,
    is_default,
    fallback_language_code,
    coverage_status,
    review_status,
    public_selector_ready,
    sort_order
) AS (
    VALUES
        ('en',    'English',                                'English',          'Latn', NULL, TRUE,  TRUE,  NULL, 'complete',    'approved',     TRUE,   10),
        ('fi',    'Finnish',                                'Suomi',            'Latn', NULL, TRUE,  FALSE, 'en', 'complete',    'approved',     TRUE,   20),
        ('zh-CN', 'Chinese (Simplified, Mainland China)',   '简体中文（中国大陆）', 'Hans', 'CN', FALSE, FALSE, 'en', 'partial',     'needs_review', FALSE,  30),
        ('zh-TW', 'Chinese (Traditional, Taiwan)',          '繁體中文（台灣）',     'Hant', 'TW', FALSE, FALSE, 'en', 'not_started', 'unreviewed',   FALSE,  40),
        ('zh-HK', 'Chinese (Traditional, Hong Kong)',       '繁體中文（香港）',     'Hant', 'HK', FALSE, FALSE, 'en', 'not_started', 'unreviewed',   FALSE,  50)
)
INSERT INTO public.system_languages (
    language_code,
    english_name,
    native_name,
    script_code,
    region_code,
    is_enabled,
    is_default,
    fallback_language_code,
    coverage_status,
    review_status,
    public_selector_ready,
    sort_order
)
SELECT
    desired.language_code,
    desired.english_name,
    desired.native_name,
    desired.script_code,
    desired.region_code,
    desired.is_enabled,
    desired.is_default,
    desired.fallback_language_code,
    desired.coverage_status,
    desired.review_status,
    desired.public_selector_ready,
    desired.sort_order
FROM desired_languages AS desired
WHERE NOT EXISTS (
    SELECT 1
    FROM public.system_languages AS existing
    WHERE existing.language_code = desired.language_code
);

-- Only mappings with a known locale meaning are copied. The old ch column is
-- simplified Chinese and therefore maps to zh-CN. The old Cantonese yue column
-- is intentionally not copied: it is not proof of reviewed zh-HK copy.
WITH legacy_translations AS (
    SELECT source.id AS lang_key_id,
           'en'::TEXT AS language_code,
           source.en AS translation,
           'legacy_en'::TEXT AS source_kind,
           'approved'::TEXT AS review_status
    FROM public.system_lang_keys AS source
    UNION ALL
    SELECT source.id,
           'fi'::TEXT,
           source.fi,
           'legacy_fi'::TEXT,
           'approved'::TEXT
    FROM public.system_lang_keys AS source
    UNION ALL
    SELECT source.id,
           'zh-CN'::TEXT,
           source.ch,
           'legacy_ch'::TEXT,
           'needs_review'::TEXT
    FROM public.system_lang_keys AS source
)
INSERT INTO public.system_lang_key_translations (
    lang_key_id,
    language_code,
    translation,
    source_kind,
    review_status
)
SELECT
    source.lang_key_id,
    source.language_code,
    source.translation,
    source.source_kind,
    source.review_status
FROM legacy_translations AS source
WHERE NULLIF(btrim(source.translation), '') IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM public.system_lang_key_translations AS existing
      WHERE existing.lang_key_id = source.lang_key_id
        AND existing.language_code = source.language_code
  );

WITH desired_tables (
    table_name,
    display_name,
    description,
    fk_display_column,
    sql_dump_policy
) AS (
    VALUES
        ('system_languages', 'Languages', 'Canonical UI-language registry and site availability controls', 'native_name', 'all'),
        ('system_lang_key_translations', 'Language Key Translations', 'Normalized translations for stable UI language keys', 'translation', 'all')
)
INSERT INTO public.system_db_tables (
    table_name,
    description,
    cached_oid,
    folder_id,
    schema_name,
    fk_display_column,
    filterbar_visible_by_default,
    is_removable,
    display_name,
    sql_dump_policy
)
SELECT
    desired.table_name,
    desired.description,
    tables.oid::INTEGER,
    (
        SELECT folders.id
        FROM public.system_table_folders AS folders
        WHERE folders.folder_name = 'lang'
        ORDER BY folders.id
        LIMIT 1
    ),
    'public',
    desired.fk_display_column,
    FALSE,
    FALSE,
    desired.display_name,
    desired.sql_dump_policy
FROM desired_tables AS desired
JOIN pg_class AS tables ON tables.relname = desired.table_name
JOIN pg_namespace AS schemas ON schemas.oid = tables.relnamespace AND schemas.nspname = 'public'
WHERE NOT EXISTS (
    SELECT 1
    FROM public.system_db_tables AS existing
    WHERE existing.table_name = desired.table_name
      AND COALESCE(NULLIF(existing.schema_name, ''), 'public') = 'public'
);

WITH desired_tables (
    table_name,
    display_name,
    description,
    fk_display_column,
    sql_dump_policy
) AS (
    VALUES
        ('system_languages', 'Languages', 'Canonical UI-language registry and site availability controls', 'native_name', 'all'),
        ('system_lang_key_translations', 'Language Key Translations', 'Normalized translations for stable UI language keys', 'translation', 'all')
), language_folder AS (
    SELECT folders.id
    FROM public.system_table_folders AS folders
    WHERE folders.folder_name = 'lang'
    ORDER BY folders.id
    LIMIT 1
)
UPDATE public.system_db_tables AS target
SET description = desired.description,
    cached_oid = tables.oid::INTEGER,
    folder_id = COALESCE((SELECT id FROM language_folder), target.folder_id),
    schema_name = 'public',
    fk_display_column = desired.fk_display_column,
    filterbar_visible_by_default = FALSE,
    is_removable = FALSE,
    display_name = desired.display_name,
    sql_dump_policy = desired.sql_dump_policy,
    updated = now()
FROM desired_tables AS desired
JOIN pg_class AS tables ON tables.relname = desired.table_name
JOIN pg_namespace AS schemas ON schemas.oid = tables.relnamespace AND schemas.nspname = 'public'
WHERE target.table_name = desired.table_name
  AND COALESCE(NULLIF(target.schema_name, ''), 'public') = 'public';

DO $$
DECLARE
    table_name_to_register TEXT;
    registered_table_uid INTEGER;
BEGIN
    FOREACH table_name_to_register IN ARRAY ARRAY[
        'system_languages',
        'system_lang_key_translations'
    ]
    LOOP
        SELECT table_uid
        INTO registered_table_uid
        FROM public.system_db_tables
        WHERE table_name = table_name_to_register
          AND COALESCE(NULLIF(schema_name, ''), 'public') = 'public'
        LIMIT 1;

        IF registered_table_uid IS NOT NULL THEN
            INSERT INTO public.system_column_details (
                table_uid,
                column_name,
                data_type,
                co_number,
                editable_in_ui,
                created,
                updated
            )
            SELECT
                registered_table_uid,
                columns.column_name,
                columns.data_type,
                columns.ordinal_position,
                FALSE,
                now(),
                now()
            FROM information_schema.columns AS columns
            WHERE columns.table_schema = 'public'
              AND columns.table_name = table_name_to_register
              AND NOT EXISTS (
                  SELECT 1
                  FROM public.system_column_details AS existing
                  WHERE existing.table_uid = registered_table_uid
                    AND existing.column_name = columns.column_name
              )
            ORDER BY columns.ordinal_position;
        END IF;
    END LOOP;
END $$;
