-- 20260822000006_normalize_view_field_sets.sql
-- Normalizes reusable field collections and their per-view personal/site assignments.
-- Bridges legacy column presets/user settings with stable dataset view keys.
-- Exists so table and card views can inherit site defaults while users keep personal choices.

ALTER TABLE public.system_table_views
    ADD COLUMN IF NOT EXISTS view_key TEXT;

WITH ranked AS (
    SELECT id,
           lower(btrim(name)) AS base_key,
           row_number() OVER (PARTITION BY lower(btrim(name)) ORDER BY id) AS duplicate_number
    FROM public.system_table_views
    WHERE name IS NOT NULL AND btrim(name) <> ''
)
UPDATE public.system_table_views AS views
SET view_key = CASE
        WHEN ranked.base_key ~ '^[a-z][a-z0-9_]{0,63}$' AND ranked.duplicate_number = 1
            THEN ranked.base_key
        WHEN ranked.base_key ~ '^[a-z][a-z0-9_]{0,54}$'
            THEN ranked.base_key || '_legacy_' || views.id::TEXT
        ELSE 'legacy_' || views.id::TEXT
    END
FROM ranked
WHERE ranked.id = views.id
  AND views.view_key IS NULL;

UPDATE public.system_table_views
SET view_key = 'legacy_' || id::TEXT
WHERE view_key IS NULL;

ALTER TABLE public.system_table_views
    ALTER COLUMN view_key SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_system_table_views_view_key
    ON public.system_table_views (view_key);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_system_table_views_view_key'
          AND conrelid = 'public.system_table_views'::regclass
    ) THEN
        ALTER TABLE public.system_table_views
            ADD CONSTRAINT ck_system_table_views_view_key
            CHECK (view_key ~ '^[a-z][a-z0-9_]{0,63}$');
    END IF;
END $$;

INSERT INTO public.system_table_views (name, view_key, status)
VALUES
    ('table', 'table', 'active'),
    ('card', 'card', 'active')
ON CONFLICT (view_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.system_column_field_sets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_uid     INTEGER     NOT NULL REFERENCES public.system_db_tables(table_uid) ON DELETE CASCADE,
    owner_user_id BIGINT      REFERENCES public.system_users(id) ON DELETE CASCADE,
    name          TEXT        NOT NULL CHECK (char_length(btrim(name)) BETWEEN 1 AND 128),
    created_by    BIGINT      REFERENCES public.system_users(id) ON DELETE SET NULL,
    created       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_system_column_field_sets_owner_name
        UNIQUE NULLS NOT DISTINCT (table_uid, owner_user_id, name),
    CONSTRAINT uq_system_column_field_sets_id_table UNIQUE (id, table_uid)
);

CREATE TABLE IF NOT EXISTS public.system_column_field_set_members (
    field_set_id   BIGINT  NOT NULL,
    table_uid      INTEGER NOT NULL,
    column_uid     INTEGER NOT NULL,
    sort_order     INTEGER NOT NULL CHECK (sort_order > 0),
    column_width_px INTEGER CHECK (column_width_px IS NULL OR column_width_px >= 0),
    PRIMARY KEY (field_set_id, column_uid),
    CONSTRAINT uq_system_column_field_set_member_order UNIQUE (field_set_id, sort_order),
    CONSTRAINT fk_system_column_field_set_members_set
        FOREIGN KEY (field_set_id, table_uid)
        REFERENCES public.system_column_field_sets(id, table_uid) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_system_column_details_table_column
    ON public.system_column_details (table_uid, column_uid);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_system_column_field_set_members_column'
          AND conrelid = 'public.system_column_field_set_members'::regclass
    ) THEN
        ALTER TABLE public.system_column_field_set_members
            ADD CONSTRAINT fk_system_column_field_set_members_column
            FOREIGN KEY (table_uid, column_uid)
            REFERENCES public.system_column_details(table_uid, column_uid) ON DELETE CASCADE;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.system_view_field_set_assignments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT REFERENCES public.system_users(id) ON DELETE CASCADE,
    table_uid    INTEGER NOT NULL REFERENCES public.system_db_tables(table_uid) ON DELETE CASCADE,
    view_id      INTEGER NOT NULL REFERENCES public.system_table_views(id) ON DELETE CASCADE,
    field_set_id BIGINT  NOT NULL,
    created_by   BIGINT REFERENCES public.system_users(id) ON DELETE SET NULL,
    created      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_system_view_field_set_assignment
        UNIQUE NULLS NOT DISTINCT (user_id, table_uid, view_id),
    CONSTRAINT fk_system_view_field_set_assignment_set
        FOREIGN KEY (field_set_id, table_uid)
        REFERENCES public.system_column_field_sets(id, table_uid) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_system_column_field_sets_table_owner
    ON public.system_column_field_sets (table_uid, owner_user_id);
CREATE INDEX IF NOT EXISTS idx_system_view_field_set_assignments_lookup
    ON public.system_view_field_set_assignments (table_uid, view_id, user_id);

-- Preserve legacy shared presets as reusable shared field collections. A preset
-- is not made active automatically because the old model had no active preset.
INSERT INTO public.system_column_field_sets (table_uid, owner_user_id, name, created_by, created)
SELECT tables.table_uid,
       NULL,
       presets.preset_name,
       users.id,
       presets.created
FROM public.system_column_view_presets AS presets
JOIN public.system_db_tables AS tables
  ON tables.table_name = presets.table_name
 AND COALESCE(NULLIF(tables.schema_name, ''), 'public') = 'public'
LEFT JOIN public.system_users AS users ON users.id = presets.created_by
ON CONFLICT (table_uid, owner_user_id, name) DO NOTHING;

INSERT INTO public.system_column_field_set_members (
    field_set_id, table_uid, column_uid, sort_order, column_width_px
)
SELECT field_sets.id,
       field_sets.table_uid,
       details.column_uid,
       row_number() OVER (PARTITION BY field_sets.id ORDER BY details.co_number NULLS LAST, details.column_uid),
       NULL
FROM public.system_column_view_presets AS presets
JOIN public.system_db_tables AS tables
  ON tables.table_name = presets.table_name
 AND COALESCE(NULLIF(tables.schema_name, ''), 'public') = 'public'
JOIN public.system_column_field_sets AS field_sets
  ON field_sets.table_uid = tables.table_uid
 AND field_sets.owner_user_id IS NULL
 AND field_sets.name = presets.preset_name
JOIN public.system_column_details AS details ON details.table_uid = tables.table_uid
WHERE COALESCE(details.hide_everywhere, false) = false
  AND NOT (presets.hidden_columns @> jsonb_build_object(details.column_name, true))
ON CONFLICT (field_set_id, column_uid) DO NOTHING;

-- Preserve the former active per-user table settings as one named personal
-- collection and assign it to the stable table view. Site rows remain shared.
INSERT INTO public.system_column_field_sets (table_uid, owner_user_id, name, created_by)
SELECT settings.table_uid,
       users.id,
       CASE WHEN users.id IS NULL THEN 'Imported site table fields' ELSE 'Imported personal table fields' END,
       users.id
FROM public.system_user_column_settings AS settings
LEFT JOIN public.system_users AS users ON users.id = settings.user_id
WHERE settings.table_uid IS NOT NULL
GROUP BY settings.table_uid, users.id
ON CONFLICT (table_uid, owner_user_id, name) DO NOTHING;

INSERT INTO public.system_column_field_set_members (
    field_set_id, table_uid, column_uid, sort_order, column_width_px
)
SELECT field_sets.id,
       field_sets.table_uid,
       details.column_uid,
       row_number() OVER (
           PARTITION BY field_sets.id
           ORDER BY settings.sort_order NULLS LAST, details.co_number NULLS LAST, details.column_uid
       ),
       settings.column_width_px
FROM public.system_user_column_settings AS settings
LEFT JOIN public.system_users AS users ON users.id = settings.user_id
JOIN public.system_column_field_sets AS field_sets
  ON field_sets.table_uid = settings.table_uid
 AND field_sets.owner_user_id IS NOT DISTINCT FROM users.id
 AND field_sets.name = CASE WHEN users.id IS NULL THEN 'Imported site table fields' ELSE 'Imported personal table fields' END
JOIN public.system_column_details AS details
  ON details.table_uid = settings.table_uid
 AND details.column_name = settings.column_name
WHERE settings.table_uid IS NOT NULL
  AND COALESCE(settings.is_hidden, false) = false
  AND COALESCE(details.hide_everywhere, false) = false
ON CONFLICT (field_set_id, column_uid) DO NOTHING;

INSERT INTO public.system_view_field_set_assignments (
    user_id, table_uid, view_id, field_set_id, created_by
)
SELECT field_sets.owner_user_id,
       field_sets.table_uid,
       views.id,
       field_sets.id,
       field_sets.owner_user_id
FROM public.system_column_field_sets AS field_sets
JOIN public.system_table_views AS views ON views.view_key = 'table'
WHERE field_sets.name IN ('Imported site table fields', 'Imported personal table fields')
  AND EXISTS (
      SELECT 1 FROM public.system_column_field_set_members AS members
      WHERE members.field_set_id = field_sets.id
  )
ON CONFLICT (user_id, table_uid, view_id)
DO UPDATE SET field_set_id = EXCLUDED.field_set_id,
              created_by = EXCLUDED.created_by,
              updated = now();

-- Drop legacy runtime structures only after every resolvable legacy record has
-- a normalized counterpart. Any mismatch aborts the migration before DROP.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.system_column_view_presets AS presets
        JOIN public.system_db_tables AS tables
          ON tables.table_name = presets.table_name
         AND COALESCE(NULLIF(tables.schema_name, ''), 'public') = 'public'
        WHERE NOT EXISTS (
            SELECT 1 FROM public.system_column_field_sets AS field_sets
            WHERE field_sets.table_uid = tables.table_uid
              AND field_sets.owner_user_id IS NULL
              AND field_sets.name = presets.preset_name
        )
    ) THEN
        RAISE EXCEPTION 'legacy shared column preset migration was incomplete';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM public.system_user_column_settings AS settings
        LEFT JOIN public.system_users AS users ON users.id = settings.user_id
        WHERE settings.table_uid IS NOT NULL
          AND COALESCE(settings.is_hidden, false) = false
          AND NOT EXISTS (
              SELECT 1
              FROM public.system_column_field_sets AS field_sets
              JOIN public.system_column_field_set_members AS members
                ON members.field_set_id = field_sets.id
              JOIN public.system_column_details AS details
                ON details.column_uid = members.column_uid
              WHERE field_sets.table_uid = settings.table_uid
                AND field_sets.owner_user_id IS NOT DISTINCT FROM users.id
                AND details.column_name = settings.column_name
          )
    ) THEN
        RAISE EXCEPTION 'legacy personal column setting migration was incomplete';
    END IF;
END $$;

DROP TABLE public.system_column_view_presets;
DROP TABLE public.system_user_column_settings;

COMMENT ON COLUMN public.system_table_views.view_key IS
    'Stable machine key used by per-view settings; display labels remain translatable UI content.';
COMMENT ON TABLE public.system_column_field_sets IS
    'Reusable named dataset field collections. NULL owner_user_id marks a shared collection.';
COMMENT ON TABLE public.system_view_field_set_assignments IS
    'Active per-view field collection. NULL user_id is the site default; a user row overrides it.';
