-- 20260822000001_create_system_row_groups.sql
-- Creates reusable multilingual groups and polymorphic memberships for registered dataset rows.
-- Bridges global classification concepts with rows without requiring one bridge table per dataset.
-- Exists so projects can group content and settings without comma-separated labels or one fixed taxonomy dimension.
-- VERSION_DB: 9.3.0

CREATE TABLE IF NOT EXISTS public.system_row_groups (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        TEXT        NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9][a-z0-9_-]{0,63}$'),
    title       JSONB       NOT NULL CHECK (jsonb_typeof(title) = 'object' AND title <> '{}'::jsonb),
    description JSONB       NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(description) = 'object'),
    sort_order  INTEGER     NOT NULL DEFAULT 0 CHECK (sort_order BETWEEN -100000 AND 100000),
    enabled     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by  BIGINT      REFERENCES public.system_users(id) ON DELETE SET NULL,
    created     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.system_row_group_memberships (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id          BIGINT      NOT NULL REFERENCES public.system_row_groups(id) ON DELETE CASCADE,
    table_uid         INTEGER     NOT NULL REFERENCES public.system_db_tables(table_uid) ON DELETE CASCADE,
    row_id            BIGINT      NOT NULL CHECK (row_id > 0),
    target_stable_key TEXT,
    created_by        BIGINT      REFERENCES public.system_users(id) ON DELETE SET NULL,
    created           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated           TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_system_row_group_membership UNIQUE (group_id, table_uid, row_id),
    CONSTRAINT ck_system_row_group_memberships_stable_key
        CHECK (target_stable_key IS NULL OR char_length(btrim(target_stable_key)) BETWEEN 1 AND 500)
);

CREATE INDEX IF NOT EXISTS idx_system_row_group_memberships_row
    ON public.system_row_group_memberships (table_uid, row_id, group_id);

CREATE INDEX IF NOT EXISTS idx_system_row_group_memberships_stable_key
    ON public.system_row_group_memberships (table_uid, target_stable_key)
    WHERE target_stable_key IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_system_row_group_memberships_stable_key
    ON public.system_row_group_memberships (group_id, table_uid, target_stable_key)
    WHERE target_stable_key IS NOT NULL;

CREATE OR REPLACE FUNCTION public.set_system_row_groups_updated_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.set_system_row_group_memberships_updated_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'update_system_row_groups_timestamp'
          AND tgrelid = 'public.system_row_groups'::regclass
    ) THEN
        CREATE TRIGGER update_system_row_groups_timestamp
            BEFORE UPDATE ON public.system_row_groups
            FOR EACH ROW EXECUTE FUNCTION public.set_system_row_groups_updated_timestamp();
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'update_system_row_group_memberships_timestamp'
          AND tgrelid = 'public.system_row_group_memberships'::regclass
    ) THEN
        CREATE TRIGGER update_system_row_group_memberships_timestamp
            BEFORE UPDATE ON public.system_row_group_memberships
            FOR EACH ROW EXECUTE FUNCTION public.set_system_row_group_memberships_updated_timestamp();
    END IF;
END $$;

COMMENT ON TABLE public.system_row_groups IS
    'Reusable global row classifications. Localized title and description values use language-code JSON objects.';
COMMENT ON TABLE public.system_row_group_memberships IS
    'Polymorphic assignments from registered dataset rows to reusable system_row_groups.';
COMMENT ON COLUMN public.system_row_group_memberships.target_stable_key IS
    'Optional semantic identity retained beside row_id; the API records system_config.key automatically.';

WITH desired_tables (table_name, display_name, description, fk_display_column) AS (
    VALUES
        ('system_row_groups', 'Row Groups', 'Reusable multilingual row classification groups', 'slug'),
        ('system_row_group_memberships', 'Row Group Memberships', 'Generic assignments from dataset rows to reusable groups', 'id')
)
INSERT INTO public.system_db_tables (
    table_name,
    description,
    cached_oid,
    folder_id,
    schema_name,
    fk_display_column,
    filterbar_visible_by_default,
    is_removable,
    display_name,
    sql_dump_policy
)
SELECT desired.table_name,
       desired.description,
       classes.oid::INTEGER,
       (
           SELECT metadata.folder_id
           FROM public.system_db_tables AS metadata
           WHERE metadata.table_name = 'system_db_tables'
             AND COALESCE(NULLIF(metadata.schema_name, ''), 'public') = 'public'
           LIMIT 1
       ),
       'public',
       desired.fk_display_column,
       FALSE,
       FALSE,
       desired.display_name,
       'all'
FROM desired_tables AS desired
JOIN pg_class AS classes ON classes.relname = desired.table_name
JOIN pg_namespace AS schemas ON schemas.oid = classes.relnamespace AND schemas.nspname = 'public'
WHERE NOT EXISTS (
    SELECT 1 FROM public.system_db_tables AS existing
    WHERE existing.table_name = desired.table_name
      AND COALESCE(NULLIF(existing.schema_name, ''), 'public') = 'public'
);

WITH desired_tables (table_name, display_name, description, fk_display_column) AS (
    VALUES
        ('system_row_groups', 'Row Groups', 'Reusable multilingual row classification groups', 'slug'),
        ('system_row_group_memberships', 'Row Group Memberships', 'Generic assignments from dataset rows to reusable groups', 'id')
)
UPDATE public.system_db_tables AS target
SET description = desired.description,
    cached_oid = classes.oid::INTEGER,
    folder_id = COALESCE(target.folder_id, (
        SELECT metadata.folder_id
        FROM public.system_db_tables AS metadata
        WHERE metadata.table_name = 'system_db_tables'
          AND COALESCE(NULLIF(metadata.schema_name, ''), 'public') = 'public'
        LIMIT 1
    )),
    schema_name = 'public',
    fk_display_column = desired.fk_display_column,
    filterbar_visible_by_default = FALSE,
    is_removable = FALSE,
    display_name = desired.display_name,
    sql_dump_policy = 'all',
    updated = now()
FROM desired_tables AS desired
JOIN pg_class AS classes ON classes.relname = desired.table_name
JOIN pg_namespace AS schemas ON schemas.oid = classes.relnamespace AND schemas.nspname = 'public'
WHERE target.table_name = desired.table_name
  AND COALESCE(NULLIF(target.schema_name, ''), 'public') = 'public';

DO $$
DECLARE
    table_record RECORD;
    registered_table_uid INTEGER;
BEGIN
    FOR table_record IN
        SELECT unnest(ARRAY['system_row_groups', 'system_row_group_memberships']) AS table_name
    LOOP
        SELECT table_uid INTO registered_table_uid
        FROM public.system_db_tables
        WHERE table_name = table_record.table_name
          AND COALESCE(NULLIF(schema_name, ''), 'public') = 'public'
        LIMIT 1;

        INSERT INTO public.system_column_details (
            table_uid, column_name, data_type, co_number, created, updated
        )
        SELECT registered_table_uid, columns.column_name, columns.data_type,
               columns.ordinal_position, now(), now()
        FROM information_schema.columns AS columns
        WHERE registered_table_uid IS NOT NULL
          AND columns.table_schema = 'public'
          AND columns.table_name = table_record.table_name
          AND NOT EXISTS (
              SELECT 1 FROM public.system_column_details AS existing
              WHERE existing.table_uid = registered_table_uid
                AND existing.column_name = columns.column_name
          )
        ORDER BY columns.ordinal_position;
    END LOOP;

    UPDATE public.system_column_details AS details
    SET is_multilingual = TRUE,
        editable_in_ui = FALSE,
        updated = now()
    FROM public.system_db_tables AS tables
    WHERE tables.table_uid = details.table_uid
      AND tables.table_name = 'system_row_groups'
      AND details.column_name IN ('title', 'description');

    UPDATE public.system_column_details AS details
    SET editable_in_ui = FALSE,
        updated = now()
    FROM public.system_db_tables AS tables
    WHERE tables.table_uid = details.table_uid
      AND tables.table_name IN ('system_row_groups', 'system_row_group_memberships');
END $$;

WITH desired_functions (name, route, creation_spec) AS (
    VALUES
        ('system_table_tools.AdminRowGroupsHandler', '/api/admin/row-groups', 'Admin list/create API for reusable row groups.'),
        ('system_table_tools.AdminRowGroupMembershipsHandler', '/api/admin/row-group-memberships', 'Admin assignment API for generic row group memberships.')
)
INSERT INTO public.system_functions (
    name, disabled, created, updated, package, specific_table_related,
    creation_spec, rate_limit_amount, rate_limit_minutes, url_route_endpoint, ui_only
)
SELECT desired.name, FALSE, now(), now(), 'system_table_tools', FALSE,
       desired.creation_spec, 200, 20, desired.route, FALSE
FROM desired_functions AS desired
WHERE NOT EXISTS (
    SELECT 1 FROM public.system_functions AS existing WHERE existing.name = desired.name
);

WITH desired_functions (name, route, creation_spec) AS (
    VALUES
        ('system_table_tools.AdminRowGroupsHandler', '/api/admin/row-groups', 'Admin list/create API for reusable row groups.'),
        ('system_table_tools.AdminRowGroupMembershipsHandler', '/api/admin/row-group-memberships', 'Admin assignment API for generic row group memberships.')
)
UPDATE public.system_functions AS target
SET disabled = FALSE,
    package = 'system_table_tools',
    specific_table_related = FALSE,
    creation_spec = desired.creation_spec,
    rate_limit_amount = 200,
    rate_limit_minutes = 20,
    url_route_endpoint = desired.route,
    ui_only = FALSE,
    updated = now()
FROM desired_functions AS desired
WHERE target.name = desired.name;

INSERT INTO public.system_group_table_func_rights (
    user_group_id, function_id, target_schema_name, creation_spec, target_table_uid
)
SELECT groups.id, functions.id, 'public', 'Filterest DB 9.3.0 row group administrator API', NULL
FROM public.system_user_groups AS groups
JOIN public.system_functions AS functions
  ON functions.name IN (
      'system_table_tools.AdminRowGroupsHandler',
      'system_table_tools.AdminRowGroupMembershipsHandler'
  )
WHERE groups.name = 'admins'
  AND NOT EXISTS (
      SELECT 1 FROM public.system_group_table_func_rights AS existing
      WHERE existing.user_group_id = groups.id
        AND existing.function_id = functions.id
        AND existing.target_table_uid IS NULL
        AND COALESCE(NULLIF(existing.target_schema_name, ''), 'public') = 'public'
  );

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'readeronly') THEN
        GRANT SELECT ON TABLE public.system_row_groups TO readeronly;
        GRANT SELECT ON TABLE public.system_row_group_memberships TO readeronly;
    END IF;
END $$;

INSERT INTO public.system_db_version (version, description)
SELECT '9.3.0', 'Added reusable multilingual row groups and generic row memberships'
WHERE NOT EXISTS (
    SELECT 1 FROM public.system_db_version WHERE version = '9.3.0'
);
